== Chapter 5

We landed in Philadelphia on fifth-day, the twenty-eighth of tenth month,
being just forty days from Liverpool: I accepted the invitation of our kind captain,
and dined with him this afternoon; he resides here when at home.
The yellow fever prevailing in the city at this time,
and many Friends as well as others having deserted it,
I went to Abington this evening and returned to the city next day,
and attended the select quarterly meeting,
which was small by reason of the prevailing fever, but it was a solid opportunity.
I returned to Abington in the evening, and on first-day attended meeting there,
which was also a good time.

Second-day, first of eleventh month.
Having taken cold, and it increasing, I became considerably unwell,
and stayed mostly about house until fourth-day,
when I attended the select quarterly meeting at Abington,
and next day a large quarterly meeting for discipline;
these were both solid instructive opportunities.
Seventh-day, sixth, went to the city and finding that the fever had subsided,
I resumed my old quarters.

First-day, the seventh, I attended the North meeting in the morning,
and in the afternoon that at Market street,
both of which were on the whole highly favoured seasons:
second-day attended the morning meeting of ministers and elders; third-day,
meeting at the North meetinghouse, fourth-day, meeting at Pine street,
and fifth-day the meeting at Market street again,
in most of which I got considerable relief indeed;
I hoped the late calamity would prove a blessing to many survivors;
may it not be too lightly looked over by any,
but be a means of arousing all from a false rest,
or too anxious a pursuit after perishable enjoyments,
as these awful visitations plainly tell us that we have no continuing city here,
and this is not the place of our rest.
Sixth-day, twelfth, I set out for New York,
being desirous to visit Friends there before I returned homeward; got to Burlington,
stayed over first-day, and attended meeting there to satisfaction.
On fourth-day seventeenth, got to New York,
where I met with a hearty welcome from many of my dear Friends,
who seemed to rejoice with me on my safe arrival in my native country.

First-day, attended the fore and afternoon meetings of Friends,
and in the evening a large public meeting appointed by Martha Routh,
in the last two I was pretty largely opened in
testimony much to the relief of my own mind,
and I believe to the general satisfaction of Friends;
indeed I think I never felt more openness in this city than at this time,
both among Friends and others.
We stayed this week and attended their preparative and
first-day meetings again to good satisfaction;
and on fourth-day, first of twelfth month was at the monthly meeting here,
also to our solid satisfaction:
next day in the evening a large public meeting appointed by a Friend,
from Purchase in this state,
in which I was opened and enlarged on several
subjects with clearness and gospel authority,
to the humble rejoicing of my own soul, and I believe of many more.
At the conclusion of this humbling season,
I took my leave of the people and bid them farewell,
and a very solemn and affecting farewell it
appeared to be to many dear souls then present.

Sixth-day, third, we left New York and got to Rahway,
and attended their two meetings on first-day,
in which through the renewed extendings of holy help.
Truth was exalted over all after much painful exercise; glory to the Lord forever.
On third-day, seventh, attended a monthly meeting at Crosswicks,
and the same afternoon got to Burlington, where we stayed over the week-day meeting,
and visited several of our Friends both in town and country.
Seventh-day, we got to Philadelphia and found the city in good health,
and our Friends there glad to see and receive us again.

First-day, twelfth, in the morning I attended the North meeting,
in the afternoon that at Pine street,
and in the evening a large meeting at Market street, in all of which I was silent,
except a few words in the latter part of the evening meeting.
Second-day, I attended the select morning meeting at Fourth street house,
which was a good time.
Next day, I attended the North meeting, which was very large,
and a bowed humbling season it was, to me and many more, blessed be the Lord.
Fourth, fifth and sixth days, attended the meetings at Pine street.
Market street, and also the Meeting for Sufferings, in all which I was silent.
First-day, nineteenth, attended North meeting in the morning.
Pine street in the afternoon, and a large meeting at Market street in the evening,
in all of which I was silent,
except a few words in the meeting at Pine street near the close,
and I have been thankful in believing that I was
preserved in these large meetings in the way of my duty,
and helped to keep the word of the Lord`'s patience,
though I know not the cause why I have been so much shut up since last in this city,
but an earnest solicitude has attended my mind, that the true, inward,
spiritual worship may be more and more sought after by me,
and all the professors thereof.
First-day evening, twenty-sixth, I have been at seven meetings since the above account,
in all of which I was silent.

Seventh-day, first of first month, 1803,
I have attended five more meetings since last entry, all silent, except one,
and yet I cannot see my way out of the city: Lord preserve me,
and enable me to hold fast my confidence in you,
strengthen me I pray you to abide every dispensation which you may see fit to order,
or permit me to be proved with,
though it be even to follow you through much tribulation and sorrow,
or into prison or even unto death--enable me O Lord to say in deed and in truth,
your will be done and not mine.

First-day, second.
I attended three meetings this day, in two of which I had some public service,
especially in the large evening meeting at Market street,
which was truly a humbling time.
I attended five other meetings this week, mostly silent,
except in a meeting for the school children,
where there was supposed to be upwards of a thousand collected;
to these dear children I had considerable communication.
First-day, ninth, I attended three large meetings again, also meetings on second, third,
fourth, and fifth days, mostly silent,
but cannot yet see my way any where out of the city.
Lord look down upon me in mercy,
and keep me near and watchfully attentive to the dispensations of your divine Providence.

First-day, sixteenth.
I attended Pine street meeting in the morning, which was very large,
and I was considerably opened in testimony, and found some relief.
I was at the Market street meeting in the afternoon, and again in the evening,
which last I thought was one of the most solid meetings of the kind I ever attended;
so much so,
that for the present it seemed as though there was not a soul
but what was sensible of the favours of this evening,
in which prayers and praises ascended up to Him who lives forever and ever,
and who is alone worthy thereof, through time and eternity.

Second-day, a favoured time at the morning meeting of ministers and elders: third-day,
attended the North week-day meeting, which was large: two Indian chiefs were at it,
and sat remarkably still and solid,
while I was engaged in opening several instructive passages respecting the
many revolutions which the seed of Abraham passed through,
before they entered into the land which God promised unto them as an inheritance.
This afternoon was their select preparative meeting, which I attended,
and this opportunity, I humbly trust,
will not soon be forgotten by some of us then present,
but be held in grateful remembrance before Him who was pleased to loose, as it were,
a seal, and let us into some of the mysteries of his kingdom,
so that my cup run over--I wept tears of humble gratitude,
under a sense of our unworthiness of these his unmerited mercies; may we profit thereby.

Fourth-day the nineteenth.
Attended Pine street meeting,
in which I was pretty largely engaged in testimony on some deeply interesting subjects,
with clearness and good authority;
in the afternoon I attended their select preparative meeting,
which was also a time of favour.
Fifth-day, twentieth, attended Market street week-day meeting, which was large;
I was opened in testimony in gospel authority, and this was also a bowed,
humbling opportunity; several Friends from the other meetings were also present.
Sixth-day, attended the Meeting for Sufferings, which was a time of favour.

First-day, in the morning I attended Pine street meeting,
which was a highly favoured season, much to the relief of my poor exercised mind;
in the afternoon attended the North meeting, which was a good time,
and in the evening the large meeting at Market street, which I sat through in silence,
and was well satisfied that I did so.
Second-day, twenty-fourth, attended the morning meeting of ministers and elders,
which was a time of favour.

Third-day, was at the monthly meeting for the Northern district, which I sat in silence,
and being very unwell I did not stay until they got through the business,
but went to my lodgings, where I continued poorly for several days,
and very low in my mind.
Lord, when shall I escape from this city?--O look down upon me in mercy, and be pleased,
if it be your blessed will, to show me what you would have me to do,
and also give me strength to perform what you are pleased to require.
O Lord, preserve me in your holy counsel, keep me in the hour of trial and temptation,
grant me patience ta endure all things for your name`'s sake: you know me altogether,
and the way that I take,
and that I cannot see aright unless you are pleased to open mine eyes;
neither can I walk in the right way, except you are pleased to lead me by your light,
and to guide me by the right hand of your power--O my God!

I did not go out to any meeting after the above-mentioned, until first-day, thirtieth,
in the morning, when I sat the North meeting through in silence.
Second-day, sat the morning meeting of ministers and elders in silence,
but my mind was covered with a peaceful calm; blessed be the Lord.
Second-day, seventh, I attended the quarterly meeting,
which was held at the North meetinghouse,
and was a very large and highly favoured meeting.
I was opened and enlarged in the authority of Truth,
and again enabled to preach the everlasting gospel from these words; "`What am I, O Lord,
that you have spoken unto your servant concerning my house for
a great while to come;`" and blessed be his ever adorable name,
through whose condescending goodness in the opening and
shedding abroad of divine light and life,
this was a day which I humbly trust will long be had in
grateful remembrance by many of us then present,
as a fresh memorial of the Lord`'s love and mercy to our souls;
blessed be his holy name forever.
Third-day attended a large meeting for the blacks at Market street,
wherein I was engaged in prayer and supplication
on behalf of this oppressed race of mankind,
in as awful a manner as I almost ever experienced,
and the meeting closed with great solemnity.

Fourth-day.
Attended a large quarterly meeting at Abington,
in which humble thankfulness and gratitude arose to our gracious Master,
who caused his own blessed Truth this day to be exalted
over all opposition in the minds of the people,
and the meeting concluded under a humbling sense thereof; we went on our way rejoicing,
and returned to the city.

Sixth-day, eleventh.
I had a religious meeting with the convicts in the state prison to good satisfaction;
and now, blessed be the Lord,
I seem relieved and quite easy to take my leave of the city, and look towards home.

Seventh-day, twelfth,
after a solid opportunity with the dear Friends where I have lodged so long,
I took my solemn leave of the city,
and being accompanied by my kind young friend John Morton, junior,
got to Darby that afternoon; next day attended the meeting there,
which proved a good time to me, and I believe to many more.
Second-day we went to Concord, and on third-day attended their quarterly meeting,
which was an exercising time to me, yet Truth seemed to get the victory,
and I felt pretty quiet and comfortable after meeting.

Fourth-day attended their week-day meeting at the same place, which was small,
but a blessed heavenly season it proved to be,
much to the comfort and refreshment of our minds.
The same afternoon went to Brandywine,
and next day attended the week-day meeting at Wilmington,
which was a time of close exercise with me, both private and public,
but I was favoured to leave the meeting with a peaceful mind, and was therefore content.
Went to London Grove, and seventh-day, nineteenth,
attended a select quarterly meeting there; first-day was at their meeting for worship,
and on second-day, a large quarterly meeting for discipline at the same place,
in all of which I was silent, except the meeting on first-day,
and then I got but little relief Third-day attended a large youths`' meeting,
in which I was silent throughout, I believe to the great disappointment of many,
but I could see no way for me to step forward to espouse the holy cause,
and therefore I endeavoured patiently to abide in my tent.
This evening went and tarried with Jacob Lindley,
and next morning several young people being present,
we had a precious heart-tendering opportunity, and next day set out for Baltimore,
but the roads being excessively heavy, we did not reach there until sixth-day,
the twenty-fifth, when we were favoured to arrive without any material accident.

First-day, twenty-seventh, were at the two meetings of Friends here, which were large,
being attended by a number not professing with us,
but I could see no way for me publicly to espouse the
holy cause in either of these meetings,
and therefore I sat them through in silence.
On fifth-day, third of third month, attended their week-day and preparative meeting,
which was also large,
and I was raised up in gospel authority to declare the everlasting Truth,
and the meeting concluded in solemn prayer,
after which I felt my poor exercised mind relieved from a great weight of oppression,
which has been my almost constant companion for some time,
and very much shut up both in and out of meetings.

First-day, sixth.
Attended both the meetings here again, which were large,
and I had pretty extensive public labour and exercise in both of them:
I think it may be said, they were humbling, baptising seasons,
and the day closed peacefully; blessed be the Lord, to whom be all the praise,
for he alone is worthy, both now and evermore.
Third-day, eighth, went out to Ellicott`'s mills, and attended a meeting there next day,
with a number of Friends and others, which was also a blessed time;
after this we returned peacefully to Baltimore.
Fifth-day attended their monthly meeting, in which I had considerable public service,
and it was on the whole a pretty solid time.

First-day, thirteenth.
Attended both the meetings again; in the first I was pretty largely opened in testimony,
but quite shut up in the afternoon, and not yet seeing my way clear to leave the city,
we stayed their week-; day meeting again, when blessed be the Lord,
I was enabled to clear my deeply exercised and oppressed mind,
and felt quite at liberty to leave the city the same day, which we did,
and got to Indian Spring that evening, about twenty-three miles,
and attended a monthly meeting there next day, which was a solid time.
First-day, twentieth, were at a meeting of Friends at Alexandria,
which was very dull and exercising for a considerable time,
but at length Truth and life gradually arose, until it became so exalted,
that many minds were bowed and humbled,
and enabled to return thanksgiving and praise to Him, who lives forever and ever.

Second-day, twenty-first.
We left Alexandria, and had no meeting in our way until we got to Burleigh,
on the south side of the James`' River,
where we attended a meeting with Friends on first-day, the twenty-seventh,
and the same afternoon got to Black Water, and next day to Suffolk.
Third-day, twenty-ninth,
a Friend from our country having appointed a meeting at Summerton, we attended it,
and it was a solid, good time.
On fourth-day, thirtieth, I reached my habitation,
and found my dear wife and family all well, and glad to see and receive me again;
and I rejoiced to see them,
and to find that they had been preserved and abundantly cared for by a kind Providence,
during my absence.

I was from home on this journey three years, one month, and ten days,
in which time I travelled by land and water, about fifteen thousand miles.
Thus, O Lord my God, in whom I have endeavoured to repose my trust,
you have carried me through many heights and depths, perils and dangers; yes,
perils by sea, perils by land, and perils by false brethren;
and through all these did preserve me.

When your billows went over my head, and my heart was ready to melt within me,
even then did you make bare your arm for my deliverance,
and sustained me by your matchless goodness,
and made me to see your wonders in the great deep; then you were there,
and guided me by the right hand of your power,
that I should not be swallowed up by the proud waves, when they roared about my head,
and threatened destruction.
Thus your countless mercies, O Lord, have been round about me in all the way,
and you have brought me safely back again to my dear connections at home;
for all these your mercies, O Lord, I desire to bless and praise your name,
which is great and adorable forever.
And now, O Lord, I am not worthy of all these your mercies;
yet since you have been pleased of your unmerited bounty to grant them hitherto,
and have given me to speak well of your name in the congregations of your people,
even to some of the nations afar off, be pleased to remember and not forsake me,
in my future steppings along through the remaining part of my pilgrimage here.

Preserve me, O my God, and deliver me from all my enemies, both within and without,
for you know them all, and see their snares, even before they are laid;
give me to see and strength to shun them all, both on the right hand and on the left,
even unto the end,
that so I may be enabled to bring honour and praise unto your
great name through all the remaining part of my days here,
and unite with those who, in unceasing anthems,
sing your everlasting praise beyond the grave.
Amen.

My kind young friend, John Morton, junior, who came home with me,
only stayed one day before he returned homewards,
being desirous if possible to reach home before their yearly meeting.
I was reluctant to part with him so soon, for I loved him dearly,
and I hope his kindness and attention to me will meet its reward.
First-day, third of fourth month,
I attended our own meeting for the first time since my return;
and had some communication in a public way;
as also once or twice within a few weeks afterwards,
but my way in this respect soon became quite closed up,
so that I almost became a wonder to my friends and to the people.
How hard it is for wise people to become fools;
indeed it seems as though they would rather remain
fools than become wise through this medium.

In the latter part of the fifth month,
my dear wife and I attended our quarterly meeting in Pasquotank,
which was a suffering time to me, accompanied with some very awful sensations;
but the vision was sealed, and not then to be opened to the people,
and I was thankful for preservation in what I believed to be my lot,
though deeply trying; however, on the last day of the meeting, being first-day,
and a mixed multitude gathered, my mouth was opened among them,
and many were broken and melted down as before the Lord;
may it be remembered to our lasting profit as the Lord`'s doing,
which is ever marvellous in the eyes of his children.
I felt considerable relief after this meeting, and returned homewards,
calling to see a few of my old acquaintances and near friends,
at one of whose houses we were favoured with a heart-tendering opportunity,
to our mutual comfort and refreshment.

We got home pretty directly after the quarterly meeting, where I have been ever since,
pretty much engaged in instructing some poor children, in our neighbourhood,
and attended our meetings constantly as they came in course,
and almost as constantly silent therein,
not having opened my mouth in more than three or four meetings for worship,
perhaps in near six months,
and frequently witnessing as great desertion as I almost ever experienced,
insomuch that that scripture was often remembered by me,
"`for I think that God has set forth us the apostles last, as it were appointed to death;
for we are made a spectacle to the world,
and to angels and to men,`" About these days my
situation was that of secret mourning and lamentation,
not for the dead, but for them that were gone into captivity,
and for the slain of the daughter of my people.--O, Lord,
by whom shall Jacob`'s seed arise, seeing it is so small and oppressed.

In the latter part of the tenth month, I attended our yearly meeting,
held this year at New Garden, about two hundred miles westward from my dwelling.
I returned my certificate to the meeting of ministers and elders,
which they had given me in 1799, to travel in Europe;
and also produced several from Friends in Europe,
expressive of their satisfaction with my travels in those countries,
which were read in the meeting.
At the same time I gave some little account of my visit,
particularly that to the newly gathered meetings on the continent,
which was very affecting to the minds of many.
On the whole it was a memorable season, and I think it might be said,
that the yearly meeting throughout was a time of favour,
which we have abundant cause to remember,
with heart-felt thankfulness and gratitude to the Father of mercies.
Several ministers from abroad were at this meeting,
with prospects of visiting the several branches thereof,
which seemed renewedly to evince that our vineyard is not yet wholly forsaken,
notwithstanding the very little fruit which it has produced in
proportion to the care and abundant labours of the great Husbandman,
which demands our humiliation and endeavours for amendment,
lest many of us be miserably destroyed, and the vineyard let to others.

Not having any further prospect at this time than to attend the yearly meeting,
I returned pretty directly home, and found the city as it were,
still encompassed and threatened with desolation,
and my prospect of returning to the mire and dungeon was so discouraging,
that I was ready to make my request to the king,
that "`I might not return to the house of Jonathan,
lest I should die there;`" and as yet I have no
assurance that I shall not be as deeply plunged as ever;
yet if it be consistent with infinite wisdom, either for my own refinement,
or if it may eventually redound to the good of others, I submit, though tremblingly.
Lord, look down in mercy and preserve me.

Eighteenth, nineteenth and twentieth of eleventh month, were held our select,
monthly and general meetings, in all of which I was opened in gospel authority,
once more to declare the everlasting Truth to our own people at home.
These were humbling seasons;
may the Lord of the vineyard sanctify them to our improvement.
After these meetings I felt considerably relieved from a great weight and burden,
with which my spirit had for a long time been clothed.
Twenty-second, I attended the burial of a youth belonging to our meeting,
who deceased after a very few hours illness; it was a memorable season,
and I hope will prove as a nail fastened in a sure place to some then present.
This week I also attended our quarterly meeting at Pineywoods;
the select meeting was on sixth-day, meeting for business on seventh-day,
and a large meeting for worship on first-day, all of which were seasons of high favour,
especially the last two,
in which many blessed God for the renewed offers of his salvation.
Amen.

1804+++.+++ Having been apprehensive from the manner in which
my mind has been exercised for several years past,
and more especially since my return from Europe,
that my future religious labours would be chiefly in
the northern and eastern parts of this continent,
insomuch that I was induced to believe it my duty to resign myself up
to the prospect of removing with my wife to New England;
I accordingly communicated my prospects to our preparative and
monthly meetings in the second month of this year,
and a committee of men and women Friends was appointed in the monthly meeting,
to take the matter under their consideration, and to visit us on the occasion;
my mind felt sweetly calmed in this resignation to apprehended religious duty.

I attended our quarterly meeting in the latter end of this month, held at Little River,
in Perquimons, and also several other meetings in that county,
which were mostly exercising and laborious,
but on the whole tended considerably to the relief of my own mind.
I also attended a public meeting at Gate`'s Courthouse, appointed by a Friend from Ohio.

Third month tenth,
the committee appointed by our last monthly meeting to enquire into our circumstances,
and to visit us on the subject of our removal to New England, met at our house,
and divine Good attending the opportunity in a remarkable manner,
they unanimously concluded that the movement was right,
and encouraged us to attend to our prospects; it was a watering time,
which tended much to our strength and encouragement.
Seventh-day, seventeenth,
at our monthly meeting the committee reported
their care and sense respecting our removal,
and having prepared certificates for us, they laid them before the meeting.

This was also an affecting time,
sundry Friends from other monthly meetings being with us;
after a time of solid deliberation and sympathy,
Friends generally seemed induced to believe it their duty to resign us,
and accordingly signed our certificates with much unanimity and great solemnity.
After which my poor exercised mind felt humbly thankful,
in being enabled once more thus far to make a full surrender of myself and my all,
for the glorious cause I had embarked in,
and which at times has been more precious to me than my natural life,
or anything I possessed in this world.

First-day, twenty-fifth,
at our meeting I was favoured with rather uncommon peace and tranquillity of mind,
and towards the latter part of it, I had considerable communication,
I thought with a good degree of clearness;
but very soon after meeting a fear possessed my mind, that it had been too much my own,
or at least that notwithstanding the vision seemed to be clear,
I had taken my own time in opening it to others,
and for a considerable time after I felt miserable.
Lord, if it be your hand that is thus chastening me, go on, spare not,
nor let your eye pity until you have made a full end,
and brought me into unreserved conformity to
your own blessed mind and will concerning me,
as you are pleased clearly to manifest it to me on all occasions; that so, O Lord,
I may be preserved watchful and attentive,
not only to the opening of your holy visions of light, but also to the times and seasons,
as you are pleased to make them known in your own blessed power.
So, O Lord, take unto you your own power,
and rule and reign both inwardly and outwardly over all, who are God over all,
blessed forevermore.
Amen.

Having now obtained certificates of removal,
I began to dispose of my little outward affairs,
in which I succeeded beyond my expectation, in much calmness and resignation.

In the fifth month, I attended the yearly meeting in Virginia,
and returned to my outward affairs with peace and tranquillity of mind,
and by the first of the sixth month, I so far accomplished the settlement of them,
that on the fourth, being the day appointed for our departure,
a considerable number of Friends and neighbours coming in to see us on the occasion,
we had a solid religious opportunity together, and then took our solemn leave of them,
and set out on this arduous journey.

We reached Suffolk in two days, though the weather was very hot,
and spent nearly three weeks about Western Branch, visiting our friends and relations,
and attending several meetings in the time;
and having agreed for a passage in a vessel bound for New York, we embarked,
the twenty-fourth of sixth month, and landed in New York on the first of the seventh.
The passage being tedious, and my dear female companions very sea-sick most of the time,
we stayed in New York until the ninth,
when we again took passage in a packet for New Haven,
where we arrived the next day about noon, and the day following went by land to Hartford,
the intended place of our residence,
where we arrived the same day about one o`'clock in the morning,
and met a cordial reception at the house of our kind friends, Thomas and Charity Rotch,
with whom we sojourned about six weeks.
In the course of this time I purchased a farm, agreeably situated,
about a quarter of a mile from the little meeting of Friends here,
but did not get full possession until the spring following,
but we took a couple of rooms in a Friend`'s house where we sojourned about seven months.

I spent most of the winter in keeping Friends`' little school here,
and about the twenty-sixth of the third month, 1805,
we got to our new habitation on the farm; and though it was very much out of repair,
we felt very glad and thankful in being favoured
once more to settle down in a cottage of our own,
having for a considerable time sojourned from place to place as poor pilgrims,
having no certain dwelling place.

After our settlement I went very little abroad, except to the monthly meeting of Oblong,
and the quarterly meeting of Nine Partners, of which we were now members.
This summer I also attended the yearly meetings of New York and Rhode Island,
and a few meetings at New Bedford, Providence, etc.,
and returned to my little family with solid peace of mind,
with whom I think I never enjoyed more sweet
comfort and satisfaction than about these days.
May the Lord preserve us in his love and fear,
and keep us thankful for the many favours which he has been
pleased to bestow upon us in these days of our pilgrimage.

I now felt at liberty to stay at home for some time, and attend to my domestic affairs,
in order to make my family as comfortable as our circumstances would admit of,
though constantly attending our own meetings both for worship and discipline,
for we had now a monthly meeting settled at Hartford.

1806+++.+++ About these days, temptations and trials seemed to assail me with redoubled force,
so that I was almost ready to conclude my best help had departed from me,
and I had scarcely strength to look up or cry for help,
either in meetings or out of them,
but verily was often afraid that I should finally loose my hold,
and fall into grievous and horrible temptations,
and so become yet a reproach to that blessed cause which I had once so much loved,
and thus the last error be worse than the first.
But blessed be the infinitely wise and merciful God,
who was pleased to regard even my weak efforts of desire towards Him,
and accept it as prayer; blessed be his holy name.
He is still a God hearing prayer,
and in tender mercy is pleased to accept the sincerity of desire,
when we have no words in which to call upon him; and when we can bear no more,
and are brought to see that all our own help has failed us,
he is then pleased to draw near, and repel the enemy, and deliver us out of his hand.
O, what shall I render unto you, says my soul,
who has been pleased thus to draw near and deliver me, yes,
poor helpless me!-- magnified be your blessed and ever adorable name, now, henceforth,
and forevermore!

I was mostly about home, except the attendance of our quarterly and yearly meetings,
until the fourth month, 1807, when I attended the yearly meeting of Philadelphia,
and several other meetings in the city and neighbourhood, to solid satisfaction;
and on my return took the yearly meeting of New York in the fifth month, and so home,
where I only stayed one week before I again set out,
and attended the yearly meeting of Rhode Island, and a few other meetings,
and soon returned home, where I stayed mostly until the latter end of the ninth month.
I then again left home,
in order to attend the yearly meeting of Baltimore in the tenth month,
which was to good satisfaction; indeed, I thought it one of the most solid,
instructive and encouraging opportunities of the kind I had ever experienced.

I have now attended all the yearly meetings for discipline in the world,
and some of them several times over, and I may remark,
that notwithstanding weaknesses and imperfections are still observable among this people,
yet I have had abundant cause to marvel at the preservation which is
still vouchsafed to them by the great Shepherd and Bishop of souls,
in keeping them so near together, in that harmony and oneness,
which ever characterizes his true followers.
May neither heights nor depths, principalities nor powers,
things present nor yet to come, nor life nor death, nor any other creature,
ever be able to separate them from this love of God,
which has been so marvellously manifested to them, through Christ Jesus our Lord.
I attended a number of meetings after this memorable yearly meeting,
to good satisfaction, and returned home with solid peace of mind.

Having had drawings in my mind for a considerable time to
visit Friends in some parts of Rhode Island and Massachusetts,
I obtained a minute from our monthly meeting for that purpose,
and set out in the latter end of the first month, 1808.
I was out in this tittle journey nearly three months,
and in that time attended about sixty meetings, sundry of which were public meetings,
appointed for those not in profession with us, which were largely attended by them,
and generally to solid satisfaction, insomuch that the priests at several places,
as well as the people, would desire another meeting;
but I dare not do anything of the kind in my own will;
and as I endeavoured to keep near my good guide,
and to be led about and instructed only by Him,
I humbly trust preservation was vouchsafed,
so that the holy cause of religion was not wounded,
nor the minds of any class of its professors hurt;
and I returned to my outward habitation with solid peace of mind; blessed be the Lord.

I went very little from home this summer,
except in attending our quarterly meeting at Nine Partners.
In the second month, 1809, I was at the quarterly meetings of Providence and Smithfield,
in Rhode Island,
and also several other meetings in the course of the journey in that state,
generally to good satisfaction; and in the fourth month,
having obtained a minute from our monthly meeting for the purpose,
I attended the yearly meeting of Friends in Philadelphia,
and spent some time in that city, much to my satisfaction.
I also visited some parts of its vicinity, as well as their West-town Boarding School,
which appeared to be in excellent order,
and attended the meeting on first-day morning with the children,
about two hundred in number, which was a blessed heart-comforting season;
indeed it was like a plentiful shower on tender plants; blessed be the Lord.

I also took several meetings in New Jersey, on my way to New York,
where I attended our own yearly meeting in the fifth month,
and then returned pretty directly home.
Lord, preserve me here in my lonely, pelican-like state,
for your rich favours I am not worthy to abide under; but if for the sake of others,
you are pleased at times to vouchsafe them, I magnify and adore your name.

I went very little abroad this summer, except in the latter end of the eighth month,
to our quarterly meeting at Nine Partners,
and spent about two weeks in visiting the meetings of
Friends in that and Stanford neighbourhoods,
to the satisfaction of my own mind, and I believe of Friends generally,
and I returned home with solid peace.
And now I may mention a trying dispensation,
which I have had to pass through for more than eighteen months;
indeed it has been nearly two years,
since my mind became impressed with a language which was intelligible to my mental ear,
saying, "`You have encompassed this mountain long enough;`" and I said in my heart,
"`What must I break up again, and become a sojourner?`"

For a time I saw not where I should go, and I said, "`Lord! where shall I go,
and where shall I sojourn?`"
and I seemed to be left under this conflicting dispensation,
without any sight or pointing to any particular place or service;
but after a time of sore conflict,
and seeking to know the blessed mind and will of the Lord concerning this thing,
at length a little meeting of Friends called Newton, in New Jersey,
a branch of the monthly meeting of Haddonfield, opened as the place,
within the verge of which I was to go and reside with my family.
This prospect became so impressive,
that I mentioned it in our meeting at Hartford more than a year since,
in order for their sympathy and communication, as way might open.
I had here a fine farm now in good order, and likely to be very productive,
so that we were comfortably settled as to the outward.
Ah!
Simon son of Jonas, how did you feel, when, under the blessing of heaven,
you had just made a fine draught in the line of your outward business,
and your divine Master queried, "`Simon, son of Jonas, do you love me more than these?`"
Yes, when your creaturely attachments were so closely tried,
and brought to the test by His querying even to the third time,
respecting your preference for Him, until you were grieved,
because you had previously professed to love Him; and yet even at the third query,
being sensible of your own weakness, you seem almost afraid to say "`more than these.`"
But He who loved you would prove your love, and therefore did tell you plainly,
that although in your younger years you did gird yourself,
and went whithersoever you would,
yet now if you "`love me more than these,`" or above all,
so as to go and feed my sheep and lambs at my bidding,
you must submit to be girded by another, even by me, and carried where you would not,
of your own inclination, go; but as though he had said for your encouragement,
"`never heed, Simon, only do as I bid you and all will be well,`" he says unto you,
"`follow me.`"

[.embedded-content-document.letter]
--

+++[+++Editor`'s Note: The meeting in the neighbourhood of Hartford was very small,
and the inhabitants generally Presbyterians,
who were not very favourably disposed towards Friends.
For some time after he resided among them, the prejudice against him was such,
that the people were scarcely willing to have any interaction with him,
or even to treat him with common civility.
It happened, however, that one of his neighbours was taken ill,
and as he was known to have some skill and experience in medicine,
his advice was solicited.
Visiting at the house necessarily brought him into their society,
and the means which he recommended proved effectual,
which seemed to prepare them for forming a more correct opinion of their new friend.
Another case of severe casualty occurred soon after he removed there,
in which his assistance was also requested,
and the discharge of these and other kind offices to the afflicted both in body and mind,
together with his consistent and steady deportment, his social disposition,
and his faithful maintenance of the testimonies and doctrines he made profession of,
soon produced a very agreeable change,
and removed the erroneous opinion which had been
previously imbibed respecting the Society.
His company was now sought by the most respectable inhabitants,
and there appeared much openness to receive the religious
communications which he sometimes found it his duty to make.

He was now a member of New York yearly meeting, which he regularly attended,
and in the course of his visits to that city,
he early perceived the buddings of the seeds of scepticism.
The same disorganizing spirit,
whose desolating influence he had sorrowfully witnessed in the Society in Ireland,
was soon detected by him, secretly endeavouring to insinuate itself among Friends,
under the plausible profession of superior light.

Having suffered much on account of this creeping, deceitful spirit in Ireland,
he hoped when he came from that country, he had left it behind him.
In this, however, he was mistaken,
and as soon as he perceived the first indications of its approach,
as a watchman on the walls of our Zion, he sounded the alarm.
Notwithstanding few were then willing to admit the effects,
which he early predicted would flow from the adoption
of the plausible opinions that were promulgated,
he felt himself constrained, as a steward that must render an account to his Lord,
solemnly and emphatically to forewarn his Friends of the danger,
if happily they might escape the deplorable consequences,
which he had seen similar sentiments produce in a
foreign land.]^
footnote:[Taken from [.book-title]#Memoirs of Richard Jordan#.]

--

I must now leave this seeming digression, and mention,
that as soon as I was fully satisfied in my own mind,
of the propriety of my giving up to this prospect, I requested a certificate of removal,
(which was some months ago,) and having now obtained one,
and having also settled my affairs, so that none should suffer by me,
I took my solemn leave of Friends and neighbours, and left Hartford with my family,
about the eleventh of the tenth month, 1809, and after a pleasant journey,
we arrived at Samuel Cooper`'s, near the place of our intended residence,
and met with a kind reception from that amiable family,
and at their invitation sojourned with them for a few weeks,
until our household goods arrived, which we had shipped round by water,
and we had got a little prepared for house-keeping,
which we commenced in the eleventh month, within a mile of Newton meetinghouse.

The good angel whom we believe to have been with us in all the way,
has still hitherto been near, comforting our minds in our lonely habitation,
in our solitary walks, and in our religious meetings,
enabling me to speak of his goodness among the people,
which seems to have endeared many of us one unto another.
And now, O Lord, you have seen all our temptation,
and the anxiety and tribulation of our souls;
we are here under an apprehension of its being according to your requiring,
and in your divine appointment.
Oh Lord, look down upon us, and be near unto us in all our temptations and besetments,
in all our tribulations and distresses,
and in all our goings in and out among the people.
Be pleased to remember us, we pray you, as among the poor and dependent ones,
that have daily need of your aid: we ask neither worldly riches nor honour; give us,
if it be consistent with your good will and pleasure, food and raiment convenient for us,
and be, O Lord, our strength in weakness, our riches in poverty,
and our present help in every needful time,
that so we may be enabled to honour you in your blessed cause on earth,
and bring praise to your great name through our lives and in our death,
who are God over all, blessed forever more.

1810, Fifth month, fifteenth.
I have had great satisfaction in the constant attendance of our little meeting,
as well as in some visits to the sick and afflicted,
as also some others among my friends,
and in the attending of our late yearly meeting in Philadelphia.
In the latter part of the fifth and forepart of the sixth months,
I attended the yearly meetings of Friends in New York and Rhode Island,
and a few other meetings in the course of the journey, to satisfaction,
which took up about six weeks.
I am now returned to my habitation again,
I think as sensible as ever of my entirely dependent state.
Lord! keep and preserve me low, and in a state of entire dependence on You,
who are the Giver of every good and perfect gift.

In the tenth month I attended the yearly meeting of Baltimore,
and also that of North Carolina, which was held this year at Little River,
in Perquimons county.
I also attended nearly all the meetings of Friends in these lower counties,
and had a few public meetings;
and also visited the place of my former residence in North Carolina,
and sundry of my near relations, both in that state and Virginia,
I was helped to labour in the love of the gospel
among my friends and isolations in this journey,
which I believe was accepted by many of them as a renewed visitation,
as well as by others to whom the gospel was freely preached,
and which tended greatly to the solid peace and comfort of my own mind.

On my way homewards I spent about a week at Baltimore,
in which time I attended sundry meetings with Friends,
and then returned pretty directly home to my family,
where I found all well and comfortable, for which I was truly thankful,
as well as for the many favours, preservations and deliverances,
through the difficulties and dangers I had encountered in the course of this journey;
blessed be the Lord.

1811, I attended the yearly meetings of Philadelphia and New York to satisfaction,
as also some of the neighbouring quarterly and
monthly meetings in Pennsylvania and New Jersey,
in the course of this year; and having now lived two years in a hired house,
I purchased a small house and lot near our Newton meetinghouse,
to which we removed in the spring of 1812;
and for some time after our removal I went not much abroad,
except to attend the yearly meetings of New York and Baltimore,
until the beginning of the year 1813, when, with the concurrence of Friends,
I visited the meetings along the sea coast in this state.
Although sensible that the seed of life lay low in many places where my lot was cast,
yet as I endeavoured to keep low, and dwell with it,
I was enabled to labour in the love of the gospel,
and at times to experience the arising and prevalency of it over all,
to our comfort and rejoicing.
I was favoured to return to my family in peace, after being out about five weeks,
in which time I travelled between four and five hundred miles,
and attended about twenty-three meetings with Friends and others, to satisfaction;
blessed be the Lord, our alone helper and preserver.

1814+++.+++ In the winter of 1814,
I spent a little time in visiting the meetings of Friends in Philadelphia,
to good satisfaction, and on my return,
my dear wife was seized with a malignant typhus fever, and was brought nigh unto death;
but the Lord had mercy on us, and raised her up again,
after a confinement of more than three months; for which favour I was truly thankful,
as the loss to me would have been inexpressibly great,
although I was well convinced that my loss would have been her unspeakable gain;
as her innocent soul through all her bodily sufferings,
seemed centered in a state of calm, quiet resignation to the divine will.
I was also thankful for the preservation of my bodily health,
so as to be able constantly to attend upon her through the whole:
may all these favours be remembered by us with heart-felt gratitude.
By the time of our yearly meeting in the fourth month, 1815,
my dear wife was so far recovered that I attended it.

I also attended the yearly meeting of New York in the fifth month,
and returned directly home; and in the tenth month following,
I attended the yearly meeting of Baltimore, much to the satisfaction of my own mind,
and returned pretty directly home to my domestic affairs,
where I enjoyed my health quite as well as usual,
until about the first of the second month, 1816, when I was seized with the ague,
which operated violently upon me, about once in twenty-four hours, for several days,
and my health was so affected by it,
that I was mostly confined in and about the house for several weeks,
in a very weak state.
But are not these dispensations of mercy, from Him who afflicts not willingly,
neither delights in grieving his children?
Afflictions are said not to arise out of the dust, nor troubles out of the ground,
and as He who is the Great Controller of events,
can sanctify all our troubles and afflictions to us,
and make them subservient to his own wise purposes,
may I improve under every afflictive dispensation which is permitted to befall me;
may they all be sanctified to my good,
and may He make them all subservient to his own wise purposes,
that I may acknowledge him in all my ways, and know Him to direct my paths; even so.
Amen.

1818+++.+++ Since the latter end of the year 1815,
I have not been out on any considerable journey,
but have apprehended that my business was much about home in
the attendance of our own meetings as they came in course;
yet not unfrequented I went to some of the neighbouring quarterly and monthly meetings,
and also attended our Meeting for Sufferings in Philadelphia.
Being now in the sixty-third year of my age,
my prospects seem much closed as respects long journeys,
feeling an increase of the infirmities attendant on advanced years,
though blessed be my gracious Helper,
I enjoy a good share of health and strength at present, considering my time of life;
yet the prayer of David seems prevalent, "`Cast me not off in the time of old age,
forsake me not when my strength fails.`"

1821+++.+++ Seventh month.
I have now been for most of two years, afflicted with a complaint in my chest,
which has rendered me unfit for much service;
yet I have been enabled to visit sundry neighbouring quarterly meetings,
and to attend our yearly meeting, as also our own monthly and particular meetings;
in which at times living desires are raised, that after the example of good old Simeon,
I may be found "`waiting for the consolation of Israel,`"

1823+++.+++ Eighth month.
My mind has long been burdened with hearing assertions made,
that every child coming into the world is placed precisely in
the same situation as Adam was when in Paradise,
or as he came out of the hands of his Maker,
and speaking slightly of the atonement of Christ,
bringing down that blessed suffering Saviour and Redeemer of
men to the level of other good persons in common.
Well would it be for such, in my apprehension,
if they would seriously consider the import of a part
of the apostle`'s comment on the law of Moses,
namely: "`He that despised Moses`'s law died without mercy under two or three witnesses;
of how much sorer punishment do you suppose he will be thought worthy,
who has trodden under foot the Son of God,
and has counted the blood of the covenant wherewith he was sanctified, an unholy thing,
and has done despite unto the spirit of grace; for we know Him that has said,
vengeance belongs unto me, I will recompense, says the Lord; and again,
the Lord shall judge his people:
it is a fearful thing to fall into the hands of the living God.`"
I am sometimes ready to tremble at beholding the signs of the times,
as relates both to church and state, and I think I never saw with greater clearness,
the necessity of being diligently engaged to feel after a foundation in ourselves,
if happily we may be favoured, at least at times,
with a comfortable evidence that it is the sure one,
on which alone there is safety and preservation;
and the awfulness of feeling which sometimes covers my mind,
seems to produce a solicitude at least, if not something like a prayer,
for myself and for those of my Friends whose situation may somewhat
resemble that of those who wept as between the porch and the altar;
"`Lord increase our faith.`"

1825+++.+++ Having now for several years been very much indisposed in my bodily health,
I have not been out on any long journey,
though mostly able to attend our own yearly and other meetings,
and a few neighbouring quarterly meetings, as also a yearly meeting or two,
until last summer and fall, when I got very little out,
but was favoured so far to recover my health as mostly to get to our own meetings,
as they came in course, during the past winter.

And now what shall I say more.--The Lord has been
pleased in the inscrutable counsel of his will,
to take from me my dear partner,
who ended her useful life in this world on the morning of the second of third month last,
almost without sickness or pain, in the seventy-third year of her age;
being as well as usual the day before, and engaged in her domestic concerns.
We had sojourned together for most of half a century,
and I could say much of her virtues,
not only as a faithful helpmeet in our outward concerns,
but in always giving me up cheerfully to the service of Truth,
and sustaining my absence with Christian magnanimity,
and sympathy with me in my labours and travels in the cause of Truth and righteousness,
and a consoling evidence attends her departure,
that she has sweetly fallen asleep in Jesus; and therefore though I sorrow,
yet not as those who have no hope;
for surely I am one in faith with the apostle of our Lord,
that "`them that sleep in Jesus, will God bring with him.`"
And now, O Lord, you have taken the mother with the children,
and left me behind a little space longer in this state of probation,
for causes known only to yourself;
for you are not bound to give account of your matters to any;
it is enough for us to know that you do all things right;
and will do for us more than we can ask or think.
But because you are a God hearing prayer,
be pleased O Lord to be near by your secret power,
and keep and preserve me during the short remainder of my time in this world,
so that I may be enabled to finish the good fight,
and keep the faith of your beloved Son, Jesus Christ our Redeemer and Saviour,
and so finish my course with joy; for you, O Lord,
are faithful who have promised a crown of righteousness.
Amen.
