== Addenda.

After the decease of his dear wife,
our beloved friend seemed to pass the remainder of his days,
as a servant waiting for the coming of his Lord,
having a clear foresight that his earthly pilgrimage was nearly accomplished,
and several times spoke of his decease as being at hand.
He attended the yearly meeting of New York in 1826, and shortly after,
in the seventh month, was at three of the monthly meetings in Philadelphia,
and spent some time in visiting his Friends there, much to the peace of his own mind,
remarking, when about to return home,
that if it proved his last visit he should be well satisfied with it.

In the eighth month he attended the quarterly meetings of Abington,
and of Salem held at Woodbury.
On his way home from the latter,
his mind was much engaged in contemplating the
present situation of the Society of Friends,
lamenting with much feeling,
the deviations from simplicity and plainness
which were conspicuous in many of the members,
the avidity with which they pursued the pleasures and riches of the world,
and the apparent lack of religious concern on their own account,
and for the welfare of the church.
Much labour, he remarked, had been bestowed upon them;
spiritual and temporal blessings had been dispensed with a liberal hand,
and yet disobedience and ingratitude had been
too generally returned for all these favours;
and he feared lest those who might be considered as the children of the kingdom,
if they persisted in this course, would be cast out, and others raised up,
as from the stones of the streets,
to support the doctrines and testimonies given to Friends to bear.
He however expressed,
that gloomy as the prospect of a succession of upright standard bearers seemed,
he had faith to believe,
that those doctrines and testimonies never would fall to the ground;
and although many were predicting that the present commotions within our borders^
footnote:[The difficulties which arose from the
unsoundness of Elias Hicks and his followers.]
would disorganize the Society, yet this would not be the case,
but those who continued to maintain the ancient faith and discipline of Friends,
would be preserved as a distinct body of Christian professors.

On parting with the Friend who accompanied him,
he alluded to his late visit to the city of Philadelphia,
and after expressing the great peace he felt in recurring to it,
observed that it would be his last visit.
The Friend expressed his earnest desire that the
solemn presentiment might not be realized,
and remarked, how much he would be missed at the present time of trial;
to which Richard Jordan replied, "`Yes, but you must part from me at some time,
and perhaps it will be as easy now as ever,`" repeating
the assurance that it would be his final visit.
This was on fifth-day afternoon, the eleventh of eighth month,
and on the following day he was taken sick.
After this he attended meeting but a few times,
being mostly confined to the house or bed,
except occasionally riding out for a change of air and exercise.

His last illness was tedious, continuing for more than two months,
and while the gradual decay of his bodily powers was apparent,
the strength and vigour of his mind seemed to remain unimpaired almost to the close.

He did not appear disposed to converse much on ordinary topics or temporal affairs,
but at times made many instructive remarks upon religious subjects.
He mourned over the desolating effects of the spirit of unbelief, which,
under the plausible but false pretext of exalting the "`light within,`" was leading
many incautious minds into a denial of the saving truths of Christian Redemption,
and a disregard of the plain and irrefragable testimonies contained in the sacred volume,
declaring, as his full belief,
that all those who were really led by the spirit of Christ,
would feel themselves constrained reverently to believe in,
and to acknowledge all that is recorded in the holy scriptures,
concerning the coming and sufferings, the death and offices,
of our Lord and Saviour Jesus Christ, as he appeared in the flesh at Jerusalem.

He several times mentioned his firm conviction at that solemn period,
that painful as is the present state of things among us,
to the true disciples of the Lamb,
it would be made the means of purifying the Society of much of its dross;
that such as stood faithful in their allegiance to Christ,
would be deepened by it in the life of religion,
and some of them would live to see the Society in a far better state than it now is.
He had seen, he said, that the Lord would take the cause into his own hand,
and none should be able to hinder him--that he would choose his own instruments,
and those of this Society who had been highly favoured,
but who had turned their backs and forsaken Him, would be cast out,
and others brought in,
who would stand for the honour of His great name and for His cause in the earth.

On the sixteenth of the ninth month, a Friend calling to see him,
he made some observations on the nature of his disease,
and intimated that he thought his recovery doubtful,
considering his advanced age and the great prostration of his strength;
but he several times remarked, that he had no will but the Lord`'s will.
"`Yet,`" added he, "`I have lived to see the end of one revolution,
(meaning, as he himself explained it, in the Society of Friends in Ireland,
during his visit there,) and if it was the Lord`'s will,
I should have no objection to see the end of the
troubles that have come over the Society in this land.`"
With much feeling and deep sorrow he then expressed his
concern for those under the name of Quakers,
who, by giving way to their creaturely wisdom and carnal reasoning,
have departed from the Christian faith,
the principles and doctrines of the religions Society of Friends.^
footnote:[Elias Hicks and his adherents.]
With much emphasis, he said, "`Oh,
what will those men do that deny the divinity of our Lord and Saviour Jesus Christ?
What refuge will they have at such time as this, on a sick-bed--Oh,
what will become of them!`"
Once he said, "`I would not be in their state for anything in the world.`"

He intimated, that during this sickness he had had great opportunity for reflection,
both by day and by night,
and he had thought much upon the awful state of those people that deny the Lord,
and the only hope of salvation -- "`which, added he, is by the mercy of God,
through the merits and grace of our Lord Jesus
Christi`" Then with much emphasis exclaimed,
"`My hope, my only hope for salvation is in the mercy of God,
through the merits of Jesus Christ,`" These, or words nearly like them,
he repeated several times during the conversation.
He commented very instructively on the ground of this his hope,
and the great stay and consolation it was to his mind.
"`Oh,`" said he, "`I would not give this hope in the mercy of God, through Jesus Christ,
for the whole world.`"
He then proceeded to relate, that during his illness, many scripture passages,
both in the old and new Testament,
had been unfolded to his mind with great clearness and comfort,
respecting the plan devised by Divine Love for the restoration of poor fallen man,
and the salvation of sinners.

After setting forth the fall of man through the temptation and subtlety of Satan,
and his aspiring above the condition allotted him by his beneficent Creator,
he proceeded to open some of those passages,
beginning with the promise of the Seed of the
woman that should bruise the serpent`'s head.
Genesis 3:15; adducing many other scripture testimonies,
which show that this Seed is Christ, even He who died for our sins on the cross,
and who is a propitiatory sacrifice for the sins of the whole world,
our advocate with the Father, and Mediator between God and man.
He enlarged upon what faith in God, and in our Lord and Saviour Jesus Christ,
had done in every generation, and then emphatically said, "`this is also my faith,
and I shall die in it as I have lived,
hoping in God`'s mercy through our Lord and Saviour Jesus Christ.`"
He made many other remarks at the same time,
that evinced his deep solicitude on account of
the spirit of infidelity which had crept in,
tracing its origin to the pride of the human heart.

On second-day, the eighteenth of the month, a Friend being with him,
he made some instructive observations on the present situation of the Society,
and with much tenderness of feeling mourned over the young and inexperienced,
who were deluded by the fair pretences of some who were considered leaders of the people,
and whom they had been accustomed to look up to
as examples and instructors in the church;
while these were taking advantage of the influence they had obtained,
to inculcate pernicious principles,
and infuse into their unsuspecting minds the poison of unbelief.
For these unwary youth, thus exposed to the artifices of designing men,
he manifested tender commiseration and sympathy.
But he said, he believed the time was coming, and perhaps was not far distant,
when these false teachers would be fully exposed.

There were many, he remarked, who went under the name of Friends,
that had never been convinced of, nor yielded obedience to,
the principles and doctrines of the Society, but had made a mere empty profession;
and it was no marvel if such as these were carried off
with the unsound notions which were now promulgated.

He believed it had been permitted,
in order to manifest such as these--as a Society we were very impure,
and needed much sifting to make us as we should be.
But he was firm in the faith, that the ancient doctrines and principles of the Society,
as set forth in the Holy Scriptures,
must and would prevail over all opposition--
that all those who were building on Jesus Christ,
would be preserved amid all the storms and commotions which now agitate the Society,
and that it would yet arise and shine in more of its ancient beauty,
than many now living have ever seen it; adding, "`I may not live to see it,
but there are some of you that will.`"

He expressed much more during the course of this interesting conversation,
not only manifesting the calm and confiding state of his mind,
and his unshaken faith in the Rock of Ages on which he had built,
but also his full conviction,
that the Christian faith of the Society of Friends would eventually triumph;
and that after the necessary conflict and suffering were endured,
to purify it from such nominal professors as hold the truth in unrighteousness,
and bring reproach upon the name of Christ by
their unholy conduct and unchristian opinions,
the Society would be enabled to rise superior to its present difficulties,
and with renewed brightness hold up the light of a Christian conduct, conversation,
and profession to the world.
Great was the anxiety he evinced,
that the Friends of Christ and his holy cause might stand firm in a patient,
persevering testimony against every innovation, whether in doctrine or discipline;
and by the steadfastness of their faith, the purity of their lives,
and the meekness and humility of their spirits,
evince that while they dare not strive to carry party views and schemes,
they felt themselves constrained by a sense of religious duty,
earnestly to contend for the faith once delivered to the saints.

A meeting having been appointed near his residence,
by a person who held and promulgated the new notions,
he appeared under much exercise of mind respecting it,
and greatly concerned at the sorrowful consequences which
resulted from the dissemination of these unsound views,
and with great earnestness asked a Friend who sat by him,
"`can nothing be done to prevent these persons from
going about sowing their pernicious principles.`"

To a Friend who called to see him, he observed, "`it is a satisfaction to reflect,
that my outward concerns are all settled;`" after a solemn pause, he added,
"`I know that I am a poor creature,
and have nothing to depend on but the mercy of a gracious God, through Jesus Christ,
my Lord:
Oh! these poor things that are trying to do away all belief in
the authenticity of the scriptures and in a Saviour,
what will become of them?
No other foundation can any man lay than that which is laid.`"

In the conversation with this Friend he observed, that his day`'s work was accomplished;
to another of his Friends--that he did not feel as though he had much more to say,
but was labouring after true stillness and patience,
to be gathered to the Source of all good; and throughout the whole course of his illness,
it was obvious that his mind was often engaged in deep, inward, awful retirement,
and waiting on the Lord.

The disease gradually made its progress;
and though the symptoms attending it were not very alarming,
yet he seemed impressed with the belief that he should not survive it.
When his Friends would express their hopes of his recovery,
though he seemed unwilling to give them pain by positively saying he should not,
yet his replies generally evinced that he had no prospect of it.
Once he said, his friends must exercise a patient hope,
he had not seen that he should get well.
At times his bodily sufferings were very great,
but he was preserved in much patience and resignation to the Lord`'s will,
often exclaiming with earnestness, "`O blessed Saviour, O Lord Jesus,
help me!`" showing that his dependence was placed on the Physician of value.

A few days before his decease, he remarked to a Friend who was with him,
"`the crisis has not been shown me, when I shall be taken but from the way I feel,
it seems as if it could not be much longer;`"--the Friend replying,
"`then you do not think you will recover`"-- he answered,
"`I leave it all to Him who knows how to order all things for the best;
I have no desire but that his blessed will may be done.`"

On sixth-day night, the thirteenth of tenth month,
he became much worse--his strength was fast failing,
and the power of articulation almost gone--and
about three o`'clock on the following morning,
the near approach of death was apparent.
He was in great suffering for a few hours, but about ten in the morning,
the conflict seemed over, and exhausted nature ready to sink away:
he said nothing during this time, except exclaiming with uplifted hands,
"`O Lord,`" which were his last words.
He breathed shorter and shorter, until about a quarter after eleven,
when his purified spirit quietly departed to the mansions of eternal glory.

His remains were interred in Friends`' burial ground at Newton, on second-day,
the sixteenth of tenth month, 1826, after which a large and solemn meeting was held.
