[quote.epigraph, , Daniel 12:3]
____
And they that be wise shall shine as the brightness of the firmament;
and they that turn many to righteousness as the stars forever and ever.
____

== Chapter 1

It has been much upon my mind, of late,
to throw together some short memorandums of sundry occurrences which have happened to me,
and also of the gracious and merciful dealings of a watchful Providence;
through whose mercy and superintending care over me, from my childhood,
I have experienced many preservations and deliverances, both inwardly and outwardly,
during the various vicissitudes which have attended my pilgrimage through time;
if haply they may afford instruction or encouragement
to any Christian traveller when I am no more.

I was born at a place called Elizabeth, in the county of Norfolk, and colony of Virginia,
the 19th day of the twelfth month, 1756, of honest parents,
whose names were Joseph and Patience Jordan.
They were both in profession with the people called Quakers,
and endeavoured to train up their children in
the principles which they themselves professed;
but my mother dying soon after the birth of her seventh child,
and I being the youngest but one of the surviving six,
have but a faint remembrance of her.
My father was at times much from home in the course of his business,
and there being no religious meeting near us, we were left exposed,
without a friend to associate with;
and I think I never was at the Friends`' meeting house more than twice,
during our stay in that part of the country,
which was until I was about twelve years of age.
About this time, my eldest brother, who had been some stay to us, died;
and soon after my father removed with the rest of the family to North Carolina,
(a short time previous to the American revolution,) and we
became members of the meeting of Friends at Richsquare,
which was about six miles from our residence.

During all this time, and for several years after,
nothing very remarkable respecting myself, occurred,
only that I remember I was early visited by something,
that impressed my mind with a sense and belief
in a state of future rewards and punishments.
I had heard much talk about a heaven and a hell,
but the impressions I now felt were different from those produced by this kind of talk;
for I was made to feel something of their power,
and from that time was sensible of great disquietude and distress of mind,
when I had been guilty of using bad words or actions in my play, or at other times;
and I was also sensible of calmness and peace of mind,
when I had been more watchful over my conduct.
I saw then that this state of mind was greatly to be desired,
but alas for the poor fallen nature which Adam`'s children are clothed with;
what proneness to evil rather than to good!
Notwithstanding I was often chastised in spirit for my misconduct,
insomuch that I cried and promised amendment, yet when these stripes were withheld,
how did I run again into the same excess of folly and dissipation!
For although my lot was now cast more amongst Friends,
so as frequently to go to their meetings,
yet many of the children and youth amongst them, who became our associates,
were worse than many of my former companions,
whose parents made no profession with Friends,
so that I believe I arrived at a higher pitch of
folly and dissipation in a few years among them,
than I had ever done before.

That day at length came, when, blessed be God, I was made to see that I was undone.
The axe was then laid, indeed, to the root of the corrupt tree,
and that which did not bring forth good fruit must be hewn down and cast into the fire.
This is the day of Christ; and who can abide it!
But if a separation +++[+++from evil]
is not now suffered, according to the doctrine of that very Christ himself,
all must be cast into hell;--alas, who can bear the thought!
No,--I must leave my companions in folly,
and endeavour to submit to the dispensation of a separation;--
but truly it was a day never to be forgotten,
wherein my situation, I suppose, resembled that of Legion,
who saw the Redeemer coming towards him in order to make the separation, and cried out,
Jesus thou Son of God, most high, art thou come hither to torment us before the time.
Ah! it seemed verily as if the pains and torments of hell had laid hold on me,
even now while in the body, before the time of final judgment and sentence was come,
and the decree sealed, "`that time should be no longer.`"
Well might the prophet query, to what end is it that ye desire the day of Lord,
seeing it is a day of darkness and not of light, even very dark, and no brightness in it.
Ah! sinner, how canst thou abide it--yet,
remember that this is only parting with the offending hand, and the offending eye,
and is it not better to endure the pain of parting with these,
which will only continue for a time, rather than to be cast bodily,
that is with all thy sins and multiplied offences, into hell,
"`where the worm dieth not and the fire is not quenched!`"
How can I bear the thought; and yet, how can I abide the conflict!
But is there any thing new under the sun?
was not the ministration of condemnation, to the rebellious sons of Israel,
a day of terrible burnings, and the blackness of darkness,
and of mighty thunder and lightnings, and the sound of a trumpet;
which so awakened and wrought upon their senses,
that they trembled exceedingly and durst not behold?
And yet they soon returned to their folly.
Oh, how could they so soon forget what they had seen,
as even to form to themselves new gods!

But in the day of Christ,
when he visits and brings under the ministration of condemnation for sin;
it penetrates the heart; it stirs the powers within,
and is not so easily eradicated from the mind.
For indeed, such was the conflict of my spirit for days, and weeks, and months,
that when it was day I wished for night, and when it was night, I wished for day;
during which time the enemy of my soul was not wanting
with his temptations and evil suggestions,
insomuch that at times my mind was almost constantly assaulted with evil thoughts,
and I abhorred myself, until I thought, that of all the creatures which God had made,
I was the most wretched and miserable.
And when I had no faith to believe that my condition would be better,
then the tempter endeavoured to persuade me to put an end to my miserable existence,
as the only way to get relieved from my pain, sorrow, and distress.
I had so far given way to this temptation,
that I was contemplating in what manner I should effect it so as to be the quickest over,
and give the least pain; when, adored be the ever blessed Redeemer,
I was brought so near to Him, as to cast myself down at his feet,
and the language of my heart was.
Lord, if I perish, let me perish here; let me go no farther away from thee.

For some time this was mostly my cry,
until at length I felt a little secret hope that I should yet obtain mercy;
and I said in heart.
Oh, Lord, if thou wilt pardon and deliver me I will serve thee.
I will follow thee whithersoever thou art pleased to lead me;
and will do whatsoever thou commandest me,
if thou wilt be pleased to be with me and show
me the way in which thou wouldest have me to go,
and what thou wouldest have me to do,
even although it be to tell what great things thou hast done for my soul.
After a time it seemed as though my cries were heard, and the conditions accepted,
and I soon began to think that I should be
called to publish the glad-tidings of the gospel;
the prospect of which became very awful to me, for I thought myself too vile a creature,
and in no way qualified for such an undertaking.
Then I concluded I would endeavour to be as good as I could,
without attempting this awful work, for I was afraid of it,
lest if I should undertake it, I might again slide into some weakness, if not wickedness,
and become the subject of contempt and ridicule,
and so the last state be worse than the first.

Thus I reasoned away several years, sometimes in hope I should get along in this way,
then again almost in despair, and in great fear of falling quite back again.
I did not always resist temptation to sin,
and so at times brought upon myself great trouble and distress;
though I may remark with thankfulness, that I never, in any part of my life,
lost my reputation amongst men,
and in this respect perhaps stood as fair as most of my age and experience in the world.
But, ah me,
I have seen that it is possible to fulfill all those duties which relate to civil society,
and are due to our neighbours, while those which we owe to our Creator are almost,
if not altogether neglected.
Much of my iniquity and transgressions was now of this kind,
and I was often sinning and repenting, repenting and sinning again.
O, merciful God! long-suffering and long-forbearing! how hast thou followed me,
and often brought my covenant with thee into remembrance, and like an indulgent Father,
showing me at times, in part, the blessed, hidden recompense of reward.

Sometimes I had precious openings in meetings,
insomuch that at length I thought I would yield, and at one time in particular,
it was so clear and powerful that I laid my hand on my knee in order to rise,
but being fearful, I thought I would try it a little longer,
until at length the opening gradually disappeared and was quite withdrawn from me.
But like the fruitless figtree, I was mercifully spared for several years longer,
without being wholly forsaken, and cut down; sometimes unstable as water,
and then again experiencing a little more stability.

At length I concluded that if I was married and settled,
my situation would be more favourable to rny religious prospects,
as I was much exposed in the world.
I was now ready to enter into covenant in this respect,
and to say "`If thou will be pleased to grant me this, and direct my steps herein,
then I will assuredly yield to thy requirings.`"
Oh! indulgent heaven! even my request for right direction was granted,
my marriage was reputably accomplished, and I settled down with my companion,
who was a young woman that sustained an amiable character in the world,
and whose religious education far exceeded mine: her name was Pharaby Knox,
youngest daughter of Thomas Knox, who was for many years before his death,
an approved minister among Friends.

My own father possessed a number of slaves, and offered me several of them,
to help me work: but my mind for several years before,
had been so thoroughly impressed with a belief
that it was not right to keep them as slaves,
that I modestly declined accepting them, although it cost me some displeasure from him,
as he had not then fully seen the iniquity of the practice.
I had to lay my hands to hard labour,
yet I felt a peaceful conscience in the course I had taken,
and thus I got on pretty quietly for a time,
especially as I had become an advocate for the oppressed black people,
and many Friends were now setting them at liberty.
But still, when weighed in the balance, I was found wanting;
and was brought to see and fully believe,
that notwithstanding God approves of every act of moral righteousness,
benevolence and justice, yet he requires the heart to be devoted to Him;
and while this is wanting, our hope of salvation can never be permanent;
there is still something wanting that cannot be numbered;
the mind is left in unsettlement and not established on
that foundation which is immovable,
and against which all storms and tempests beat in vain.

After I had thus struggled and wearied myself for several years,
endeavouring still to get along in my own way,
until I had well nigh silenced those heavenly calls to revealed duty;
a travelling friend came to our meeting, and was led to minister to my state,
(which no mortal knew of by information from man,) in such a manner,
that I accepted it as a renewed visitation from that same gracious Father of Mercies,
who had been so long striving with me.
This dear servant, who had left all to follow his blessed Master,
was made instrumental to strengthen in me the weak things that remained,
so that I was once more enabled to renew my resolutions; and in a short time after this,
I was raised upon my feet in a small meeting then held in a Friend`'s house,
near my habitation.
I expressed but a very few words, greatly to the surprise of those present,
but the peace and sweetness which flowed into my soul after the meeting,
were better felt than described: indeed I could not, neither did I wish to describe it,
but soon got home in order to be quiet.

I think I did not speak again in meeting for some weeks,
and notwithstanding my call to this work seemed so indubitably clear, yet my appearances,
for several years, were but seldom, though I could perceive they were generally approved,
and acceptable to Friends.
But I was afraid of having more top than root, and thought if I must be a preacher,
I greatly desired to be one of the right sort; yet my progress in this work was so slow,
that I was often doubtful of ever coming to much in that line, I think,
as well as I can now recollect, it was about the twenty-fifth year of my age,
when I first began this work; and I did not venture out on any considerable journey,
within the space of ten years.
I was however frequently made use of in our meetings for discipline,
under appointments to sundry services in Society,
and also travelled on several small journies in the work of the ministry,
within that time,
I believe to the general satisfaction of Friends and others where my lot was cast.

Between the years 1790 and 1797,
I several times attended the general Assembly of the state,
on behalf of the oppressed Africans among us,
in company with others appointed by our yearly meeting,
in order to remonstrate against some existing laws,
which had opened a door for much injustice,
to be committed against the rights and liberty of that people.

I was also engaged to travel on foot to several places,
where great cruelty and injustice had been exercised,
in taking up and selling such negroes as had been liberated by conscientious persons;
and I had some memorable opportunities among them.
During the same period I also travelled considerably in the state of Virginia,
and attended several of their yearly meetings to satisfaction.
