== Chapter 2

Having had drawings in my mind at times for several years,
to pay a religious visit to some of the northern and eastern states,
I laid my prospect before our monthly and quarterly meetings,
and obtained certificates expressive of their unity and concurrence with me therein;
and my esteemed friend Josiah White, of Perqimans county,
agreeing to be my companion in this weighty undertaking,
also obtained the concurrence of the monthly meeting to which he belonged.
We set out on the seventeenth of the third month, 1797,
and met at our friend Ann Scott`'s at Western Branch, Virginia, on the eighteenth,
and next day being first-day we attended their meeting,
in which I sat as an example of silence to the people.
We returned to Ann Scott`'s, tarried that night,
and next day rode as far as Thomas Pretlow`'s,
and the day following reached Barnaby Nixon`'s at Burlejgh.

Here we met our dear friends Benjamin Albertson and wife,
who accompanied us next day to Burleigh meeting, which was a low time to me,
and mostly silent, except a few words near the conclusion.
We went that evening as far as John Hunnicutt`'s,
and thence took our journey by way of Petersburg and Curies,
and spent a day with my ancient and honourable relative Robert Pleasants.

Twenty-fifth.
We proceeded by the way of Richmond, and in the evening reached Micajah Crew`'s,
near Cedar Creek: next day being first-day we attended their meeting,
where I was silent throughout: after meeting went to Clark T. Moorman`'s,
who with his dear Rachel accompanied us next day to Caroline,
where we had a meeting on the twenty-seventh, in which I had some communication,
but it was a laborious time.
On the following day we were accompanied by Matthew Terrill;
baited at the house of a kind man in Fredericksburg,
and had a religious opportunity with him and his wife to good satisfaction,
and reached Robert Painter`'s at Stafford the same evening; had a meeting there next day,
which was also an exercising time, both during the silence,
and in the utterance of a short testimony.

We got to Alexandria on the thirty-first,
and on first-day the second of fourth month attended
two meetings there to a good degree of satisfaction:
second-day went to Sandy Spring in Montgomery, and the day following had a meeting there,
which was a time of deep wading,
but I was favoured to get through to a good degree of comfort, blessed be the Lord!
Went that evening to Samuel Snowden`'s, and the next day, being the fifth,
had a satisfactory meeting at Indian Spring.

On fifth-day the sixth, we set out for the Clifts nearly fifty miles, through a poor,
hilly and dreary country; had a small meeting with the few under our name there;
and on our way back another at West River,
where Friends are so reduced in number that no regular meeting is held,
though formerly it was the place of their yearly meeting.
Here I was baptised for the little remnant left under our name, and had to mourn,
as over the city of their fathers`' sepulchres, which seemed to lay without walls,
gates or bars, and encouraged them to arise if possible, and endeavour to rebuild them,
that they might not be thus exposed to the incursions of their potent enemies,
which had almost brought desolation upon that place.
They seemed much affected with the visit and with the testimony of
truth at that time--I wish they may profit under it,
for I believe some of them were made sensible that it
was a fresh visitation to a declining people.

This part of Maryland is so generally cleared of timber,
that in riding about fifty-two miles,
I think we passed about one hundred and twenty-five gates,
set up across the road to save fencing.

On our return to Indian Spring, it being first-day,
we attended another meeting with them and rode the same day as far as Elk Ridge,
and next day had a comfortable meeting there.

On the following morning we went to visit a sick friend,
and after a comfortable opportunity at our lodgings, with the family,
and several others who were present, we called to see Benjamin Banneker, a black man,
an astronomer.
He showed us a copy of an almanac which he had just calculated for the succeeding year,
also a clock which he had made several years ago, I think he told us,
without any instruction.

After some conversation on these subjects, I felt my mind engaged, in a weighty manner,
to recommend him to turn his attention inward, and seek after the knowledge of God,
the Creator of all, who is the Giver of every good and perfect gift,
and hath bestowed a measure of his divine grace on all men,
in order that they might glorify him in their day and generation,
and when time here shall be no more,
receive a crown immortal in that world which is to come;
this being the great end for which he created them,
which man never can arrive at by all his skill
and knowledge in the secrets of nature or art;
or something to this import.
He seemed somewhat affected by the communication, and enquired after my name,
saying he would record it.

We went that afternoon, the eleventh of the fourth month, into Baltimore,
to the house of James Carey, and finding that the small pox prevailed in the city,
as it had done in several places we had passed through before,
we became somewhat intimidated respecting the disorder, in looking forwards; however,
we attended their monthly meeting, which was on the thirteenth;
and having solidly weighed the matter,
we concluded to take the small pox by inoculation, and our kind friends aforesaid,
having offered their house and assistance, the operation was performed on the fourteenth.

We had great attention paid to us by this kind family and several of their neighbours;
and I got through the disorder favourably, for which mercy I felt thankful in heart.
My dear companion had it much worse than myself, for on the third day,
the doctor finding that instead of the pock making its appearance,
his fever had nearly left him, his pulse slow and confused,
and little or no inflammation in his arm, but the part rather sunk and livid,
recommended him to dine on solid food,
take a glass of wine and exercise himself by walking, which was all attended to;
and whether from this circumstance or the state of his blood,
the pock made its appearance soon after, in great abundance.
They filled very slowly, and he was sometimes not without the appearance of danger,
yet through the particular care and attention of the physician and kind nurses,
under the blessing of a kind Providence, he was brought safely through,
for which we were humbly thankful.

These circumstances occasioned my detention in this city much longer than I had expected,
being nearly six weeks; though towards the latter end of that time,
my companion getting better, I attended a meeting at Ellicott`'s mills to satisfaction;
was also at sundry meetings with Friends in the city,
and had three public meetings for those not professing with us.
I had also a religious opportunity with the masters and scholars in the academy,
as well as many private opportunities, and I may say with humble thankfulness,
that my little dedications here,
have through divine help tended greatly to the relief of my poor depressed mind;
and feeling as I apprehended, fully clear of this place for the present,
I left my dear companion to the care of very kind
friends and to the protection of Divine Providence,
and set out on the twenty-ninth of fifth month
for the Eastern shore of Maryland and Delaware.
Rode that day to Gunpowder, and next day had a meeting there to satisfaction,
after which I went to Fawn in the border of Pennsylvania,
and on the following day attended their meeting; rode about twenty miles that evening,
and next day was at the meeting at Little Falls, which, on the whole,
was a time of favour.
After meeting we called to see William Amos, senior,
an ancient friend who had not only travelled much,
but also suffered greatly on Truth`'s account; rode that evening to Bush,
and had a meeting there next day, which tended to our solid comfort and rejoicing.

We went that evening to Joshua Husband`'s at Deer Creek,
and the next being first-day attended the meeting at that place, which was large;
many not of our Society came, and the gospel was freely preached to them,
showing why Jesus Christ was pleased to manifest himself unto his immediate followers,
and not unto the world, giving them to understand the mysteries of the kingdom of heaven,
while he spake unto others in parables.
It was a season of divine favour,
wherein thanksgiving and praise ascended to Him who liveth forever and ever!
We crossed the Susquehannah river that evening at a place called Bald Friars,
where the current was very rapid and more than a mile over, and next day,
fifth of sixth month, had a meeting at Little Britain,
and the following day attended an appointed meeting at East Britain,
which I hope was profitable to some.
We then went to a meeting appointed at West Nottingham,
where I was favoured to clear my mind in a close searching testimony,
warning the negligent and lukewarm professors,
yet had a word of comfort and encouragement to the few mourners in Zion.

On the ninth we had an appointed meeting at East Nottingham,
where that eminent servant of the Lord, John Churchman, formerly belonged;
this was a pretty large meeting,
and I hope will prove a profitable season to many if carefully improved.
Next morning, after a solid opportunity in the family of George Churchman,
I proceeded on my journey and reached Appoquinimink in the evening;
attended the monthly meeting at Duck Creek on the following day,
and on first-day the eleventh was at Friends`' meeting at Little Creek,
which was a favoured time.
At four in the afternoon, I had a public meeting in the State house at Dover,
which was very large and a good time; the people seemed glad of the opportunity.
On the twelfth had a meeting at Canterbury,
and the following day attended the monthly meeting of Motherkill,
which was a time of favour.
In the evening went to Camden,
and on the fourteenth had a public meeting there to satisfaction:
indeed there seemed to be great openness in the minds of the people generally,
in these parts,
and they flocked together in abundance at a very short
notice when they heard there was to be a public meeting.

On the sixteenth we had a meeting at a little village called Fredericka,
where no Friends reside, which was a solid, good time;
here Warner Mifflin and his wife met us,
and we had a meeting the same afternoon in Friends`' meetinghouse at Milford,
and on the next day one at Coolspring, which was a dull exercising time,
it felt to me as though they were settling upon their lees.
We lodged at a Friend`'s house,
where we had a religious opportunity in the evening to some satisfaction,
and on the day following, being first-day, we attended Coolspring meeting again,
where I was favoured to clear my mind in a close searching testimony;
may it be remembered to profit.
Next day, in the forenoon, had a meeting in the courthouse at George Town,
and another in the afternoon at a little village called Dagsborough,
both to a good degree of satisfaction.

From this place we went to the house of a respectable man, in the state of Maryland,
and after a satisfactory religious opportunity in his family,
we proceeded into Accomack county on the Eastern shore of Virginia,
and had a solid meeting next day among a sober people at Horntown;
went in the evening and lodged with a justice of the peace, and the day following,
being very rainy, we rested.
On the twenty-fourth crossed the Chinkoteague Bay, about seven miles,
to an island of the same name,
and had a comfortable meeting with a few sober people there; returning the same evening,
and there-being eleven of us in a small fishing boat and the weather rather blustering,
the passage was not without the appearance of some danger,
but we were favoured to get safely to land.

Twenty-fifth.
Being first-day,
we had a pretty large meeting in the morning in
the dwelling-house of the late Daniel Mifflin,
and another at the same place, in the afternoon, for the coloured people;
both were satisfactory.

The day after, we rode about eighteen miles to the house of a justice of the peace,
who appeared to be fully convinced of our principles and was very loving towards Friends;
he took me in his chaise next day to Accomack courthouse, where we had a public meeting;
and returned to his house the same evening.
The twenty-seventh, returned up to Mifflin`'s place,
and had a comfortable opportunity with the young people who occupied the house, who,
though not members of our Society,
entertained us very hospitably,--this opportunity was
like a morsel of living bread broken amongst us,
under a humbling sense whereof we took our leave,
and that day reached a little town in Maryland called Snowhill,
a noted place for ship-building, where we had a meeting in the courthouse,
which afforded me some relief, though I believe it is a place of great dissipation.

We tarried here this night, at the house of a person,
who with his wife and daughters were very kind and civil to us;
next day went to Salisbury and had a meeting that evening in a large inn,
which was satisfactory, though the people were generally light and gay on coming in,
yet they seemed much humbled under Truth`'s testimony,--blessed be the Lord!
Next day we proceeded to Easton and lodged; and on first-day the second of seventh month,
we had a meeting in the forenoon at a place called the Fork,
and another in the afternoon twelve miles further at Centre,
both among the Nicholites and to satisfaction:
the testimony of truth went forth freely amongst them, which they received with gladness.
They are a plain people, both in their dress and manners,
and much esteemed by their neighbours for their
uprightness and honesty in their dealings,
and I was induced to believe that many of them were not far from the kingdom of heaven.
We went that night and tarried with James Harris,
who is said to be the principal leader among this people,
and is I believe an honest good man.
He entertained us with much affectionate kindness,
and at parting expressed his gladness at my company,
taking his leave of us in a very friendly manner.

We had an appointed meeting with Friends of Marshy Creek,
where I was painfully exercised throughout the meeting in silence;
yet found relief in the conclusion, from the belief that I was in the way of my duty;
then went on across Choptank river,
and on the following day attended meeting at Choptank, which,
in the forepart was very exercising, but towards the close,
truth arose and gave the victory -- blessed be the Lord!
Proceeding thence, we were at several meetings, viz., Bayside,
the preparative meeting at Easton, Tuckahoe,
a public meeting in the courthouse in Easton, a meeting at Choptank Bridge,
and another at the head of Chester, with Friends and others, mostly to satisfaction.
The next meeting was appointed to be held in Friends`' meetinghouse at Chester.
As I approached this place I felt under an inexpressible cloud of exercise,
insomuch that as I sat in meeting,
it seemed as though the very pains of death and hell had laid hold on me.
I thought I was never more sensible of the necessity of earnestly crying
unto Him who alone is able to rebuke the storm and raging of the sea,
and to save us from sinking; and as this was my fervent cry in this meeting,
blessed be his name, he was pleased to hear in this hour of distress,
and cause the sea to cease from raging,
and give ability to exalt his testimony over the
heads of even whoremongers and murderers,
for such there were present (as I afterwards understood)--towards the latter
end of the meeting it seemed as though the powers of hell were shaken,
and the great name was praised and exalted over all, who is worthy forever!

On fourth-day the twelfth, were at Cecil meeting, which was also a time of deep exercise;
a spirit appeared to prevail amongst them not much unlike that of the Egyptians formerly,
which refused liberty to the chosen seed,
until a darkness covered them which was to be felt:
there was much labour bestowed in order to bring them to a sense of their condition;
but alas! it seemed to have little effect for the present--the
increase must be left with him alone who hath power to give it.
Next day we attended an appointed meeting at the head of Sassafras,
where was a number of people not professing with Friends,
some of whom were from the head of Chester, nine or ten miles off,
and others from the neighbouring villages, who behaved with becoming order and solemnity,
while the gospel was freely and largely preached amongst them,
which they appeared to receive with gladness.
It was given me to believe that there is seed in these parts near to be gathered,
if Friends keep their habitations in the truth; which is the prayer of my soul for them:
dined at the house of a hopeful young man, and a number of other Friends being present,
we were favoured with a comfortable opportunity together.

Journeying thence we got to Appoquinimink, and next day had a meeting with Friends there,
which was a time of favour, wherein a remnant were given to rejoice in God`'s salvation:
we reached White Clay Creek the same evening, and here I met my dear companion,
Josiah White,
after a separation of more than six weeks--we
were truly rejoiced to see each other again.
Next day being the seventh of the week, we rested, and on first-day in the forenoon,
attended Friends`' meeting at White Clay Creek;
then rode to Wilmington and attended their afternoon meeting, which was large,
but dull and poor to me.
I sat it through in silence, I believe to the great disappointment of many,
but I was thankful in being preserved from gratifying the itching ears.
We rested on second-day and wrote letters to our friends,
and on third-day attended an appointed meeting at Chichester, which was a large, solid,
good meeting: went that evening and tarried with John Tolbert,
whose dear wife was then in Europe on a religious visit;
he appeared to bear her absence with becoming resignation.

Next day we had a meeting at Chester which was rather a low laborious time:
Lord! more and more show unto thy people the necessity of labouring for daily bread.
Rode to Darby, and on the following day attended a large meeting at this place,
which was also a time of deep exercise, but truth arose and gave us the victory,
blessed be the Lord therefor!

Several Friends from Philadelphia met us here, and in the afternoon,
the twentieth of seventh month, we went into the city: next morning, being market day,
we walked in the market, which both for quantity and quality of the provisions,
far exceeded any market I had ever seen;
and amongst the many thousands of people which I supposed to be there,
I was much delighted in observing not only the cleanliness in every department,
but the orderly conduct of the people;
insomuch that I do not remember to have heard a single oath repeated,
or any indecent behaviour, but all seemed to be conducted in peace and harmony,
which yielded real satisfaction to my mind.

On first-day we attended Market street meeting in the morning,
where I had a pretty open time in testimony, and it was a solid good meeting:
in the afternoon attended the North meeting, which was to me laborious,
but I was favoured to get through to a good degree of satisfaction.
On second-day morning we went to the meeting of ministers and
elders held in Fourth street meetinghouse,
after which we returned to our lodgings and were
visited by a number of our valuable friends.
Third-day attended the monthly meeting for the
Northern District where I had good service,
to the comforting and tendering of many minds and much
to the relief of my own--praised be the Lord!

In the evening several Friends came in, and being drawn into solemn silence,
the divine presence was felt to be near, and we had a heart tendering time together,
like a refreshing shower from heaven on the thirsty ground,
under an humbling sense whereof,
praises and thanksgiving ascended up to Him who alone is worthy forever!

We attended the monthly meeting held at Pine street meetinghouse on fourth day,
where I was opened into the mystery of the holy waters
as seen by the prophet in the vision of life,
pointing out the glorious work of reformation,
and the spreading of the kingdom of Christ Jesus upon earth.
It was an humbling time,
in which the hearts of many were made renewedly
thankful to the Lord for the continuance of his mercies,
especially the remnant who were engaged to travail with the seed,
and who waited for the consolation of Israel.
We visited several Friends in a social way this afternoon,
and next day went to the preparative meeting at Market street,
which was also a solid and good meeting.
In the evening on returning to our lodgings we found a
number of Friends who had come in to see us,
and after a time of pleasant conversation, being drawn into stillness,
I was opened in testimony, and it proved a blessed opportunity,
like the distilling of the precious dew of heaven upon our spirits;
it was the Lord`'s doing, giving us to rejoice together in his blessed presence;
praised be his name forever.

On sixth-day, we attended the monthly meeting of Philadelphia, for the middle district,
held in the Fourth street meetinghouse: here I felt such an exercise on my spirit,
that I was ready to cry out,
"`for Zion`'s sake I cannot hold my peace;`" and as I gave up thereto,
a door of utterance was opened upon the subject of the evil spies, who,
after they had been favoured not only to see the good land,
but also to eat of the fruit thereof,
and to bear some of the clusters on their shoulders in the sight of the people,
brought in an evil report, and made the hearts of many to melt,
because of their discouragements and unbelief.
This was opened and set before us in the light of the gospel,
to the bowing and humbling of many minds; for which favour,
thanksgiving and praises ascended up to Him,
who thus mercifully continues his holy help to
the remnant of his people that trust in him;
Amen.
Went and spent a little time with our ancient and honourable friend James Pemberton,
and the meeting for business having adjourned to four o`'clock in the afternoon,
we sat with Friends again, and then went to see our worthy friend David Bacon.

We rested on seventh-day and wrote letters to our families,
and on first-day morning attended Pine street meeting, which was large,
many not of our Society being present: the Lord`'s power broke forth amongst us,
and I was engaged in testimony and supplication until I was almost faint;
the divine presence shone amongst us,
to the comfort and consolation of many hearts--blessed be the name of the Lord!
In the afternoon we were at Market street meeting, where I was silent,
but satisfied in the belief that I was in the way of my duty.

On second-day, the thirty-first of seventh month, we attended Abington monthly meeting,
held this time at Frankford, about five miles from the city, which was a favoured time.
We dined with Nicholas Wain at his country residence,
who with his dear wife were affectionately kind to us;
several Friends from the city also came in, and we had a religious opportunity,
to the solid comfort and refreshment of our spirits, after which we returned to the city.

Third-day we went to the North meeting, at which there was a marriage.
I was much exercised in the meeting, and had a clear opening on my mind,
but could find no way to express it, and went away with my burden and had a poor evening.
Next day attended Pine street week-day meeting, which was a time of close exercise,
yet I was enabled to wade through to a good degree of satisfaction.
We made a few social visits, and returned to our lodgings;
my mind in rather a poor stripped state.
Lord, grant me patience; preserve and help me, if it be thy blessed will,
that so thy holy cause may not suffer by me!
Fifth-day we were at the Market street meeting,
where I was led to treat on the subject of Solomon`'s
coming to sit on the throne of his father David,
and bringing his father`'s enemies to justice; this was a solid and good meeting.

Sixth-day, fourth of eighth month.
We kept pretty much to our lodgings, and wrote letters to our friends,
there being no meeting in the city.
On seventh-day, fifth, we attended the quarterly meeting of ministers and elders,
where I was largely opened on one of Daniel`'s visions,
and I believe it was to general satisfaction.

First-day, sixth.
We went to the North meeting in the forenoon, which was large.
I was opened on these words, "`that which is afar off and exceeding deep,
who can find it out;`" from which I was led to treat on the mystery of the true church,
of which the man Christ Jesus is head:
through the extension of holy help this was a blessed opportunity,
which I hope will not soon be forgotten by me, and many others present.
I soon retired to my lodgings after this meeting, being unwell,
but felt solid peace of mind.
In the afternoon, though still poorly, I attended Market street meeting,
which I was favoured to sit through in peaceful silence,
and returned to our lodgings with a thankful heart.
In the evening, several Friends coming to see us, after a time,
we were drawn into silence, and our gracious Master was pleased to favour us,
as with a celestial shower, to the comfort and refreshment of our souls;
under an humbling sense of which, praises and thanksgiving ascended up to Him,
who alone is worthy thereof forever.

On second-day the seventh, we attended the quarterly meeting which was large;
several Friends from the country being present,
and on the whole it was a solid and good meeting,
which I was favoured to enjoy in silence,
while several others were acceptably engaged in public communications.
After meeting we went to see the wife and children of our friend Thomas Scattergood,
he being at this time in Europe on a religious visit.--Third-day the eighth,
in the forenoon, a youths`' meeting was held, and in the afternoon one for the blacks,
but I continued so unwell that I did not attend either of them.

Fifth-day the tenth, getting better of my indisposition,
we attended the Market street meeting this morning which was large, perhaps more so,
on account of a marriage.
I felt very weak in body, but being soon clothed with an exercise of spirit,
I ventured to stand up and was opened on the subject of wisdom,
from which I was enabled to utter many gospel truths,
and the meeting concluded in solemn prayer and supplication to the Almighty Father,
for the continuation of his mercies towards us his poor dependent creatures.
This was a glorious meeting, wherein my soul, with many more,
were refreshed and enabled to thank God and take
courage in pressing forward in the heavenly journey,
looking unto Jesus the author and finisher of the saints`' faith; to him be glory,
dominion, and praise, forevermore.

Sixth-day, the eleventh.
We left Philadelphia and attended a quarterly youths`' meeting at Abington,
which was a solid season; at the house where we dined,
a considerable number of Friends came in, many of whom were young people,
and we had a satisfactory religious opportunity with them,
after which we went home with Peter Yarnall and wife to Byberry,
where we rested next day.

First-day the thirteenth, attended a meeting at Bristol which was large,
many not of our Society being present,
the gospel was freely preached to this auditory and the
people seemed humbled under Truth`'s testimony,
and behaved with a becoming solemnity throughout, much to my satisfaction,
although the meeting held near three hours;
many were made thankful and gave glory to God.
We called to see an ancient Friend in the afternoon and
had a religious opportunity in the family,
and then rode to William Blakey`'s.

Second-day, the fourteenth, attended an appointed meeting at Middletown,
which was the largest appointed meeting we have been at in this country.
I stood forth in the love of the gospel in this large assembly,
until my nature was well nigh exhausted ere I was aware of it;
but the Lord`'s truth was exalted over all,
insomuch that I was scarcely sensible of the want of anything;
blessed be his great name forever!

After the meeting was over I soon withdrew to William Blakey`'s with a thankful heart,
and in the evening had a comfortable opportunity
with the family and several other Friends,
some of whom were from Philadelphia.
Third-day, the fifteenth, attended a meeting at the Falls, which was also very large,
many not professing with us being there, who behaved well,
and seemed humbled under the testimony of Truth,
which was largely declared amongst them in its own authority.
This was a solid good meeting,
wherein thanksgiving and praise ascended to the great Shepherd of Israel,
who still continues to care for his sheep.

After meeting we went home with Jonathan Kirkbride,
accompanied by Peter Yarnall and wife; in the evening a number of young people coming in,
we had a religious opportunity among them to some satisfaction.

Fourth-day, sixteenth.
We left Pennsylvania and crossed over into New Jersey at Trenton;
attended an appointed meeting there the same day,
which was poor and dull in the forepart, but at length Truth arose and gave the victory,
and its own testimony was exalted.
After this meeting we rode to Stony Brook, and on fifth-day, seventeenth,
attended a meeting there which was a very exercising one to me:
I was opened on the words, "`Foxes have holes and the birds of the air have nests,
but the Son of Man hath not whereon to lay his head;`" and was favoured to get relieved.
We rode about twenty-three miles that afternoon, and next day got to Rahway,
where we attended the quarterly meeting of ministers and elders,
and on seventh-day the quarterly meeting for discipline.

First-day, we attended two large meetings for worship at the same place,
there being a very great number of people not of our Society,
to whom I was enlarged in testimony;
which went forth in a close searching manner to
the careless professors and to the sons of folly,
yet a word of comfort and encouragement was handed to the mourners in Zion,
who were made glad this day, for the exaltation of the Lord`'s truth over all,
under a humbling sense whereof,
praises and thanksgiving ascended to Him who liveth forever and ever.
Besides these memorable meetings, we had sundry private opportunities in this village,
in most of which our souls were humbled and melted down before the Lord,
under a sense of his living presence being felt amongst us,
whereby the stone was rolled away and the poor of his flock were
watered by the pouring forth of divine consolation into their souls;
glory be to his great name forever,
who hath not forgotten to be gracious to his humble depending children,
who desire to wait for him.
Second-day, the twenty-first, had a public meeting at Elizabethtown,
about five miles from Rahway, on our way to New York, which proved very laborious to me,
with very little prospect of much good resulting from it.

We got to New York that evening and took up our lodgings with
our kind friends Robert and Elizabeth Bowne:
on entering this large city I felt low and dejected in mind.
O Lord, look down upon me and preserve me through every trying scene.
Fourth-day, twenty-third, attended their week-day meeting, which was large;
I had considerable to communicate, and felt some relief.
We visited some of our friends, and returned to our lodgings,
where we spent most of the remaining part of this week;
for I felt so low and dejected in mind, that I could not think of much visiting;
but endeavoured to abide in patience, inwardly breathing to my gracious Master,
for preservation and right direction.
Our friends frequently called to see us in the evenings,
and some of these I hope were not unprofitably spent:
one of them in particular I thought was rather a remarkable time,
much of it being spent in solemn retirement, wherein several were broken into tears;
it was a heart-tendering time, though there was not a word spoken amongst us.
Seventh-day, still so low and shut up, that I stay mostly in my chamber.

First-day, twenty-seventh, attended the fore and afternoon meetings here;
the first was a glorious time, wherein Truth reigned over all,
to the humbling and bowing of many minds: the Lord`'s great name was magnified,
and the little remnant of his dependent ones sweetly comforted:
the last meeting was not quite so open as the first,
but I hope was a profitable time to many.
We called to see our ancient and honourable friend Joseph Delaplaine,
and then returned to our lodgings: in the evening a number of Friends came to see us,
and we were favoured with another heart-tendering opportunity together;
blessed be the Lord therefor.
Next day we went to visit an ancient Friend whose name was Henry Haddock,
he appeared to be not far from his final change;
we had a comfortable religious opportunity with him and his daughters.

Third-day, the twenty-ninth, we left New York, crossed the East river at Brooklyn,
and attended an appointed meeting at Newtown, which was small,
yet a door of utterance was opened to preach the
gospel in good authority to this small gathering,
most of whom were broken and tendered before the Lord,
and the meeting ended in prayer and thanksgiving: at the conclusion,
my poor spirit felt so relieved that I left the meeting with joy and gladness of heart;
glory to Him who said, "`I go away and come again.`"
We rode about twenty miles to Westbury, and lodged at the house of Gideon Seaman,
whose father is a very aged man and blind, but otherwise active,
frequently goes to meeting more than a mile on foot,
and seems cheerful and lively in spirit.

Fourth-day, thirtieth.
Attended the weekday meeting at Westbury,
where many Friends were collected who made a very plain appearance,
but I sat the meeting through in silence, lamentably poor, and so went away.
After this meeting we went to Fry Willis`',
and on fifth-day attended the meeting at Jericho to some satisfaction.
Sixth-day, first of ninth month: went to an appointed meeting at Hollow Hills, which,
on the whole was a time of favour:
in the afternoon called to see an ancient Friend who was blind,
and had a satisfactory religious opportunity in his family.
Seventh-day attended a meeting at Bethpage,
which was very exercising and trying in the forepart of it, but towards the close,
a door of utterance was opened to labour pretty largely
in a close searching manner for their help;
and many for the present,
seemed pretty much affected at the opening of their states and
setting them before them in the authority of Truth.

I left this meeting with the evidence of peace,
and in the afternoon had religious service in two families,
the latter of which was truly a soul-reviving season:
here the heavy burden and covering of sackcloth,
which my poor soul has borne much of the time we have been on this island,
seemed to be rent and measurably taken off,
and I had to witness something like the oil of joy for mourning,
and the garment of praise for the spirit of heaviness--for which my
soul bowed and worshipped Him who is the Alpha and the Omega,
the beginning and the end; worthy to be worshipped and exalted over all so be it,
world without end.

We returned to Fry Willis`' the same evening, and next day being first-day, the third,
after a comfortable season in the family,
we went to meeting at Matinicock which was large,
there being a considerable number present who were not of our Society.
Here my spirit was uncommonly baptised into feeling,
on account of a state of infidelity and disbelief in
Christ Jesus the Saviour of the world,
and my mouth was opened largely on the subject, in a manner I thought strange of,
amongst so many Friends;
but I was afterwards informed that these principles much prevailed in that neighbourhood,
and that there were a number present supposed to
have imbibed those dark principles of deism.
Oh! what will become of these wicked agents of Satan, unless they repent and turn to God!
Will he not miserably destroy these wicked husbandmen,
and let his vineyard to others that will receive his Son!
The meeting ended in solemn prayer, and the Lord`'s truth was this day exalted over all,
to the humbling and confounding of the gainsayers; glory to his great name forever.

Went after meeting to Silas Downing`'s, and several Friends coming in after dinner,
we had a heart-tendering opportunity together.
Next day we had a meeting at Oyster Bay, where are not many Friends,
but a considerable number of others came in,
to whom the gospel was freely and largely preached,
with which they seemed well satisfied: the meeting concluded with prayer,
and the people parted with great solemnity.
We returned to Silas Downing`'s, and on third-day, the fifth,
attended a meeting appointed at Cowneck, which, though not large, was very exercising.
I laboured considerably amongst them, and though it appeared to have but little effect,
yet I was favoured in the conclusion to feel relief;
we also had a comfortable opportunity in the evening where we lodged.

Fourth-day, sixth, returned to Westbury, where we met with our countrywoman Charity Cook,
on her way to Europe, and were truly rejoiced to see each other:
next day we all attended Westbury meeting, which was very laborious and exercising,
but ended to a good degree of satisfaction.
Went that evening to Flushing,
and on the following day attended the monthly meeting there,
to which Friends of New York belong.
This was a glorious meeting:
I thought I never had been a witness to such a
solemnity at any meeting for so long together;
it continued throughout both the meeting for worship and discipline,
which held about six hours.
I was largely engaged in testimony and supplication,
greatly to the relief of my poor exercised mind,
and to the comfort and rejoicing of many others.

Apprehending ourselves clear of Long Island, we parted with Charity Cook and company,
and other dear Friends, and set out for the main:
had religious opportunities in two families on our way,
and after riding about fifteen miles crossed over the Sound to New Rochelle.
Seventh-day we attended an appointed meeting at West Chester,
which was very poor and exercising in the forepart, but ended to the relief of my mind.
First-day, the tenth, were at Mamaroneck meeting, which was large, there being a burial.
I was led to treat on the nature and spirit of the gospel,
which breathes peace on earth and good will to men.
Truth reigned over all this day, and a glorious meeting it was to us,
and to many who did not profess with us, but who seemed glad of the opportunity.

Third-day, the twelfth, we attended a meeting at New Rochelle,
appointed for those not of our Society, which was pretty large:
their priest and his wife were there, and all were quiet;
the meeting ended to satisfaction,
and I returned to our lodgings with the evidence of peace.

Fourth-day we had a meeting in the courthouse at White Plains, which was also large,
and the people behaved in a solid becoming manner;
and although I suppose I sat silent near an hour and a half, yet they continued quiet,
until at length a door of utterance was opened, and it proved to be a glorious meeting:
the people were generally humbled and many were broken into tenderness and tears;
it was said there were several lawyers present,
who were also affected under Truth`'s testimony.
The meeting concluded in prayer,
after which I commended the solid attention of the
audience and took an affectionate leave of them,
many of the people wept and departed with great solemnity:
may the Lord bless and sanctify this opportunity to their lasting benefit,
and take all the praise unto himself, to whom alone it is forever due, but unto us,
self-abasement as in the dust.

Fifth-day, the fourteenth, attended the monthly meeting at Purchase, which was large,
and eminently owned by the Divine presence; the lukewarm were powerfully called unto,
and aroused, and shown the danger of their situation,
at which many of them seemed to be humbled for the present,
while the true mourners were comforted and encouraged.

Sixth-day, fifteenth.
This morning as I walked to and fro alone, I rejoiced in spirit,
and all that was alive in me returned thanks to my gracious Master,
who had enabled me to leave my all for his gospel`'s sake.
May I keep the word of his patience under every turning of his divine hand upon me,
until he fully perfect his will in me to the praise of his own name.
Amen.

Seventh-day, sixteenth.
We took our leave of Friends here in near affection,
and set out for Rhode Island through Connecticut, a very rough road.
On first-day we attended their little meeting at Middlesex to satisfaction,
and then took our journey by the way of Mill River, Stratford, New Haven, Guildford,
Killingsworth, New London, etc., and on fourth-day, the twentieth,
got to a Friend`'s house at a place called Pawtucket Bridge,
which is on the boundary between Connecticut and Rhode Island.
This is the first Friend`'s house we have seen since we left Middlesex;
the people among whom we have passed are generally civil and respectful to strangers.

Fifth-day, the twenty-first, attended a meeting at Hopkinton, which was a low time,
and I left it much dejected; indeed,
for several days I seemed to be as it were under the weight of a mountain.
Oh Lord, withdraw not thy help from me, for without it I cannot persevere,
no not even stand still, nor watch one hour; therefore, oh my God,
enable me yet to lean on thee, for on the arm of thy power I desire to trust,
in which alone there is safety and preservation.

Sixth-day attended an appointed meeting at Westerly, which was small, but on the whole,
a precious soul-animating opportunity--blessed be the name of the Lord!
We were then at South Kingston upper meetinghouse,
Richmond and South Kingston lower meetinghouse, all of which were seasons of favour:
on second-day we crossed over two wide ferries, by way of Conanicut Island, to Newport,
Rhode Island, and put up with our friend Thomas Robinson.

Third-day, the twenty-sixth, we attended the monthly meeting here, which was large,
and proved a laborious, exercising time to me,
yet I found some relief in a faithful discharge of apprehended duty,
and hope it was a profitable season to some.
I also visited the women`'s meeting, I believe to the satisfaction of Friends.
In the evening we had a time of retirement at our lodgings, with the family,
as we had had the evening before, both which opportunities passed in silence,
with which I was satisfied; "`there is a time to keep silence,
and a time to speak,`" may I be rightly directed in both.

Fourth-day we stayed mostly at our lodgings, and wrote letters to our families,
and on fifth-day, twenty-eighth, attended their week day meeting, which was large,
and the testimony of Truth flowed forth freely, especially towards the rising generation,
of which class there was a large proportion present, many of whom were much tendered,
and the meeting ended in prayer.
In the afternoon we paid social visits to some Friends to satisfaction,
and returned to our lodgings.
Sixth-day: this morning my mind is humbled and contrited before the Lord,
under a fresh sense of his continued goodness to my poor soul.
Oh Lord,
so continue and keep me in the way that will please thee--for
without thy help I see that I can do nothing aright.

On seventh-day, the thirtieth,
we had a very large public meeting in Friends`'
meetinghouse for those not professing with us,
who at their gathering sat in a solid becoming manner;
but one stood up very soon in testimony in a way that unsettled the meeting for a time;
but at length it seemed to become more settled, and I expected soon to stand up,
but that same person rose again with a repetition of many words without life,
at which the people were so disturbed that they began to leave the meeting;
and although my concern for them was great,
yet I durst not offer any thing until the coming of the heavenly Prophet,
lest I should be a means of scattering instead of gathering them.
And in the remembrance of the passage respecting Saul`'s conduct and the effect of it,
in a case analogous to this,
I was settled down in the quiet and passed the meeting in silence,
and left it rejoicing in my own preservation.

First-day, first of the tenth month,
we attended the fore and afternoon meetings in course, which were both seasons of favour,
wherein truth reigned to the humble rejoicing of many minds.
Second-day, not feeling clear in my mind,
I proposed a meeting this morning for the ministers and elders only,
which was agreed to and we met about eleven o`'clock:
this meeting being rather uncommon and a great task for me, we went to it,
trembling and in great fear, but my gracious Master who, I did believe,
laid this service upon me, mercifully helped me to labour tenderly with them in his love,
insomuch that many were broken and melted down under the influence of
the holy power that attended us in this opportunity.
After the meeting some of the Friends ventured to tell
me that there was a cause for my exercise,
and marvelled at the manner in which I was led amongst them;--it was
the Lord`'s doing and marvellous in the eyes of his children.
My soul bowed and acknowledged the kingdom and the power and the glory to be His,
to whom alone all the praise is due forevermore.
Amen.

Third-day, the third, we left Newport and were at an appointed meeting at Portsmouth,
which was a solid favoured season.
Having a Friend of Newport for our pilot, we crossed over to Tiverton that evening,
and next day had a meeting there, which was small and poor,
but ability was mercifully afforded to labour pretty largely amongst them,
to the relief of my own mind, and I hope to the profit of some.
We had a religious opportunity in the Friends`' family where, we dined,
and rode the same evening about eighteen miles to New Bedford.
On fifth-day, we attended their week-day meeting at this place,
which I hope on the whole was to some profit, though very exercising to me.
Sixth-day, was a very low and trying time.
Lord, keep and preserve me in the right way!

Seventh-day, the seventh,
about three o`'clock this morning we went on board a
sloop and set sail for the island of Nantucket,
where we landed about four the same afternoon.
We continued on this island about three weeks,
constantly attending meetings with Friends on their meeting days,
had several public meetings for those not professing with us,
and also visited many families;
and although we found it a low time with Friends generally,
so that much inward exercise and deep wading was my lot, during most of the time,
yet I was often opened and enlarged amongst them in gospel authority,
to the tendering of many hearts both in public and private opportunities.
At length that deep inward travail of spirit and covering of sackcloth,
which had been so much my clothing since we landed, seemed to be taken away;
so that on the twenty-eighth, we took leave of Friends early in the morning,
set sail for the continent and being favoured with a fine passage,
we landed safely at New Bedford the same afternoon,
and next day being the first of the week we
attended both the meetings here to satisfaction;
and on second and third-days we visited several families of Friends,
in some of which we were favoured with precious
opportunities to our comfort and rejoicing.

Fourth-day, eleventh month, first, we had a blessed meeting at Acushnet,
about four miles from New Bedford, with the few Friends there, William Rotch, senior,
and his wife, and several other Friends from this town being with us.
Fifth-day, attended the week-day meeting at New Bedford to solid satisfaction,
and on sixth-day had an appointed meeting at New Town,
and another next day at Aponyganset, both pretty large, and favoured,
the last eminently so, wherein the great name was exalted and praised;
many present were humbled and bowed under a sense thereof,
and at the conclusion of the meeting, withdrew with great solemnity.

First-day, the fifth, attended both the meetings at New Bedford again,
which were blessed opportunities,
through the arising and overspreading of divine power and love.
Second-day, sixth, had a public meeting for the town`'s people which was also a solid,
good meeting; we had likewise several favoured opportunities in families.
Third-day, the seventh, had an appointed meeting at Long Plain,
in which I was led to treat pretty largely on the Babylonish captivity,
where mention is made of the affecting situation of the people when
they sat beside the waters and wept in remembrance of Zion,
with their harps hanging on the willows,
not able to sing the Lord`'s song in a strange land.
This was a solemn time, wherein there was much weeping and brokenness in the meeting,
and some Friends seemed almost astonished at the testimony I had to bear,
and informed me afterwards that a member, and one reputed a minister,
belonging to that meeting,
had imbibed principles contrary to the well known
doctrine held by Friends from the beginning,
and had drawn away a number after him to the great confusion and dividing of the meeting,
and to the distress of Friends.

Fourth-day, the eighth, we were at a poor small meeting at Centre,
the next day at Acushnet preparative meeting,
and the day following at a meeting at Little Compton,
the last two to pretty good satisfaction.
We rode about five miles to Jeremiah Austin`'s,
and on seventh-day had a public meeting at this place to pretty good satisfaction;
after this we took our solemn leave of Friends there, and got to Tiverton that night;
and on first-day, the twelfth, rode about eight miles in the morning,
and attended a meeting at Swanzey, which I sat through in silence;
then riding about eighteen miles further, we got to Moses Brown`'s at Providence,
where we spent most of next day in writing letters, etc.
On third-day we were at their Meeting for Sufferings,
and on fourth-day at a meeting at Smithfield, about six miles from Providence,
in which I had some close searching labour,
and left it with a quiet mind and returned to Moses Brown`'s. Fifth-day, sixteenth,
attended the week-day meeting at Providence,
which was a blessed heart-tendering opportunity.
Next morning we took leave of our friends and set out for Hartford,
where we arrived just in time to get to their little meeting on first-day morning;
we also attended that held in the afternoon, both which were favoured seasons.

Second-day we rested, and on third-day appointed a meeting in the city of Hartford,
which was attended by but few of the towns-people.
Fourth-day, twenty-second, attended the midweek meeting at Hartford, which was a solid,
good time, several not professing with us being present.

Apprehending ourselves clear of this place, we proceeded towards Oblong,
and prosecuted our journey through much difficulty, occasioned by the frost and snow,
and were at no meeting until first-day,
when we attended Friends`' meeting at a place called the Branch, near Oblong,
in the state of New York, which was a pretty solid opportunity.
Rode that afternoon to Oblong, and next day had a meeting there,
which was a season of much close exercise:
it seemed to me as though most of the people there had neither ears to hear,
nor hearts to believe, or to receive the heavenly dew;
and my mind was so impressed with a state of obduration and hard-heartedness,
that at length I cried out in prayer and supplication, and then felt relief.
With a heart melted into tenderness I left them,
and rode that afternoon to Daniel Haviland`'s, where we lodged.
On third-day attended a meeting at the Valley; fourth-day at Peachpond,
and on fifth-day a preparative meeting at Bedford;
the first two were exercising and laborious, yet to some relief,
but the last was a highly favoured opportunity,
wherein our spirits seemed generally melted into
tenderness before the Lord--glory to his name forever!
After this precious meeting we rode about fifteen miles on our way towards New York,
though the weather was extremely cold, and arrived there next day, being sixth-day,
the first of twelfth month.

On first-day, the third, we attended the fore and afternoon meetings in the city,
which were crowned with the over-shadowing of Divine power,
to the humbling and melting down of the souls of many, especially among the young people,
of whom there was a large number present:
it was a day which I trust will not soon be forgotten by many of us,
especially the afternoon meeting, at the conclusion of which,
prayer and praises ascended unto Him, whose is the kingdom, the power and glory, forever,
amen.

After this last mentioned meeting, I felt much spent and almost faint,
and having previously taken some cold which was now renewed, I was considerably unwell,
but blessed be the Lord, I had sweet peace of mind.
I continued poorly until fourth-day, the sixth,
when I attended the monthly meeting in the city, in which I was silent and felt relieved:
on fifth-day we left New York and got to Rahway that evening,
and on seventh-day reached Burlington, and lodged at John Hoskins`'.

First-day, tenth.
We attended the meeting of Friends here, in which I was also silent, and next day,
notwithstanding I was very low in my mind,
and had been so most of the time since we left New York,
I concluded to proceed to Philadelphia,
but when we got to the Delaware river opposite the city, there was so much ice in it,
that we could not get our horses over, so we were under the necessity of leaving them,
and with much difficulty worked our way through the ice,
and got into the city about three o`'clock in the afternoon,
where we were again kindly received by our friends.

Third-day, twelfth.
Attended the week-day meeting at the North meetinghouse, which was large,
and I felt very poor and stripped at sitting down,
and sat a considerable time in much weakness and fear,
especially as I was amongst so many worthy fathers and mothers as were then present;
but the Lord, who can raise the poor as from the dunghill,
and set them among the princes, was pleased to raise up my poor soul this day,
and enlarge my heart in the love of the gospel, to my humble admiration,
and to the satisfaction of Friends.
Dear Samuel Emlen said, he had been made to rejoice in the Lord, that day,
for the offers of his salvation: it was indeed the Lord`'s doing,
who is our strength in weakness, our riches in poverty,
and our present help in the needful time -- blessed be his holy name forever.

Fourth-day, we attended Pine street meeting, which was a solid, good time: fifth-day,
we were at Market street meeting, which was pretty large,
and here I was again raised up in the authority of Truth,
to stand as a monument of adorable mercy, to the humble rejoicing of many.
In the afternoon, being accompanied by Samuel Emlen, James Pemberton, and some others,
we went to the prison to visit a criminal who was under sentence of death for murder,
and the time appointed for execution was near at hand.
The opportunity was truly humbling to my mind:
I was opened on the awful subject of the two malefactors who
were crucified by the side of our Saviour,
and of their dispositions as appeared from their speeches on the cross,
and this poor man was earnestly recommended to the example of the last.

Next day we attended the meeting for Sufferings;
and the day following a committee of Congress,
with some Friends appointed by the yearly meeting,
to present a memorial respecting the abolition of slavery;
in the evening we had a religious opportunity
with some young people at a Friend`'s house.

First-day, seventeenth.
In the morning we attended the Market street meeting, which was a time of favour,
and in the afternoon a meeting with the prisoners in the state prison,
there being at that time about two hundred of them; they sat very orderly and attentive,
and that same poor man whom we had previously visited was also brought into the meeting,
he having obtained from the governor a respite for one week:
it was a time to be remembered with thankfulness; the prisoners seemed generally humbled,
and several of them broken into tears; the meeting concluded in prayer,
and the solemnity which prevailed was to my humbling admiration.
In the evening we were at the large meeting at Market street,
which on the evening of this day is attended by Friends from the other districts,
and also by a number not professing with us: it was a very large, crowded meeting,
and proved to be a time of favour, divine good being near us,
and It concluded with great solemnity.

Second-day, eighteenth.
Attended the second-day morning meeting of ministers and elders,
and in the evening went to a meeting of young women who had formed
themselves into a society for the benevolent purpose of relieving the poor,
sick and aged of their own sex in this city.
After they had gone through with the business of the evening, a solemn pause took place,
and this little meeting was eminently owned with the overshadowing of Divine good,
greatly to the comfort and encouragement of the young
people in their present arduous undertaking:
the opportunity concluded with solemn prayer and supplication,
and we went on our way rejoicing.

Third-day, attended the preparative meeting at the North meetinghouse,
and on fourth-day that at Pine street, in both which I was silent,
while others were engaged in public labour.
Fifth-day was at meeting at Market street to satisfaction,
and in the evening visited a black school:
sixth and seventh-days were spent mostly in social visits to satisfaction.
First-day the twenty-fourth, attended three meetings in this city,
in all of which I was silent,
as also next day in the morning meeting of ministers and elders,
and my desire is that I may be preserved in a holy watchfulness and resignation,
either to do or to suffer, according to the will and direction of my gracious Master,
so that he will but be pleased to show me what to do, and what to leave undone.

Third-day, twenty-sixth.
Attended the monthly meeting for the Northern District, which was large,
a number of solid Friends from different parts of the country being there,
it was a blessed time to me and many more.
I was again raised from a very low estate and set as among the princes of the people,
it was of the Lord and not of man, therefore I rejoice with trembling;
the meeting concluded in solemn supplication in a powerful manner by Jacob Lindley,
and broke with great solemnity,
and the harmony was like the pouring forth of precious oil.

Fourth-day, twenty-seventh.
Attended the monthly meeting at Pine street, which was not so large,
and more laborious than the preceding one.
I was engaged to go and sit awhile in the women`'s apartment,
where I was pretty largely opened in testimony to my great satisfaction.
Fifth-day, the twenty-eighth, attended the preparative meeting at Market street,
which was a solid time; and on sixth-day the monthly meeting of Philadelphia,
held at the Fourth street meetinghouse, which was also a favoured season.

Seventh-day, the thirtieth, being unwell I stayed mostly at our lodgings,
and on first-day we attended the North meeting in the morning.
Pine street in the afternoon, and a large meeting in the evening at Market street,
in all of which I was pretty largely opened in testimony, especially the last:
dear Peter Yarnall concluded this meeting in supplication,
and the end was crowned with great solemnity.

Second-day, first of first month, 1798,
we attended the morning meeting of ministers and elders,
where I was opened on the subject of gospel ministry; it was a heart tendering season,
and tended greatly to the relief of my mind.
This was the last meeting we were at in the city,
and we returned to our lodgings with thankful hearts, blessed be the Lord therefor.

On third-day morning, several Friends came to see us,
and we had a precious parting opportunity,
and then took our solemn leave in near affection, and went to Concord that day:
next day attended the monthly meeting there, and rode to Wilmington the same evening,
and on fifth-day attended the preparative meeting there.
I felt very poor, low and almost dejected, and so went to this meeting,
but blessed be the name of the Lord, through the renewing of his goodness,
it was a season of comfort and rejoicing.
The following day we went towards Baltimore,
though there was so much snow and ice that we found
considerable difficulty in crossing the Susquehanna;
but we got safely over on the ice, where it was more than a mile wide.

First-day, the seventh, we attended a small meeting at Bush to good satisfaction,
and on second-day reached Baltimore.
In our way we met with some Indian chiefs who seemed glad to see us,
there being a particularly good understanding between Friends and the natives:
we understood they were going to Congress with some complaint of grievance.
There was something in their countenances which appeared serious,
but their interpreter being at this time behind, I could not speak to them,
though they all stopped and held out their hands to me in token of friendship.
Truly under the awful clothing of my spirit at that time, I was ready to cry out,
O America, America;
how wilt thou atone for the injuries thou hast done to
this people and to those of the nations of Africa?
Hath not the universal Father of mankind testified, "`with what measure ye mete,
it shall be measured to you again.`"
O thou land of my nativity, how wilt thou be able to stand,
when He who hears from heaven the cries and grievances
of the unjustly afflicted and oppressed,
shall arise to plead their cause.
Oh, for thee I tremble, when I see clouds,
thick clouds arising over thee and gathering blackness.

Third and fourth-days, I went not much out from my lodgings, being poorly,
and also low in my mind, though I was not quite idle,
but was employed part of the time in writing letters, etc.
Fifth-day, eleventh, attended the monthly meeting here without much relief,
and not seeing my way out of the city, nor yet to appoint many public meeting:
on first-day we attended the two meetings of Friends,
in both of which I was pretty largely opened in testimony in a close searching manner,
especially in the afternoon, when dear Mary Mifflin being present,
concluded the meeting with solemn prayer.
After this I seemed to feel in a good degree relieved with respect to my own mind,
and concluded we might leave Baltimore; accordingly on second-day, the fifteenth,
we took our leave of Friends, and went on our way as far as Ellicott`'s mills,
and the weather being very rainy and the waters high,
we did not get away until fourth-day,
when we attended their weekday meeting at Elkridge to solid satisfaction.

Fifth-day, we attended the preparative meeting at Indian Spring,
and next day a monthly meeting at the same place,
to which the Friends of Elkridge and Sandy Spring belong:
these were both favoured opportunities,
many not professing with us attending in the morning of each day, that is to say,
during the part of each meeting spent in worship;
to these the gospel was freely preached and they withdrew in a solid manner.

On seventh-day, the nineteenth, we got to Alexandria,
and the day following attended two meetings there, both laborious and exercising to me,
yet I hope profitable to some.
I left them rather low in my mind, and next day got to Occoquan,
and had a public meeting there the day after,
which was also laborious and not to much relief, the people`'s hearts seeming to be hard.
Fourth-day and fifth-day, we got to Caroline,
and our friend David Brooks of North Carolina, having arrived there just before us,
in the course of a religious visit,
had appointed a meeting to be held at Caroline meetinghouse next day, which we attended;
it was nearly silent.
We went that evening to Pleasant Terrill`'s,
and it came on so very rainy and snowy that we stayed there all night and next day,
and on first-day set off for Cedar Creek,
but the snow and water so abounded on the earth
that we did not reach it in time for meeting;
so we stopped at a Friend`'s house, and on the morrow went to Genito,
where we had an appointed meeting the day following, to satisfaction.

Fourth-day, the thirty-first,
we got to Richmond and had an appointed meeting there also satisfactorily;
then went to Curies and tarried with Robert Pleasants.
Sixth-day, second of second month, attended the preparative meeting at White Oak Swamp,
and on seventh and first-days,
were at the monthly and general meetings at the same place,
and also a meeting of ministers and elders, in the afternoon of first-day;
all of which were seasons of favour,
though the testimony went forth in a close searching manner,
especially in the general meeting; may it have the desired effect,
but this we must leave to the Lord.

Our next meetings were at Curies, Petersburgh, Gravelly Run,
and so to the quarterly meeting at Black Water, most of which were exercising,
laborious seasons.
Here my companion and I parted, after being together about eleven months;
he returning home by way of Western Branch,
I went to my brother Benjamin`'s in Southampton, stayed with him a day or two,
and attended their week-day meeting to satisfaction.

On fifth-day, the fifteenth, I reached home,
and found my dear wife and little family well, and things as to the outward,
better than I expected, considering my long absence,
for which I was thankful in heart to Him who hath graciously promised,
that neither grace nor glory, nor any good thing,
shall be withheld from those who faithfully serve him.
May I henceforth be enabled to serve Him more fully and unreservedly, yea,
worship and adore Him with all my heart, even to the end,
that so no other beloved may have the preference in my heart,
which ought to be his temple.
Amen.

In this journey I was from home about eleven months,
and travelled upwards of three thousand miles.
Sixth-day, sixteenth, being the next day after my arrival at home,
fell the greatest snow that I remember to have seen in North Carolina.

Third-day, twentieth of third month.
Mostly disagreeable weather since my return home,
and the state of my mind much resembling it, so that I have scarcely seen one fair day,
neither have I opened my mouth in one of our meetings since my return,
but my spirit has been almost continually covered with inward exercise and mourning,
for what cause I have not been favoured fully to see; therefore, oh, my God,
be thou pleased to draw near to my poor soul in this time of trial, and sustain me,
that so I may not cast away my confidence in thee;
for I desire yet to trust in the secret arm of thy
power for preservation and support from day to day.

First-day, eighth of fourth month.
This day I was opened in testimony for the first
time in our meeting since my return home;
but "`although I speak my grief is not assuaged;`" for
though my opening was with a good degree of clearness,
yet my sorrows have returned upon me.
Lord, increase my faith, and also my patience,
that I faint not under these proving conflicts,
that so I may be enabled to hold out to the end!

Sixteenth, seventeenth, and eighteenth, cold, blasting winds, and consuming frosts,
cut off the fruits, and caused much of the tender vegetation to wither; thus,
it is evident that the Father of mercies is repeatedly informing our senses,
and our understandings, that we are entirely dependent on his goodness and mercy,
for every temporal as well as spiritual blessing.

Nineteenth and twentieth of fifth month;
had a pretty open time in testimony both at our monthly and general meetings,
which had been the case a few times previous:
I also attended our quarterly meeting in this month, which was through divine favour,
a solid, good meeting; and was at a burial the next day after the quarterly meeting,
several miles on my way home, which was a solid time,
and I returned home with a good degree of peace and satisfaction of mind.

First of eighth month.
I have continued mostly about home since our quarterly meeting, and now Gervas Johnson,
a Friend from Ireland, being here on a religious visit,
I concluded to accompany him to a few meetings, which I did,
both in the lower part of this state, and a few within the borders of Virginia,
which on the whole was to pretty good satisfaction.
I returned home with a fever on me, which I had not been clear of for several days;
it increased to a severe attack of the bilious kind, which proved tedious,
and confined me at home until about the time of our yearly meeting in the tenth month,
which I attended, though very weakly; yet I was glad I was there,
for although some of the first sittings were truly suffering seasons, on the whole,
it was a solid, good yearly meeting, for which my soul bowed and worshipped before Him,
who has thus graciously continued his care and lovingkindness to us poor creatures,
who are unworthy of such dignified favours.
May it prove a powerful incitement to us to love him more,
and to walk worthy of the vocation whereunto he hath been pleased to call us.

Soon after this yearly meeting, I attended our state legislature,
in company with some other Friends appointed by the yearly meeting,
to present a remonstrance and petition on behalf of the oppressed Africans;
after which I continued about home, almost continually covered with gloom, temptations,
inward exercise and tribulation, until I almost loathed myself and all around me,
and this both in meetings and out of meetings, so that my faith has well nigh failed me.
Oh Lord, reach forth thine hand and preserve me,
while I am endeavouring to come unto thee on this sea of trouble,
that my poor soul sink not in the depths thereof,
that I may yet live to praise thee for the multitude of thy mercies!
Amen.
