== Chapter 3

+++[+++Having passed through many humbling baptisms,
in which he endured great stripping and poverty of spirit,
preparatory to further religious service, and having patiently waited the command of Him,
in whose hand are the times and seasons; in the 3rd month, 1799,
he imparted to his friends a prospect of duty which had long attended his mind,
to make a visit in the love of Christ, to Great Britain, Ireland,
and some parts of the continent of Europe.
In opening this concern to the several meetings whose concurrence was necessary,
Divine goodness attended, contriting the spirits of many present,
and cementing them in the precious feeling of Gospel fellowship.
He obtained certificates from his monthly and quarterly meetings,
and from the yearly meeting of ministers and elders,
expressive of their approbation of his proposed engagement,
and of unity and sympathy with him therein.

In making the necessary arrangements for entering on this extensive field of labour,
the completion of which would necessarily require much time,
and involve considerable risk of life, from the perils of a sea voyage,
and the exposure to change of climate in foreign lands;
one of his principal concerns was to arrange his outward affairs.
Being anxious that in the event of his death abroad,
the situation of his estate might not give trouble to his friends,
or bring any blemish upon the cause which he had espoused;
and fully believing that if he was not faithful in the unrighteous mammon,
he could not expect to be entrusted with the true riches,
he discharged what debts he owed, and settled up all his temporal concerns.
By his industry and frugality he had acquired a good farm, on which he was settled;
and while he encouraged his wife to live during his absence,
as comfortably as its proceeds would admit of, he enjoined upon her,
not to contract any debts; that if he should not live to return home,
no one might suffer any loss on his account,
nor the least shade be cast upon the religious profession they were making.^
footnote:[From [.book-title]#A Biographical Memoir of Richard Jordan#]

[.offset]
His journal continues:]

Third month, sixteenth, 1799, At our monthly meeting, I have now,
after passing through many deep baptisms, and sore conflicts of mind,
resigned myself up to the prospect of visiting some parts of Europe,
and this day laid my concern before the meeting.
Several solid Friends from other monthly meetings happened to be present,
which I esteemed a favour: it was a memorable baptising season with Friends,
many in the meeting being melted into tenderness and tears.
After this I felt my mind brought into a remarkable calmness and serenity,
even beyond expression, and my burden much lightened.

In the fifth month, I attended the quarterly meeting at Western Branch in Virginia,
as also their yearly meeting held this year on the north side of James`' River,
and returned home with peace of mind;
praises and thanksgiving to Him who thus leadeth
about and instructeth in the way of peace,
I stayed mostly about home until the eighth month,
when I attended the monthly meeting of Jack Swamp,
and being under an appointment in our yearly meeting with some other Friends,
to visit our select members in their families,
I attended to that appointment with another Friend or two,
in the counties of Northampton, Chowan and Perquimmons,
also attended our quarterly meeting at Wells`';
and having obtained a certificate from our monthly meeting,
expressive of their unity and concurrence with me, in my concern to visit Europe,
I laid the same before the quarterly meeting,
and obtained their endorsement to the same purport,
with much unanimity and near sympathy, insomuch that it was an heart-tendering season,
and tended much to my encouragement.

In the latter end of the tenth month, I attended our yearly meeting,
held this year at New Garden,
where I also revived my concern to visit Europe in the meeting of ministers and elders,
and laid my certificates from the monthly and quarterly meetings before them,
which obtained the attention and sympathy of the meeting in an affecting manner,
so that after a time of solid deliberation,
I was set at liberty with much brokenness and tears of near fellow feeling,
for which my soul was bowed, and we worshipped together.
Having obtained a certificate from this meeting,
and attended the several sittings of the yearly meeting to satisfaction, I returned home,
where I stayed pretty much, except the attendance of our own meetings,
until the eleventh month, when I was at our quarterly meeting at Piney Woods,
and in the twelfth month attended the monthly meeting of Jack Swamp.

First month, twenty-sixth, 1800.
Having felt an engagement to visit some people not professing with us,
in the upper part of this county and at Halifax,
especially among the higher classes and those in authority,
and having liberty of our meeting so to do, accompanied by a member thereof,
we visited General Allen Jones, in the upper part of this county,
and had a public meeting near his house, which was large; the people behaved soberly,
and seemed glad of the opportunity;
the General and his wife were very kind and attentive to us, and his son-in-law,
William R. Davie, being one of the ambassadors sent over at this time by our government,
in order to negotiate a treaty with France,
and the General knowing of my intention of going to Europe,
gave me letters to the ambassador, in case I should stand in need of his assistance,
it being a time of war between England and France. I accepted his kindness,
which I believe was providential,
for a treaty was happily negotiated between France and the United States,
and these letters proved of singular service to me afterwards.

We also went to Halifax, and lodged with one of the judges of the Supreme Court,
who had married one of the General`'s daughters,
and we found great openness and kind attention with them:
we had a public meeting in the town, to which came a number of people of note,
and among them the judge and his wife; many seemed to be humbled,
and a number broken into tears.
After this highly favoured meeting, we dined with the judge,
after which we parted with them, and I returned home with the answer of solid peace.

Soon after this, John Hall from England, who, with his companion,
was on a religious visit southward, came to our house, and tarried to rest a few days,
and be at our monthly meeting: this was time very agreeably,
and I trust not unprofitably spent;
it indeed proved very strengthening and encouraging to my dear wife,
who was so soon to part with me for so long a journey.

Having been favoured, as I apprehended, to see the right time for my setting out,
it was fixed to be on the twentieth of second month,
and the solemn time arrived only about two days after we parted with these dear friends:
it was a memorable day; a number of my friends and neighbours came to see me,
and take their leave, and after a religious opportunity together,
I took my solemn leave of them, and set out on my journey,
being accompanied by my dear wife, and several of our friends,
as far as the Western Branch, in Virginia, which is about sixty miles.
Here we attended their monthly meeting on the twenty-second, which was a time of favour,
though the testimony went forth in a close, searching manner;
we also attended their meeting on first-day;
and then I went to visit some of my relations, and stayed to their meeting on fourth-day,
my dear wife being still with me, and also some other Friends,
who came with us from home on a visit to their relations in these parts.

The weather being very rainy and snowy, we continued about the Branch until seventh-day,
first of third month, when we went to Robert Jordan`'s at Suffolk,
and the same evening to Summerton; attended their meeting next day, and on third-day,
the fourth, after a solid opportunity with a number of Friends who came to see us,
I took a solemn and affectionate leave of my dear wife,
and of other Friends who were present, and got on to Black Water that evening,
where we attended their week-day meeting next day; and the day following,
not feeling easy without appointing a meeting at the same place, we attended it,
and then feeling clear we went on to Burleigh.
Crossed James`' River, and were at Curies meeting next day, and on second-day, tenth,
got to Richmond, and visited a few families there; then took meetings at Cedar Creek,
South Land, Goose Creek, and so on to the quarterly meeting at Fairfax,
where we met our friend Daniel Haviland, from New York state,
who had been on a religious visit to the southward.
This was a very laborious, exercising meeting to me,
but I was favoured to leave it in a good degree relieved, and I hope clear of the place.
Our next meetings were Bush Creek, Pipe Creek, Monallen, Huntingdon, Warrington,
Newberry, and so to Yorktown in Pennsylvania,
where we attended two meetings on first-day;
stayed their preparative meeting on fourth-day, and rode about ten miles that evening.
Crossed the Susquehanna at Wright`'s ferry, and had a little meeting in Columbia;
from thence we took meetings at Lancaster, Lampeter, Sadsbury, East Cain,
a monthly meeting at Uwchlan, and another at Goshen, and on first-day,
the thirteenth of fourth month, we attended a meeting at Springfield,
and reached Philadelphia the same evening.

Although I have generally made but short notes in this journey hitherto,
yet I may now remark,
that notwithstanding some highly favoured seasons have
been witnessed in the course thereof,
many others have been attended with much exercise,
deep suffering and inward travail of spirit, and sometimes almost discouragement,
so that I have been ready to compare myself to Noah`'s
dove that found no rest to the sole of her foot.

Second-day, fourteenth: attended the morning meeting of ministers and elders,
which was rather a low time; third-day,
was at the weekday meeting at the North meetinghouse which was a highly favoured season:
I also attended several other meetings this week, in which I was silent,
except at a youths`' meeting on sixth-day evening.

The Yearly Meeting of ministers and elders for Pennsylvania, New Jersey, etc.,
began on seventh-day, which I thought was the largest of the kind I ever attended,
but it was rather a low time, may it tend to deepen us,
and may the Lord draw near to us in all the further sittings
of this annual assembly to the comfort of our souls,
and to the exaltation of his great name.
The public meetings for worship on first-day at Market street and North meetinghouses,
were very large; the meeting for discipline began on second-day, the twenty-first,
and continued by adjournments until sixth-day evening:
it was very large and many weighty and interesting subjects were deliberated on,
and although some of the sittings were not so lively as could have been desired,
yet it was on the whole a time of favour, and concluded with great solemnity.
I was glad that I was there, as it was a time of deep instruction to me,
though I did not open my mouth in any of the sittings, until the last day,
and then but a very few sentences.
I was considerably opened in one or two of the
sittings of the meeting of ministers and elders,
I believe to the general satisfaction of Friends, and much to the relief of my own mind.
First-day, the twenty-seventh, attended a meeting at Darby, seven miles from the city,
after which I returned to the city, and being much fatigued and somewhat unwell,
I concluded to rest a few days in order to recruit;
accordingly went into the country with Nicholas Wain, to take a little fresh air;
afterwards returned to the city and attended meetings in course.

Sixth-day, eighth of fifth month.
Having been pretty constantly employed in attending meetings as they came in course,
and the Quarterly meeting in the city being also now over,
and no way opening for me to take my passage from this port,
I went with Samuel Smith to Bucks county about twenty-two miles:
we visited several families of Friends in that county to satisfaction,
attended a meeting at Byberry on first-day morning,
and returned to the city the same evening.
Seventh-day, seventeenth: went in company with several Friends,
to pay a visit to the President of the United States,
and had a religious opportunity with him and his wife, which was a time of favour,
and they expressed their satisfaction therewith, and thanked us for the visit.

First-day, the eighteenth: attended Market street meeting in the morning,
and in the afternoon had a meeting in the state-prison with the convicts;
three of them were under sentence of death for treason and insurrection,
who were also brought into the meeting;
the testimony and doctrines of Truth went forth freely amongst them,
and a number were reached and some affected under the power thereof:
the three poor criminals aforementioned appeared very sober and attentive;
the meeting concluded much to our satisfaction.

Second-day, attended the morning meeting of ministers and elders,
which was a blessed opportunity, and the same afternoon I took my leave of friends here,
and set out for New York, being accompanied by my valued friend John Parrish,
who was going on to attend the Yearly meeting there.
We went pretty directly on, taking only the monthly meeting at Rahway in our way,
and got to New York on sixth-day, the twenty-third:
Samuel Smith of Philadelphia having obtained certificates in order to
visit Ireland and some other parts on the other side of the Atlantic,
we concluded to take our passage from this port, if way opened for it;
and in order thereto, some Friends here had been applied to,
to endeavour to find a suitable ship for our purpose,
which they had done and agreed for conditionally;
with which we were well satisfied and confirmed it, after we had been on board;
though she was to sail so soon that we were doubtful whether it would
afford us an opportunity of attending the yearly-meeting.

On seventh-day, the twenty-fourth, the meeting of ministers and elders began,
and on second-day, the meeting for business,
which continued by adjournments until second-day, the second of sixth month,
which on the whole, I think was the most solid yearly meeting I ever attended,
which was cause of humble thankfulness to many.
We were favoured to attend these precious opportunities,
until the last day of the yearly meeting;
just as it was sitting down we were ordered on board.
We directly went into both apartments, men`'s and women`'s,
and took our leave of our dear friends publicly, which was a very affecting moment,
a number withdrew and came after us, in order to see us embark;
it was the ship Warren of New Bedford, of about three hundred tons burden,
Jonathan Parker, master.
When we got to the wharf she was under way and had to pursue her several miles by boat,
but at length we got safely on board and bid adieu to our dear friends;
but the wind soon shifting to the eastward, and the tide also making against us,
we came to anchor near Sandy Hook within sight of New York, where we laid that night.
In the evening, just as we were preparing to go to bed,
two young Friends came from the city,
and brought the agreeable news of the yearly meeting`'s
making a peaceful conclusion that afternoon,
which we were glad to hear, our minds being much with them;
and this gave us another opportunity of letting our friends know how we were,
and of sending some of them fresh tokens of regard.

Third-day, third, early in the morning they weighed anchor and put the ship under way;
we have a fine breeze, the ship sails well,
and we are fast bidding adieu to our American shores,
I feel thankful in heart for the continuation of a quiet, peaceful mind.
We have the company of our friend Gervas Johnson, and three other cabin passengers;
held meetings in the cabin every first-day to satisfaction, and on the whole,
had a fine passage of thirty days, when we landed safely in Liverpool,
glad and thankful in heart for our preservation and the
privilege of setting our feet once more on firm ground.
We were met at the dock by our kind friend Robert Benson, who took us to his house,
where we were affectionately entertained by him and his dear wife,
who is a sweet spirited woman.

And now I can hardly help remarking a little on
my feelings in first landing in this country,
so much boasted of for freedom, insomuch that if a man of any nation, or colour whatever,
land on its shores, he breathes free air;
but alas! the number of ships we had met going hence to Africa for slaves,
and others of the same description which we now saw laying here,
employed in that abominable and inhuman traffic, was so great,
that when my foot first trod on English ground,
the thick darkness and distress that covered my mind were beyond description.
I was afterwards told that the English have
about two hundred ships employed in that trade,
chiefly from this port;
from this trade many draw their great riches and live in pride and luxury,
making their boast of living in a free country,
while thousands of their fellow creatures are groaning
under the iron hand of oppression through their means,
and all this, it seems, is sanctioned by this free government,
and even in its own territories abroad.
Alas! will God`'s justice sleep forever?
Surely nay, but the measure of their iniquity must be filled,
and then his judgments will be poured out upon them,
and on all the nations that have long wrought abominations before him!

The next day after we landed being fifth-day, the third of seventh month,
we attended Friends`' week-day meeting in this town, which was a blessed time,
wherein the wrestling seed of Jacob was raised into dominion,
and my soul was enlarged in his love and power, both in testimony and supplication,
and many souls with mine,
bowed and worshipped him who is Lord over all blessed forevermore.

Sixth-day, Samuel Smith and myself being both unwell, stayed at our lodgings;
seventh-day being a little recruited, we visited some of our friends,
and on first-day in the morning, I was so unwell that I did not go to the meeting;
in the afternoon feeling better, I attended,
and although Truth did not arise so much into dominion as when I was first there,
yet on the whole it was a time of favour, and I believed of renewed visitation to some.

Second-day, seventh, we set out on our journey towards Scotland,
going by the way of Ormskirk and Preston, and so to Lancaster,
about fifty-four miles from Liverpool.
Third-day, we attended a monthly meeting in the afternoon at this place,
and their select quarterly meeting for Lancashire the same evening,
both favoured opportunities.
Next day we attended the quarterly meeting for business at the same place,
which was a day not soon to he forgotten;
here were several Friends`' from London and other parts,
and we were sweetly comforted together in the Lord and one in another,
and many souls bowed and worshipped him, who is worthy forever and ever.
Fifth-day, tenth, we attended their week-day meeting here,
which was also a crowned meeting, a number of Friends from a distance being present.
Having landed in this country in a very low tried situation,
I have great cause of humble thankfulness and gratitude to my gracious Lord and Master,
who hath not forsaken or left me in this strange land,
but has been pleased to draw near in mercy and magnify his own cause,
which he sent me over the mighty deep to espouse,
giving me a place also in the minds of sympathising Friends;
blessed be his holy name forever.

We had a comfortable meeting at Yelland with Friends and a few others on sixth-day,
and got to Kendal the same afternoon,
where we stayed until first-day and attended two meetings of Friends,
which were on the whole opportunities of favour, especially that in the morning;
but not feeling quite clear to leave this place yet,
we visited a few families of Friends and stayed their meeting on third-day,
which was to our satisfaction.
Our next meetings were Terril, Penrith, where we had also a public meeting, Moreland,
Carlisle, Cornwood, a monthly meeting and a public meeting at Alstone, Allendale, Darwin,
and so to New Castle upon Tyne:
some of these last mentioned meetings were dull and laborious,
wherein Truth did not arise into much dominion,
but others were open and much to our satisfaction.

These northern parts of England are very bare of wood,
the country very broken and romantic, and in some places barren,
but well cultivated where it is fit for tillage.
I was not a little surprised to see so much land in England lying untitled;
for notwithstanding the vast population of this little island,
it is said that nearly one-fourth part of the lands in the kingdom are uncultivated,
yet in times of peace they have plenty and to spare.

On entering New Castle my mind was covered with
rather uncommon oppression and discouragement:
we had the company of Mary Stacey of London,
who was a daughter of that eminent minister of the gospel Rachel Wilson,
and her companion Sarah Lynes from Ireland,
who had been mostly with us since we left Lancaster.
Twenty-seventh, attended the fore and afternoon meetings of Friends here.
I laboured a little in the morning, but the cloud soon returned upon me,
and so I remained both in public and private, with very little intervening light;
so that I kept myself as much retired from company as I well could; Lord,
look down in mercy upon me.
Meeting with our dear friend John Wigham at this place,
on his way home from the yearly meeting, he concluded to pilot us to Edinburgh.

Third-day, twenty-ninth, set off for Edinburgh by the way of Morpeth, Weldon,
Whittingham, Wolverhaughhead, Cornhill, Greenlow, Blackshield, and so to Edinburgh,
about one hundred and six miles from New Castle.
We arrived at this place on sixth-day, the first of eighth month, and on seventh-day,
rested and wrote.
The country from New Castle is more level than we had travelled through before,
better timbered, and to us appeared better as to its quality, except that near Edinburgh,
where there are a great many coal-pits, and the country has a more dreary appearance.
However,
my business is not to remark much on the soil and
produce of the countries through which I pass,
but more particularly on the religious, civil, and moral character of the people.

First-day, third, we attended two meetings of Friends here,
in both of which we were enlarged in the love of the gospel, greatly to our own comfort,
and to the comfort and satisfaction of Friends.
On third-day, we took post-chaise and went to Glasgow, and attended a meeting there:
although there are not many under our name in this place at present,
yet the principles of Friends seem to be gaining ground,
and we understand that a number frequently come and sit down with Friends,
in their silent meetings; indeed,
my heart felt enlarged towards the people as we walked the streets.

We returned to Edinburgh and attended their two meetings on first-day again,
which were solid, good meetings, especially the last.
Second-day, we went on to the north by way of Kimross,
and on third-day had a meeting in a pretty large town called Perth,
where are only two members of our Society at present residing,
but a number of sober people attended, and it was a heart-tendering time;
blessed be the Lord who was with us,
and gave us to rejoice in the renewed offers of his salvation.
There was one called a clergyman at the meeting, who behaved in a solid manner,
and at the conclusion came and took his leave of us, wishing us well,
and praying that every blessing might attend us.

Fourth-day, thirteenth, went to Dundee, and had a meeting there in the afternoon,
and on fifth-day proceeded by the way of Arbrotb, Montross, Bervy, and so to Stone Haven,
where we lodged.
Just by this last place is Ury, the seat of Robert Barclay, the apologist;
the present proprietor, the great-grand-son of the apologist, now resides there,
but makes no profession with Friends.
Seventh-day, sixteenth, we rode to Aberdeen,
and on first-day attended two meetings there,
at both of which we had a number of the town`'s people with us,
amongst whom were some soldiers, who behaved well,
and seemed to be humbled under Truth`'s testimony,
one of them especially was broken into tears; these were both pretty solid,
good meetings.

Next day we rode to a place called Balhalgardy, and on fourth-day got to Old Meldrum,
and attended the week-day meeting of Friends there,
and feeling our minds drawn towards the town`'s people,
we appointed a meeting for them in the evening, to which many of them came,
and behaved in an orderly manner, while many gospel truths were freely declared to them,
and I hope some were profited thereby.

Fifth-day, twenty-first.
We attended a monthly meeting at Kinmuck, which was a highly favoured season;
dear Elizabeth Wigham, wife of John, obtained a certificate to visit Ireland:
thus the messengers are running to and fro, may true knowledge be increased.
My companion, Samuel Smith, having a desire to return to Old Meldrum on first-day,
I accompanied him, and we attended two meetings there again, to which,
especially the last, came many of the town`'s people,
to whom my companion had considerable communication, but I was silent in both meetings.
Second-day, twenty fifth, in the morning had a meeting at Kinmuck,
where I was still shut up;
in the afternoon was held the select half year`'s meeting at the same place,
which through the renewed extendings of holy help,
was a season of comfort and refreshment to my poor soul; blessed be the Lord.
Next day was held the half year`'s meeting for business, which, on the whole,
was a time of refreshment and comfort to many minds.
We went in the afternoon to visit a sick Friend,
had a precious opportunity in the family, and returned to Kinmuck.

Fourth-day, twenty-seventh, we set our faces towards Edinburgh again,
and got as far as Stone Haven to lodge,
and next morning went to see Robert Barclay at Ury: he had three sisters with him,
one of whom had lately married;
her husband and a young clergyman who had been tutor to some of the children,
were also present.
They received us very kindly, we breakfasted with them,
and after walking awhile in the garden,
which is beautifully situated on a lively running stream of water,
and cultivated in great perfection, we returned to the house,
which is said to be the same that the apologist lived in.
It is a large stone building,
in which still remains the study in which the Apology was written,
which is now a library.

After we had viewed various parts of that ancient good man`'s relics,
we proposed a religious opportunity with these young people,
who had neither father nor mother living, which they acceded to;
it was much to the relief of my mind, and I hope will be remembered to profit, by most,
if not all of them.
Robert and his brother-in-law walked with us near a mile,
and seemed loath to part with us, taking their leave in a very affectionate manner.
Oh, may the lives and testimonies of those eminent instruments and faithful servants of God,
in their day, like "`the blood of righteous Abel, though dead,
yet continue so to speak to after generations, and to their own posterity in particular,
that they may be stirred up to follow them as they followed Christ.

Being thus clear, we passed on to Montross,
where we had a religious opportunity with an ancient woman Friend and her daughter,
who are the only persons under our name residing there.
Next day we got to Dundee, and lodged at a Friend`'s house; he was not at home,
and his wife not being a member of our Society,
was very averse to her husband`'s joining Friends,
yet she would not let us stay at an inn, but came and had us away to their house, saying,
that though she was not one with us in outward profession,
she loved them that loved the truth, and believed us to be such.
She seemed getting more reconciled to her husband`'s change;
we thought her an honest-hearted woman, willing to be instructed,
so recommending her to the Lord, we departed.

On seventh-day, the thirtieth, we got to Perth,
and next day attended Friends`' little meeting in the morning,
and in the afternoon had a public meeting in a large building called Guildhall,
but there came such an abundance of people, that the hall could not hold them by perhaps,
many hundreds, so that they were crowded in the street,
and in the court round about the hall.

All seemed so unsettled and confused, that my mind was very much tried,
but being exercised for their everlasting good, I pretty soon stood up;
they became still and solid,
and a door was opened to preach the gospel pretty largely to this great concourse,
I believe to general satisfaction: the meeting concluded with fervent prayer,
and the people withdrew with great solemnity.
I believe it was a memorable time to some of them;
may the Lord help them--and I hope he will--but it must be in his own time,
and not in theirs.

I may now remark, that in passing along through Scotland,
it has not felt so dark and distressing to my mind, as in many other places;
it has seemed to me that there are many precious souls,
who are secretly enquiring the way to the Zion of rest;
but oh for those pastors and teachers, who keep them as it were in the outward court,
and instruct them to look for this rest in something without them,
even in their ceremonies and ordinances.
But how can it be otherwise, when they themselves have come no further,
but are still framing ordinances out of the scriptures, without the spirit,
and without the life.
Oh, what running to and fro, to find this rest; what divisions in their churches,
so called; yea, divisions and subdivisions, and none seem to be yet settled.
How my soul felt for them! and I was not a little confirmed in my mind,
that a door would be opened, yea, was already opened,
for the true messengers of the gospel to labour profitably in that country,
if they do but travail deep enough in the spirit and in the life,
which it is the earnest solicitude of my soul may be the case there,
and wherever it may please the Lord to send them.

We got to Edinburgh on third-day, and attended their week-day meeting on fifth-day,
which was a time of favour; in the afternoon visited some Friends in their families,
to satisfaction: sixth-day I was unwell, having taken considerable cold,
but got out with my companion to two families, at the last of which I was taken ill,
and did not get away until seventh-day evening, when I went back to our lodgings,
where I still continued so unwell that I was not able
to attend either of the meetings on first-day,
though my companion attended both.

Fourth-day.
After being favoured with a precious, heart-tendering opportunity,
in the family where we lodged,
and with a number of other Friends who came to take leave of us,
we parted from them in much near affection,
and set out for Carlisle by the way of Selkirk and Hawick.
At this place we went to see a friendly man,
who appeared to be convinced of our principles,
and had a religious opportunity with him and his wife, to satisfaction.
We had no meeting until we reached Carlisle, where we arrived on seventh-day,
and on first-day morning attended a meeting with Friends there,
to which came many of the town`'s people,
and in the afternoon we had a pretty large meeting at Scotby, three miles from Carlisle,
both of which were solid opportunities.
We visited several families of Friends at this place, and next day returned to Carlisle,
and from thence took the following meetings: viz., Moorehouse, Wigton, Beckfoot, Allonby,
and a monthly and select meeting at Maryport,
most of which were times of deep and laborious exercise.

From Maryport we went to Broughton, and lodged at the house of our friend John Hall,
who at this time was on a religious visit in America:
we were pleased to find his dear wife and children enjoying
good health and cheerful resignation in his absence.
On first-day we attended their two meetings,
and in the evening had a very precious opportunity with this family,
and several other Friends who came in.
After this we took meetings at the following places: viz., Graysouthen, Pardshaw Hall,
a quarterly meeting at Cockermouth, and a public meeting at the same place,
and from thence we went to White Haven; these last meetings were mostly to satisfaction.
We attended the meetings at White Haven on first-day: I was silent in the morning,
and feeling my mind drawn towards the town`'s people,
we had a public meeting in the afternoon, which was very large,
and the doctrines of the gospel were pretty largely opened to them,
and they seemed to pay great attention; the meeting concluded to satisfaction,
and we went on our way rejoicing.

Next day, visited a few families; the day following, went to Cockermouth,
and from thence to Kendal, and attended the quarterly meeting,
which was a very exercising time to me.
After this meeting was over, I felt considerably unwell, and laid by for a day or two,
but got so as to attend meetings on first-day again, in both of which I was silent.
Next day, being the sixth of tenth month, we went to Lancaster,
and the day following to Preston,
where we attended their little week-day meeting on fourth-day,
which was a very searching time among the few,
but some of them were humbled and contrited before the Lord,
having their states opened and set before them in the authority of Truth.
We lodged with some young people whose parents were deceased; they appeared hopeful,
and we had a precious opportunity with them.

Fifth-day, nineteenth.
Went to Bolton, and had a meeting there next day, to our comfort and rejoicing:
went to Manchester in the afternoon, and on first-day, twelfth,
attended their two meetings, which were large, but a deep, exercising,
suffering time it was to me.
Both of us had something to say near the conclusion of the last meeting,
which was rather particular, but there seemed to us but little room to receive it;
and thus it is, if we who make so high a profession in religion above others,
unhappily settle down in the form, without the life, we become more benumbed, dead,
and hard to reach than any other people.
We left them with heavy hearts,
and in the evening a considerable number of Friends coming in to see us,
particularly of the younger class, we were favoured with a good opportunity together,
which afforded some relief to our exercised minds.

We went from thence to Warrington, where that eminent minister of the gospel,
Samuel Fothergill, in his time resided; and on third-day, the fourteenth,
we attended that meeting, which, at our first sitting down,
I hoped would prove a watering season; but alas, the scene soon changed,
and I was let down into such a state of suffering and distress,
that it seemed as though I was brought to the gates of death,
and hell seemed ready to triumph; yet, blessed be the Lord,
as I endeavoured to trust in him, and patiently wait for his help,
I was raised up again in his power, to declare the everlasting Truth in a close,
searching manner.
Oh, surely, the time is approaching, when the sinners even in Zion will be made afraid,
and fearfulness will surprise the hypocrites; may they be aroused and stirred up, now,
while the day of mercy is still offered.
But alas, many in some places seem settled down at ease, contented with the name,
without the thing itself; and at the same time are so insensible of their situation,
that they can almost bid defiance to the testimony of Truth,
because they do not apprehend that it can belong to them.
Notwithstanding our close, searching labour in this meeting,
the word of consolation was imparted to a few tender-spirited souls,
particularly of the younger class, who appeared to be under a concern,
on account of the low state of things amongst them; may the Lord help them.

Fourth-day, fifteenth, got to Liverpool; on fifth-day attended their week-day meeting,
on sixth-day a burial, and on first-day were at their meetings in course;
most of which were exercising seasons,
yet on the whole they were gotten through with a
good degree of relief to our poor tried minds,
so that we left them pretty easy and quiet, for which we were thankful.
We had a solid opportunity in the evening with the family where we lodged,
and the day closed peacefully.

Second-day, the twentieth.
Samuel Smith having expressed a prospect of going towards London,
and my way seeming pretty clear for Ireland, it became a close trial to us both,
having been favoured to travel together most of the time since we landed,
in the fellowship of the gospel,
but as each of us endeavoured to keep close to our own prospects,
we became resigned to our separation, believing it to be for the work`'s sake,
and not in our own wills; therefore, after calling a number of our Friends together,
in order to let them know the ground of our separation,
I concluded to embark for Ireland by the first opportunity;
but the wind being at this time unfavourable, I stayed here until fifth-day,
and attended their week-day meeting again, when there was another burial,
and the opportunity was pretty open and satisfactory.

Sixth-day, twenty-fourth.
The wind being still unfavourable for sailing out of this port,
a young man Friend from this place agreeing to accompany me to Dublin,
we took a boat and sailed up the river Mersey, about ten or twelve miles to a canal,
where we got into a canal boat and proceeded to Chester, the county town of Cheshire,
and put up at an inn with very civil people.
The passengers in the boat were generally very respectful to us,
though none of them were professors with us; several who lived in Wales,
a considerable distance from this place, came next morning to take leave of us.
There are so few under our name in this place, that Friends are not much known:
it is a large walled town,
and commands a prospect of a most delightful and well cultivated country around it,
and is noted for the ancient structure of the buildings, and its large fairs.

First-day, twenty-sixth.
Attended the little meeting of Friends in the forenoon,
to which came a few not professing with us; and in the afternoon we had a public meeting,
which a number of the upper class attended, among whom was an officer in the army.
The people behaved with becoming solidity, and we had a blessed meeting,
wherein the Lord`'s living power reigned over all,
and his great name was praised to the humble rejoicing of many hearts.
After this blessed meeting we retired to our inn,
a number of Friends came and supped with us, and having invited the people there,
which was my principal object, they were very ready to come and sit down with us,
and a precious religious opportunity we had together,
which I was induced to believe was a fresh visitation to some of them,
particularly the innkeeper and his wife, who were a couple of goodly young people;
they expressed their regret at our leaving them so soon, but we being engaged,
took our seats in the mail coach about one o`'clock in the morning,
and arrived at Holyhead about six in the evening,
the distance being upwards of ninety miles, through a very rough and mountainous country.

The inn being full when we arrived,
we were under the necessity of getting private lodgings,
which we did not obtain without considerable imposition.
Being weary we slept well, and next morning, the twenty-eighth,
arose early and got on board the packet, but it was rainy and boisterous;
we soon got under sail, and had scarcely cleared the Head,
when the wind set in against us,
so that we were beating about for two days and nights before we reached Dublin,
though it had been run, we were told, in eight hours.
This proved not only a rough and tedious, but also disagreeable passage,
there being so many passengers on board before us that we got no bed,
and the passengers were all sea-sick, except myself, and I think, one more;
but all these trying circumstances,
together with that of having the company of some dark, wicked spirits on board,
were made tolerable to me, through the blessed prevalency of a quiet and easy mind,
so that my soul praised the Lord for the preservation
through all these difficulties and dangers.

On fifth-day about eight o`'clock in the morning, we landed in Dublin,
and were conducted to the house of a young Friend,
who received us kindly and gave us some refreshment,
and at our request took us to the house of his father, Joseph Williams.
Being now set down, without a companion, in this great metropolis,
where there are by computation upwards of four hundred thousand souls,
and not one inhabitant whose face I have ever seen before to my knowledge,
the cause I came to espouse, feels precious: O Lord, preserve me.
Sixth-day being the time of holding one of their week-day meetings in the city,
I attended it, though pretty much cast down in my mind, in consequence of my situation;
but it proved a time of favour beyond my expectation.
I had not much to say in testimony, yet was favoured with some precious impressions,
and this language was sweetly uppermost in my mind, "`the kingdom stands not in word,
but in power;`" and I trust this meeting concluded under a
humbling sense of the renewing of this power in many minds.

I soon returned to my lodgings, notwithstanding many kind invitations,
but I want to feel my way clear, before I go much abroad; therefore, O, my God,
be thou pleased to be near me by thy blessed power, and keep me on that foundation,
against which all storms and tempests beat in vain, and upon which alone,
thy people can truly rejoice in thy salvation.
Amen.

I stayed in and about Dublin nearly three weeks,
constantly attending meetings as they came in course, which was three times a week,
but had no opening to appoint any public meeting.
I visited a poor school, consisting of about two hundred children,
and had a religious opportunity with them to satisfaction,
which also appeared to be well received by their teachers.
I also visited several Friends in their families, attended the burial of a Friend,
and was at one of their monthly meetings;
and feeling my mind clear of Dublin for the present,
I may say with heartfelt thankfulness and gratitude to my God,
I leave Friends here in love,
there appearing among them a general openness to
receive me and the testimony given me to bear,
notwithstanding some unhappy divisions had gotten in among them,
to the great grief of the right-minded.

Having prepared myself to travel on horseback,
I set out from Dublin the nineteenth of the eleventh month,
and took my journey into the north of the nation.
The first meeting I came to was Rathfriland, about fifty-seven Irish miles from Dublin,
where I had a public meeting, many of the town`'s people came in,
and it was to pretty good satisfaction.
The next meetings I took, were Lurgan, Hillsborough, Milecross, Belfast, Ballinderry,
Lisburn, and back to the quarterly meeting at Lurgan, for the province of Ulster,
which was held on the eighth of the twelfth month.
I had considerable satisfaction in most of these last mentioned meetings,
especially in a large public meeting at Lisburn,
to which came many officers and soldiers.
I think I never saw so many people of this description at a meeting before:
they behaved in a solid and becoming manner, and the people generally seemed satisfied;
several of the officers stopped at the conclusion of the meeting to take me by the hand,
which they did in a respectful manner,
and I believed many of them were sensible of the favours of that evening.

After the quarterly meeting was over, I took meetings at Moyallen, Antrim, Grange,
Colerain, Charlemount, Richhill, Coothill, Edenderry, Rathangan,
and so to the quarterly meeting at Carlow for the province of Leinster,
which was held the twenty-ninth of twelfth month: in most of these meetings,
the testimony went forth with clearness and good authority,
much to the relief of my mind.
O, it is of the Lord`'s mercy and goodness to his poor ambassadors,
yea and the power of his love, both secretly and openly manifested in and through them,
that they are thus supported and carried through perils by sea and perils by land, yea,
and perils among false brethren: blessed be his name forever,
which is a strong tower in the day of trouble for all his faithful, dependent children.
O may I find access to it in every dispensation,
that so I may be enabled to hold out through every future storm and tempest,
peril and danger, of whatsoever kind he may be pleased to order or permit,
even unto the end.
Amen.

The next meetings I attended, were Kilconner, and back to Carlow,
and had a public meeting there, and then to Ballitore, Athy and Mountmellick.
First-day, eleventh of first month, 1801,
I attended the fore and afternoon meetings of Friends at Mountmellick for the first time;
they were large, there being two private boarding-schools of Friends in this town,
also many of the inhabitants are Friends.
On my first sitting down among so many good looking Friends,
I hoped the tide of gospel life and power would have arisen amongst us,
to our comfort and rejoicing; but, alas! when we look outward,
how often are our pleasant prospects blasted, and we disappointed in them.
This was truly a laborious exercising meeting, with very little relief;
and in the afternoon, -- O, this afternoon, when shall I forget it?
verily it seemed for a considerable time, as if death and hell triumphed,
and the pains thereof had got hold of me;
pains which I believed were not much unlike the miseries those souls
endure which are forever separated from the presence of God;
so that I often cried out in my spirit,
Lord have mercy on me! what shall I do?
I expressed very little in testimony and sat down,
and at length being clothed with the spirit of supplication,
in as awful a degree as I almost ever experienced it,
I was engaged to call publicly on God omnipotent,
that he would be pleased to break the chains of death, the bands and fetters of hell,
in the hearts of the people,
and remember in mercy the poor souls that were laying under the altar,
crying in the bitterness of their spirits to Him for help.
This was the substance of the language with which I was awfully
engaged to address the almighty Father in this congregation;
and blessed be his ever adorable name, He was pleased to draw near,
and by the arising of his own power, caused the powers of darkness to tremble;
under an humbling sense whereof, my soul felt relief as I arose from my knees.
For two nights before this, I got very little rest,
walking in my room when all were asleep, crying to the Lord for help;
but praised be his goodness, this night I had good rest, yet being nearly tried,
I see the need I have of crying daily to Him,
for the support of his blessed arm under every dispensation, that so indeed,
"`neither heights nor depths, principalities nor powers, things present nor yet to come,
may ever be able to separate me from his love, which is in Christ Jesus our Lord.`"
Amen.

I stayed here until fourth-day, and attended meeting with them again,
Elizabeth Wigham and her companion also attended, and Truth was again exalted over all,
to our humble rejoicing, and the great name was praised, who alone is worthy forevermore.
In the afternoon I set out in order to be at the quarterly meeting at Clonmel,
about fifty-two Irish miles from this place;
we attended one small meeting in the way at Ballynakil,
and then went to the aforesaid quarterly meeting, held for the province of Munster.
This meeting was large, and I thought on the whole,
the most solid quarterly meeting I have attended in this nation.

The meeting for business was held on second-day,
and a large parting meeting on third-day, which was a time long to be remembered by me,
and I humbly trust by many more present: my cup ran over and I wept tears of joy,
rejoicing in God our Saviour,
and the souls of many bowed and worshipped Him who lives forever and ever.
I visited several families of Friends after this memorable meeting,
and next day set out for Mountmellick again, where we arrived the day following,
though it was very cold and snowy, but through all I am preserved in good health.
Stayed over their two meetings on first-day,
and visited the young women`'s boarding-school to satisfaction,
and this week went to Ballymurry, in the county of Connaught,
about forty-two Irish miles from Mountmellick, taking a meeting at Moat in my way;
had a meeting with Friends and a few others at Ballymuwy, and returned to Moat,
and attended their two meetings on first-day, and visited a family or two in the evening.
On second-day, rode to Tullamore, and had a meeting with a few Friends there;
then returned again to Mountmellick, and attended their week-day meeting,
which was large,
and something was experienced like the precious evidence of victory over that spirit,
which so oppressed and bore down my soul when I was first at this place.
Here are a few exercised sincere souls,
with whom I was nearly united in their low and tried situation.
The Lord, who knoweth them that are his, gave us the victory,
and we were made to rejoice together in his salvation; blessed be his name forever.
O, saith my soul, may these hold fast their confidence in Him,
and not give way in the day of battle and sore conflict, which must be their portion.

I visited the provincial school for Friends`' children,
and had a religious opportunity with them to satisfaction, and then leaving Mountmellick,
I took meetings at Mountrath, Knock, Roscrea, Birr, and so to Limerick,
most of which were favoured opportunities, except the last, which was a very hard,
laborious time, without much relief.
It seemed to me as though the world had well nigh gotten the victory at this place:
what exercising meetings, what times of suffering among a people so captivated,
do those experience who are endeavouring to choose the Lord for their portion,
and to have their minds centered on things above;
may I always be enabled to prefer Jerusalem to my chiefest joy in this world,
and those things which endure forever, to those which must soon pass away,
and perish with the using.

From Limerick I went to Cork, about fifty-two miles, and having taken a cold on my lungs,
I kept house pretty much for several days, though I attended meetings with Friends,
as they came in course, and once visited a little meeting at a place called Bahdor,
about fourteen miles off, and returned to Cork.
And now I have freedom to mention,
that my mind has been deeply baptised whilst in this large city,
not only in religious exercise and labour,
but also in the prospect of the suffering state of the poor.
I had seen and felt it generally through the nation, but here it was more obvious.
One night, just after I went to bed,
the town was alarmed with an apprehension that a mob was collecting;
and several parties of soldiers were called out and sent in different directions,
in order if possible to prevent it.
But all efforts of that kind proved in vain, for next morning it took place,
and an awful scene it was to me.

Being in my chamber, and hearing a great noise, I looked out at the window,
and behold the street was darkened with multitudes of poor meagre looking creatures,
with the marks of want and distress imprinted on their countenances,
and as a token of their starving condition,
they had a small loaf of wheat bread fixed on a staff,
and just above it a piece of poor looking barley bread, dressed in black cloth,
which hung down a little below it.
This was surrounded by a company of poor, miserable looking women and children,
who marched towards the Exchange and went to the mayor of the town.
The general of the army then stationed in Cork, observing their motions,
rushed on before them, and like a wise moderate man,
advised the mayor to go out to meet them and speak kindly to them,
and promise them some relief, and advise them to go quietly home; which he did,
and it had the desired effect.
But relief not coming that day;
O what will not hunger drive men to! the next morning
the same awful scene passed again before my eyes,
only with a more formidable and desperate
appearance--the general then drew out his troops,
and stopped their march, while he ventured to ride in among them,
and endeavoured to reason with them, and succeeded in dispersing them without mischief.
Measures being then immediately devised for their relief,
they were afterwards quiet during my stay there:
the number of inhabitants in this city is said
to be about one hundred and twenty thousand,
and more than a fourth part of them were at this time in a state of want.

From this place I went to Youghall and attended two meetings; thence to Garryroan,
where I met Samuel Smith, who had lately arrived in this nation from England.
Alter a very exercising meeting we went to Clonmel,
where we attended several meetings together, and also visited a number of families,
all to pretty good satisfaction; indeed,
some of these opportunities were eminently owned with the divine presence and power,
insomuch that the gospel tide seemed to overflow its banks,
and cause almost a general watering; blessed be the name of the Lord,
who hath richly rewarded me for my second visit to this place:
may it also tend to the benefit of the visited,
but this I must leave in the hands of Him, who alone can give the increase,
and return Him thanks for the evidence of peace in the labour.
Amen.

We went next to Anner Mills, and spent a day with Sarah Grubb and her school children,
where a considerable number of Friends came in the afternoon to see us,
and we were favoured with a precious heart-tendering opportunity together.
Next day Samuel Smith and I parted again, he going towards Carlow, and I to Waterford;
attended three meetings at this place and visited some Friends to satisfaction.
From Waterford I took meetings at Ross, Forest, Cooladine, Enniscorthy, Ballentore,
and so by Carlow, to the quarterly meeting at Mountmellick,
where I again met Samuel Smith, and we attended the quarterly meeting together, which,
on the whole, was a solid, instructive time:
we also attended their week-day meeting and another at Mountrath about eight miles off,
which was a blessed watering opportunity to a number;
we returned to Mountmellick with joyful hearts.

On second-day, seventh of fourth month,
I set out in company with several other Friends to attend the quarterly meeting at Cork,
about ninety Irish miles from this place, and Samuel Smith went towards the north.
I had an agreeable journey, attended the quarterly meeting,
which was a time of instruction, though very exercising for the most part,
and returned directly back to Mountmellick, with a peaceful mind:
tarried there one night, and next day went to Rathangan, where I again met Samuel Smith,
who had been detained there about a week with indisposition:
we were glad to see each other again in a strange land.
On first-day, I attended both their meetings here, and next day,
Samuel being a little recruited, we took the canal-boat and went by water to Dublin.

Third-day, attended one of their meetings in the city,
and on fourth-day I went to Wicklow, about twenty-three miles,
had a meeting with Friends and a few others, and returned to Dublin,
in order to attend the yearly meeting which began with
a meeting of ministers and elders on seventh-day,
twenty-fifth of fourth-month, and on second-day the meeting for business opened,
which held by adjournments, until third-day, the fourth of fifth-month:
and notwithstanding it appears to be a low time
with the Society in many places in this nation,
insomuch that there is at present a great forsaking in the land,
and even a time of treading down and trampling under foot many of the
precious testimonies and privileges which our forefathers dearly purchased,
and left us in the quiet possession of; yet, blessed be the Hope of Israel,
He was pleased to draw near in several of the sittings of this yearly meeting,
and to evince by the exaltation of his truth and the power thereof, over all opposition,
that he hath not forsaken nor forgotten to be gracious to the remnant of his people; yea,
the remnant of this people,
whom he gathered out from the "`lo-heres,`" and the "`lo-theres,`"
and brought to sit down under his own immediate teaching.

Blessed forever he his great name, may his Israel now say.

Feeling my mind now released from any further travelling or
prospect of religious labour in this nation,
I signified the same to Friends near the conclusion of this yearly meeting,
and they accordingly gave me a certificate of unity
with me in my religious labours amongst them.

On fourth-day, the fifth of fifth-month, I took a solemn farewell of Ireland,
and with Samuel Smith, his companion, and Mary Sterry from England,
and several Friends from this nation going over to the yearly meeting at London,
went on board a small vessel called a cutter,
and arrived at Holyhead the next day in the evening.

[.embedded-content-document.letter]
--

+++[+++Editor`'s Note: His visit to Friends in Ireland,
was somewhat extraordinary in its character and productive of memorable consequences.
A short time previous to his going into that nation, a number of persons,
members of the Society, deluded by false pretensions to spirituality,
and greater degrees of light on religious subjects than the rest of their brethren,
began to promulgate many wild and sceptical notions
relative to the doctrines of the Christian religion.

The avidity with which undisciplined and superficial
minds grasp that which is clad in the garb of novelty,
and the propensity to amuse themselves with speculation,
rather than submit to the restraints of the religion of Jesus Christ,
render the propagation of error less surprising than it would otherwise be.
Against the dangerous errors embraced by many under the name of Friends, in that Island,
Richard Jordan bore a solemn and powerful testimony -- he laboured with undaunted zeal,
to expose their falsity, warned both old and young against adopting them,
and under the influence of a prophetic spirit foretold the
sorrowful consequences which they would inevitably produce,
if persisted in.
And he lived to see these predictions verified.
The hand of Divine Providence seemed to be turned against the
advocates of these notions in a remarkable manner.

Some who had lived in ease and affluence experienced a sad reverse in their situation;
many not only lost their religious reputation,
but even suffered in their moral character,
and became an astonishment to their former acquaintances.

Others, awakened by timely warning, abandoned their errors,
and through the mercy of a gracious Redeemer
came to experience repentance and forgiveness:
they embraced the Christian religion in faith and sincerity,
and were again restored to the bosom of the Church.

When the same pernicious principles invaded the
peaceful borders of the Society in America,
and began to spread discord and unbelief among its members,
Richard Jordan as a faithful and experienced watchman,
was one of the first to raise his warning voice,
and exert himself under the influence of Divine love,
to counteract their baneful effects.]^
footnote:[From [.book-title]#A Biographical Memoir of Richard Jordan#]

--

Early the following morning we hired a coach and chaise, and set out for London,
going by the way of Salop, Colebrookdale and Birmingham,
at all which we attended meetings; and arrived in London on the fifteenth.
I am now here, in this great city of London, comparing my situation to an empty purse,
and as dependent as the sparrows that have neither storehouse nor barn.
Lord, thou feedest them; I also endeavour to look unto thee for support;
and I pray thee look down upon me, preserve and support me, if it be thy blessed will,
that so I may be kept from dishonouring thy holy cause, wounding any of thy children,
or making work for sorrow and repentance to my own soul; that thus, through thy grace,
O Lord; I may be enabled to honour thee in thought, word and deed,
who art worthy forevermore.

I took my lodgings with our friend Josiah Messer, who,
with his wife and children were affectionately kind to me.
On first-day, seventeenth, attended two meetings at Westminster,
in both which I was silent;
also in two sittings of the yearly meeting of ministers
and elders on second-day at Grace Church Street.
On third-day morning, the meeting of ministers and elders sat again,
and in the afternoon a large meeting, for considering the state of Ackworth school.

The yearly meeting for discipline began on fourth-day, the twentieth,
at Devonshire house, at the opening of which I had a little to communicate,
and a precious covering spread over the assembly.
This meeting was very large,
and continued by adjournments until the second of the sixth month,
in the course of which, several important and interesting subjects were deliberated on,
and we were favoured with many fresh evidences,
that notwithstanding all the weaknesses and
deficiencies prevalent amongst many of the members;
as a society we are still owned by that ancient
Goodness which first gathered us to be a people,
and many were given renewedly to rejoice in his saving help, and to adopt the language,
"`What shall we render unto thee for all thy benefits!`"

The next day after this large and solemn assembly concluded,
the meeting of ministers and elders sat again,
where it appeared that all the other American Friends, four in number,
now in this nation on religious visits,
were clearing out in order to return to their respective homes,
some of them having been here several years;
so that I am likely to be left as it were alone, in this strange land.
A prospect which I had before leaving home,
of visiting some parts of the continent of Europe, now revived,
and I expressed it in this meeting, with which it feelingly concurred,
so that I know not yet how long I have to sojourn here, a poor lonely pilgrim.
Be pleased, O Lord, to keep near and guide me in the right way.
