== Chapter 4

I continued in and about London until the middle
of the seventh month--attended many meetings,
some of which were very laborious and exercising,
and others eminently favoured and owned by the divine power and presence,
to the humble rejoicing of many.
And now feeling my mind clear of London for the present,
and having procured my passports for leaving this country,
it being a time of war with France, and having the company of two young men Friends,
going over to Germany on business, I left London the fifteenth of seventh month,
and took post-chaise for Yarmouth, about one hundred and twenty miles,
where we arrived next day, and put up with a Friend whose name is William Sewell,
where we were kindly accommodated until the packet in which we were to embark,
sailed for Hamburgh.

Priscilla Gurney and her companion, whom I had seen in London,
being now engaged in a visit to the families of Friends in this place,
and the packet not sailing until third-day the twenty-first,
I joined them in the visit on sixth and part of seventh-day,
and attended two meetings on first-day, one of which was a public one;
all to good satisfaction.
On second-day sat with them in a few more families,
and very early on third-day morning we were ordered on board,
but all the passengers did not get collected until nearly seven o`'clock, there being a,
large number, made up of different nations and tongues,
among whom was the Prussian ambassador to the English court;
he and his wife were very agreeable persons,
accommodating themselves to the passengers with much affability and respect.

Besides these, there were Jews, Italian, German, French, English,
and myself being an American, made the sixth nation:
we soon got under sail and had a fine passage of
about fifty-seven hours to Cuxhaven in Germany,
one hundred leagues from Yarmouth; all the passengers were very civil and respectful.
At Cuxhaven we got pretty good accommodations at an inn,
and next day several of us who were bound to Hamburgh;
hired a small vessel and had an agreeable sail up the river Elbe,
about seventy miles to Hamburgh; but as they did not permit any to pass through,
or come within, the gates of the city of Hamburgh, after nine o`'clock at night,
we were not in time for admission, and therefore lodged in a little town called Altona,
about a mile below, where we were well accommodated at an English inn,
and on the following day hired a couple of men to carry our baggage,
and went into Hamburgh, where we put up also at an English inn.
The Elbe, divides Holstein, belonging to the king of Denmark on the north, and Hanover,
belonging to the king of England, on the south.

Finding no opening for religious service in Hamburgh, I went to Altona,
and spent a little time with Vander Smithson, a religious man,
who appeared to be convinced of our religious principles, and whose son,
Gilbert V. Smithson, I had seen in Scotland about a year before.
I then returned to Hamburgh, and on fifth-day, the thirtieth,
we took our journey towards Pyrmont, travelling all night through a dreary country,
thinly inhabited, where no comfortable accommodation could be had for a long distance.

Having taken some provisions with us,
we travelled on until about twelve o`'clock next day, when we arrived at Zell,
about sixty-eight English miles, and at ten that night reached Hanover,
a very fine inland town, and famous for the king`'s gardens.
The next place we halted at was a little town called Sprent, seated in a fertile valley,
covered with luxuriant crops of grain,
and the high hills surrounding it clothed with beautiful groves of trees,
which afforded a delightful prospect;
the deep green verdure of the forests circling large fields of corn,
now whitening for harvest, and the labourers just entering into them.
O,
that I could have seen as much respecting the spiritual condition of the
people among whom I have been travelling in these parts of Germany;
but, alas! until I came to this place,
on which nature has so bountifully bestowed her gifts,
I have seen very little that seemed to attract my particular notice,
except the barrenness of the soil, and the licentious,
extortionate disposition of the people, which has been evinced with very few exceptions,
so far as we have had any thing to do with them.

At this place we had to wait for a change of horses,
being under the necessity of submitting to the common way of travelling in this country,
which is, for the traveller to procure a carriage of some sort,
and then hire horses from stage to stage,
the length of each being about three German miles.
The hire of these horses must be paid before we leave the post-house,
at the rate of half a rix dollar per mile for each horse,
and then in getting to the next stage, submit to the impositions of a dull, slow,
and sometimes insolent postilion,
that cannot be urged beyond his common gait for love or money,
and yet has a right to demand what they call snap money,
which is about six or seven pence per mile,
to furnish them with beer and a bit of coarse bread for their horses,
which is their common custom.
Such is the slow motion of some of them, that at one time,
I think the boy with a good looking pair of horses,
drove us only about one of these miles in two hours.
I can hardly forbear remarking on their extortion at the inns,
where they generally charged for each person, two marks for dinner, and two for supper,
without any kind of drink; two marks for each single bed,
sometimes with extra charge for candlelight; and for breakfast of tea or coffee,
one and a half marks, the marks are about one shilling and six pence sterling each,
and the rix dollar four shillings.

Seventh-day, first of eighth month.
We reached Pyrmont about ten o`'clock in the evening,
and were kindly received by Frederick Seebohm, with whom we lodged that night.

First-day, second, attended the two meetings of Friends at Pyrmont,
to which came a considerable number of persons not of our Society,
it being a place much resorted to by people from many parts of the world,
on account of the mineral waters, which are esteemed the best in Europe.
I had never before spoken through an interpreter in a meeting,
but being pretty soon opened in the love of the gospel towards these people, I stood up,
and a well concerned Friend of this place interpreted for me.
We were favoured with a blessed opportunity
through the fresh extendings of holy goodness;
indeed such was the spreading and prevailing of divine power and mercy,
that my interpreter could not refrain from tears as he rendered what I spoke into German,
there being very few present who understood English.
Many people also attended in the afternoon,
and the gospel was again freely preached to them;
a number appeared to be humbled under the precious influences thereof,
so that both these meetings concluded in a solemn manner,
and I humbly trust that the souls of many bowed with my own,
and worshipped and praised the Lord for the renewed manifestation of his love and mercy.

Next day I took my lodgings with my kind interpreter, at a place called Peacedale,
about one English mile from Pyrmont:
it is beautifully situated on the side of a rich fertile valley,
and surrounded with high hills, which are covered with delightful groves of trees.
Several other Friends also live here; their houses form a kind of village,
and they have a manufactory of cutlery,
in which a number of the poor Friends are employed,
also a spinning factory for the poor women Friends.
The prices of labour in this, as well as several other parts of Europe, are so low,
that many of these industrious people are very poor and hard set to get a living,
so that I often felt deeply for them.

About four o`'clock on second-day afternoon,
their monthly meeting was held at this place, for Friends of Pyrmont and Minden,
this last being a small meeting within the territories of Prussia.
After a considerable time of silence, when the clerk was just proceeding to business,
I stood up with these words; "`in those days, when there was no open vision,
the word of the Lord was precious;`" and through the renewing of his ancient goodness,
which is ever new to those who are made partakers of it,
this was a time which I hope will not soon be forgotten by many of us then present;
my cup run over, and I wept tears of gratitude and joy before Him,
who had enabled me to leave my all in this world, for his blessed Gospel`'s sake,
and the good of souls, free from any prospect of outward interest and gain:
the countenances of many at this blessed season of favour, as well as their hearts,
were softened and bedewed with tears, acknowledging it to be the Lord`'s doing,
and I think one or more of them, in words, at or near the conclusion of the meeting.
After this, I returned to my lodgings with the incomes of sweet peace,
and I now did not regret the many conflicts and difficulties
which had attended my coming to see these dear people.
O,
may my soul be filled with thankfulness for the
abundant fulness of comfort it now enjoys,
for in addition to the inexpressible favour just hinted at,
the next day I received letters from home, giving agreeable information of the health,
peace and harmony of my dear wife and little family,
and also of the prosperity of my outward affairs; blessed be the Lord.

Fourth-day, fifth; a good time at the weekday meeting;
next day wrote sundry letters to my friends in America.
Sixth-day, the young man who came with me from London left me, and returned homeward;
thus I am once more left as it were alone in a strange land,
but I will endeavour to lean on the blessed Arm which hath hitherto supported, preserved,
and carried me through; Lord enable me so to trust.

First-day, ninth, attended the fore and afternoon meetings at Pyrmont;
many not of our religious Society were there; some of whom were very light and airy.
I had considerable communication amongst them in the morning,
and my interpreter in the afternoon, and both were, on the whole,
pretty solid opportunities.

Fourth-day, twelfth, I was at the week-day meeting again,
which was also a pretty solid time.
Seventh-day, accompanied by Lewis Seebohm,
I went to visit the little meeting of Friends at Minden in Prussia,
it being about forty-two English miles from Pyrmont.
We got there the same evening, and put up with Frederick Smith,
an honest Friend of that place, who with his daughters,
received us very kindly and affectionately.

First-day.
We attended the two meetings of Friends, which were both highly favoured seasons,
especially that in the morning;
it was much crowded by people not professing with Friends,
and a door was opened to preach the gospel among them with clearness and good authority:
the people were very solid and attentive, and appeared to be well satisfied,
and the meeting concluded in solemn prayer and supplication.
This was the first time I was ever engaged in this awful service through an interpreter;
he kneeled down beside me, and seemed nearly united with me in spirit,
as he translated my words, with which the people seemed also to unite.
Many of them came forward at the conclusion of the meeting, and took me by the hand,
in a very solid, affectionate manner; indeed,
I felt a stream of gospel love in my heart towards the people as I walked the streets,
the countenances of many seemed to me to bespeak the sadness of their hearts,
and a desire to be relieved from the yoke of spiritual bondage; my soul secretly prayed,
May the Lord Almighty help them!

A dear, seeking woman, having heard of my intention of being at Minden at this time,
came fifteen miles in the morning on foot, to be at the meeting,
but being detained in crossing a river,
did not reach Minden in time for the first meeting: she attended that in the afternoon,
which was also a blessed time, through the renewing of holy help.
She came and supped with us in the evening, and on being asked,
if she was not weary with her walk, replied,
"`Nay;`" seeming rejoiced that she had been at the meeting.
Many of these dear people would stand, and look me in the face with tears in their eyes,
regretting that they were not able to speak to me,
telling my interpreter that the language of their hearts towards me was love, and truly,
mine often over-flowed with love to them.

Second-day, seventeenth, I requested a meeting for Friends only,
which was held at the house where we lodged, a little out of the town:
the aforementioned woman, and another sober person or two, also attended it.
At this meeting I was permitted, to dip my foot afresh, as it were, into oil,
as rejoicingly so perhaps, as I ever experienced; and O, saith my soul,
what shall we render unto the Lord for all his benefits, which we cannot merit,
and especially such eminent condescendings of his love and
goodness as he was pleased to vouchsafe to us this day,
under a humbling sense of which,
our souls seemed melted down together as wax before the sun, so that there were few,
if any dry cheeks in the meeting;
may the Lord sanctify this favour to our lasting benefit,
and take all the honour to himself, unto whom it is due, now and forever; amen.

Third-day.
Early in the morning we left Minden and returned to Pyrmont,
and next day attended the week-day meeting there,
which was a comfortable time in silence,
and I had to believe that many were made to feel that which is preferable to words;
may they grow and prosper therein.

First-day, twenty-third.
I attended the two meetings here for the last time:
in the morning I was pretty largely opened in testimony, and it was a precious time:
in the afternoon I was silent, but my interpreter had some communication,
which appeared to afford satisfaction, and to command stillness in the meeting,
which had been somewhat interrupted by a man in liquor, but ended quietly.

Not feeling quite easy to leave Pyrmont without seeing Friends together by themselves,
I proposed such a meeting this evening, and in order to effect it they met at Peacedale,
and a few others under convincement also attended.
The forepart of this meeting was rather hard and laborious,
requiring great deliberation in delivering what I had to say,
looking well for the stepping stones, which seemed to lay in such an intricate situation,
that it brought discouragement over me, and I began to look for a stopping place;
when blessed be the Lord, his power broke in upon us, and was so eminently manifested,
that it proved like a plentiful shower upon the thirsty ground,
and we were generally broken and melted down before the Lord,
and his great name was praised, who alone is worthy, now and forevermore.

After this memorable meeting, I felt, as I apprehended, fully released, and next day,
being the twenty-fourth, Lewis Seebohm having agreed to accompany me as interpreter,
I took my solemn leave of Friends, and set out for Amsterdam in Holland,
about two hundred and forty miles distant.
We travelled about six German miles to Bielfeldt,
where we got a pretty comfortable lodging.

Twenty-fifth and twenty-sixth.
We travelled most of these two days among Roman Catholics,
and along the way side there were abundance of crosses and images,
particularly at the parting of roads:
at the most noted places was the pretended image of our Saviour,
which appeared to be made of a kind of alabaster,
and was nailed to the cross in the attitude of expiring;
on some of them was also represented the crown of thorns.
At other places were images of Mary and the child Jesus, placed on stone pillars,
and also likenesses of several of the saints.
O,
how my soul secretly mourned over the great superstition
manifested among them in these and other respects;
yet notwithstanding their ignorance,
they received and entertained us kindly for our money,
and seemed to look respectfully on us, though probably by them accounted heretics.
Many of them had goodly countenances, and I did believe were sighing under their burdens;
may the Lord look down in mercy on these and hasten the day of their deliverance.

Twenty-seventh.
We entered Holland, and making a little halt at the first town we passed through,
I felt my mind so strongly drawn in gospel love towards the inhabitants,
that I could not help thinking of a meeting among them,
and mentioned it to my interpreter, but no way seeming to open then, to bring it about,
I heavily passed on, and most of this day felt rather uncomfortable.
May the Lord do more for them than such an opportunity could have effected.

Sixth-day, twenty-eighth.
We got to Utrecht, a neat, well built town on the Rhine, where we lodged,
and on seventh-day we had a very agreeable ride of about twenty-four English miles,
into Amsterdam, the road lying along a great canal,
on the banks of which for a considerable part of the distance,
were beautiful country houses set off with delightful walks, groves of trees,
beautiful arbours,
and the most extravagant temples of pleasure I had ever seen in any country;
these were surrounded with extensive level fields of grass, like a plain,
over which were dispersed herds of fine cattle feeding.
In viewing these delightful improvements, which were like a pleasant garden,
I concluded within myself,
that if these people were but gathered in spirit to the
alone source of all true and permanent happiness,
and to an humble dependence thereon,
this place would approach the nearest to a paradise below,
of any situation I had ever seen.
But alas,
a disposition quite different from this seemed to me to prevail in this country,
that is to say, soul eat, drink, and enjoy the good of all thy labour,
for thou hast goods laid up for many years.

Having heard of a few religious people in Amsterdam M`'
ho had forsaken the national worship,
and for some time had met together, and sat in silence,
pretty much in the way of Friends, we sought them out this afternoon,
and proposed sitting with them on the morrow, of which they seemed glad.

First-day, thirtieth.
We went near half a mile from our inn to meet these people, and sat down with them.
I soon felt, as I apprehended,
that although their outward appearance was not much like Friends,
their beginning was under a right dispensation,
and their disposition like that of children who were willing to be instructed.
The truths of the gospel ran forth like precious oil amongst them,
and a blessed watering time we had, both in the morning and again in the afternoon;
may the Lord send them help out of Zion, saith my soul.

Second-day.
According to the custom of this place, we gave in our names, places of abode,
and business, and waited on the Burgher`'s office with our passports;
they refused at first to admit us into the office with our hats on though my
interpreter informed them that we were of the people called Quakers,
and it was a religious, scruple we had, and not from contempt or disrespect to any,
that we refused that honour to men; one of them said, in a scoffing manner,
that the spirit had not told him so.
We were turned into a long entry, until they had taken counsel of their committee,
as they said; and after we had waited without, a considerable time,
which we were favoured to do patiently, we were called in,
and respectfully received with our hats on.
They then executed our business and discharged us in a friendly manner, without any fees,
and we went on our way rejoicing that we had been enabled to
bear this little testimony on behalf of Truth and Friends.
We then went and spent a little time with some of those friendly people aforementioned,
and they seemed to rejoice in our faithful testimony before the magistrates,
so that we hoped it would tend to their encouragement under similar trials.

Fourth-day, second of ninth month.
We attended another meeting with the aforementioned friendly people to satisfaction.
There are now no members of our religious Society in Amsterdam,
though formerly there was a considerable number:
the remains of a fine meeting-house are still there,
which with a considerable privilege attached to it, belong to the Society,
and are under the care of Friends in England.
We went to see the house,
and I having been requested by the meeting for Sufferings in London,
to attend to some business respecting the estate belonging to Friends as aforesaid,
they not having opportunity to do it, during the late troubles in Europe,
we undertook to examine into it for them, and settle it as well as we could,
which occupied part of two days, it having laid a considerable time neglected;
so that our attention appeared to be very seasonable,
and gave Friends in England good satisfaction,
and we were glad that it was in our power to assist them herein.
This week I also waited on our American consul,
in order to procure a passport to travel in France;
he treated me with much kindness and civility, gave me a good passport,
and would not take any fee for it, though entitled to it in virtue of his office.
I also called at the French consul`'s office the same day,
where I likewise met with civility and attention,
and got my passport endorsed under the seal of the French Republic.
We went to see several religiously disposed people in the city,
not those we first met with; stayed over first-day,
and attended two more meetings with those first mentioned serious people,
several others also coming in,
these were both favoured opportunities and the evening closed peacefully,
blessed be the Lord.

Fourth-day,
Lewis Seebohm having after some difficulty obtained passports to travel in France,
this morning we left Amsterdam and took our journey towards Antwerp in French Flanders.
We went about twenty-four miles this day in a treckschute,
along a large canal to a town called Gouda, where we lodged,
and next day took the mail for Antwerp.
We travelled until about nine o`'clock at night,
when my interpreter was taken so ill that we
were obliged to stop at an inn until morning,
when finding himself better we proceeded and reached Antwerp about ten o`'clock.
After taking some refreshment we went to the town-house,
and presented our passports for examination; they received us with much civility,
and put off the examination for a few hours on account of the press of business,
fixing an hour for us to come again.

We went accordingly about the time appointed,
and got our passports endorsed under the seal of the French Republic,
and delivered to us very respectfully, so much so, that I told the principal secretary,
if I lived to return to my country again,
I should take pleasure in speaking well of French civility and kindness;
he seemed somewhat affected, and said it was but their duty to do so,
and took his leave of us in a very friendly manner.
Thus, way has been made for us hitherto, even in the minds of those in authority.
Our endorsements recommended us to the Prefect`'s office in Paris,
and we journeyed on through a fine, well cultivated country,
and lodged in a neat and well built town called Ghent.

First-day, twelfth, travelled in a very heavy carriage called the Diligence,
carrying many passengers, I think at one time we had fifteen,
and the roads so broken up in some places that we were obliged to get out and walk.
One of these carriages broke down just behind us in the evening,
but we were favoured to get to our intended lodging place, a fine town called Lille,
where we were put into a room the most extravagantly
furnished of any that I ever lodged in,
and being very weary I soon got to sleep.
On second-day we could get no stage, and were therefore obliged to remain at Lille;
but on third-day we proceeded,
though the roads in some places were so bad and the carriage heavy,
that at one place the horses stopped, and we all got out to walk,
but my interpreter having observed that walking fatigued me,
persuaded me that I had better get in again, and I at length consented,
though I did not feel easy with it,
which seems as though the mind sometimes receives a presentiment of approaching distress.
I believe I had not been in the carriage five
minutes before the horses ran off the causeway,
and overset it down a precipice perhaps twelve or fourteen feet.
The fall was very great, and the postillion seeing the danger jumped from his seat,
before the carriage went down, leaving all to me who was shut up alone,
and had no chance of escape.
Ah! surely it is of the Lord`'s mercy that I am left to give this account.
The passengers who saw the carriage go down thought I was killed,
and ran back as quickly as they could.
I opened the door, and begged some one to help me out,
when they found not even a bone broken, only my right hand was strained,
and my leg and shoulder on the same side much bruised.
The French passengers were all very kind in assisting me, especially a lawyer of Paris,
who had travelled with us from Gouda,
and when I became so ill that I could not go on in the stage,
stayed with us until we arrived in his native city of Paris, which was on the eighteenth,
his name was Alexander Moyanat.
He continued his kindness as long as we stayed in Paris,
coming frequently nearly a mile to see us, and several times invited us to dine with him.
Had I not been in so much pain from my hurt,
I think I should have enjoyed the fine prospects in this beautiful country;
and I may safely say from general observation,
that it rather exceeds any country I have ever before travelled in.

At Paris we met with Abraham Barker, a Friend from New Bedford in North America,
and no way opening for any religious meeting at this place, when first-day came,
we sat down together in our hired room in silence, and a sweet time it was to me.
It may not perhaps be amiss to mention how we were treated at the municipality,
when we attended to present our passports.
We were stopped by the guards, who had strict orders, it seems,
not to suffer any man to pass, unless he had what is called a cockade in his hat,
but on our desiring our guide to step forward and inform the officers,
that we were of the people called Quakers,
and that our not observing those signs of the times was not in contempt of authority,
or disrespect to any in office, but from a religious scruple in our own minds,
it being the same with us in our own country, they readily accepted our reasons,
and one of the officers came and took us by the guards and so up into the chamber,
where we were suffered to remain quietly with our hats
on until our passports were examined by two officers,
and again endorsed under the seal of the Republic,
permitting us to go to Calvisson in Languedoc.
Thus it often appears to me that we make our way better in the minds of the people,
when we keep strictly to our religious profession,
in all countries and amongst all sorts of persons.

I not being well able to travel, we stayed here for several days,
and though no way seemed to open for a religious meeting,
we spread several books which we had taken with us for that purpose,
and found considerable openness in the minds of the people to receive them;
they treated us with much civility and respect.
We also went to Versailles about twelve miles from Paris,
where we met with some friendly people who seemed glad to see us;
we only stayed here one day, and returned to Paris.
Twenty-third was what the French call their Decade,
or the anniversary of their revolution, which seemed to be kept with great joy,
and such a concourse of people as were collected on the occasion, I never before saw.
The Friend aforementioned and myself took a walk in what are called the Elysian fields,
and were not a little surprised to observe the order
that prevailed throughout this vast concourse.
I think we did not observe one drunken man,
or the least sign of wrangling and scarcely one loud sentence spoken among them,
neither do I know that we met with so much as a sneer from one of them,
or any kind of insult, notwithstanding our appearance must have been singular to them.

I walked out a few other times during our stay in Paris for the benefit of fresh air,
but being poorly and sometimes low in mind,
and not having the advantage of the language to converse with the people,
I stayed much in my chamber, reading in my bible, which I had taken along with me,
to my great satisfaction.

Sixth-day, second of tenth month.
We left Paris and had a pretty agreeable journey through a fine,
well cultivated country to Lyons, upwards of three hundred miles,
where we stayed only one day.
Being desirous of getting on to Congenies,
where we understood there were a considerable number of professors with us;
we concluded to take boat and go down the Rhone, a very rapid river,
as being more agreeable than going by land;
the southern parts of France being much more hilly than those we had passed over.
On fifth-day we got our carriage on board a boat, set out early from Lyons,
and had a pretty fine run that day,
but it came on so rainy that the Rhone became dangerous for our little boat.
Next day in the afternoon we got out our carriage and went on again by land,
which proved a merciful deliverance, as we afterwards understood;
for the day after we left the Rhone a boat was lost
with a considerable number of people on board,
who were all drowned.

First-day, eleventh.
Through considerable fatigue and difficulty, we arrived at Congenies,
where we were kindly received by Lewis Majolier and his wife, with whom we put up.

Third-day, had an appointed meeting at this place with those under our name,
and although we found them in a very weak state,
and not much appearance of the Friend about them,
yet it proved through the renewal of holy help,
one of the most watering seasons I ever experienced in a meeting.
We found it necessary to use great deliberation in our communications,
in order to be at all understood,
so general a weeping prevailed at hearing the sound of the gospel in plain,
simple truths delivered among them.

Next day we went to Nismes about ten miles distant,
and visited one or two under our name there,
and the day following we went to a place called
St. Giles about fifteen miles from Nismes,
close on the sea, and said to be noted formerly for containing many protestants,
who suffered much, especially in the reign of Lewis XIV.
for their religious principles,
which occasioned a great dispersion of the inhabitants from that place,
and it has never recovered, being now only a small town, but the remains of a large city.
There are, however, at this time, a number who make some profession of our principles,
with whom we had a meeting, of which they seemed glad,
though it was not so open as the aforementioned one at Congenies.
We only stayed one day, and then returned to Congenies.

On first-day morning, attended meeting again at this place,
which was considerably larger than the first, and was also a time of favour.
After this meeting,
feeling my mind much exercised for the right advancement of Friends here,
I proposed a meeting to be held at some suitable time, which was acceded to,
and held this afternoon.
My mind was opened and enlarged, in laying their weak and disordered state before them,
and the consequences of having no rule, or order of discipline,
to unite them in supporting and holding up the testimonies of Friends.
Many seemed fully sensible of it,
and confessed in much brokenness that their deviations had been such,
that they had been only usurpers of the name of Friends.
This was truly an affecting opportunity, and after much time had been spent,
in which many with weeping lamented their situation,
it was proposed to hold a meeting next day, to try if they could get into some order,
which was agreed to, and in the evening several articles were drawn up,
in order to lay before them.

Second-day, a meeting for business was accordingly held,
when the aforementioned articles were laid before them.
They consisted of sundry heads of testimonies from the
book of Extracts of London Yearly Meeting,
accommodated as much as might be to their local and weak situation;
and it was proposed that all such among them,
as were willing and desirous of supporting these rules and testimonies,
should subscribe them and become united in the work.
This proved also a time of general weeping and brokenness,
and I could not forbear weeping with them.
I think about thirty of them stood up, and declared their willingness and desire,
to support and maintain these rules of discipline as proposed, and subscribed thereto.
Others confessed with tears that they felt too weak to engage at present,
and desired to know whether a door would be left open for them hereafter,
in case they should be better able to come in at a future day.
After a considerable time had been thus spent,
and they had appointed some of their number as overseers, etc., the meeting concluded,
and I believe many minds with ours, were greatly relieved:
may the Lord prosper the work in their hands to his own glory--
for I did believe in our passing along in this country,
that there was a precious seed in many places, that would at some future day be gathered.
May the Father of mercies bow down his gracious ear to the groanings thereof,
and hasten the day of its deliverance.

Fourth-day, twenty-first.
Apprehending myself clear of any further labour among these people,
Lewis Seebohm and I parted; he concluded to stay a few days longer about Congenies,
and then take his journey homewards through Switzerland,
and I proceeded towards Bordeaux, in order to look for a passage to some port in England.
This proved to be a very trying journey, it being between two and three hundred miles,
and I had only the company of a young man who
had lately been an officer in the French army,
and did not understand a word of English; but as he was so kind as to offer himself,
and it being the best shift I could then make for a pilot, I accepted his kind offer,
and very attentive and assisting he was to me, so far as we could understand each other,
which was chiefly by the help of a dictionary.
This was my tried situation for about eight days,
for meeting with some accident by the way,
by getting one of the axletrees of our carriage broken,
and also having some very stormy weather,
we did not reach Bordeaux until the twenty-eighth.

I happened to get lodgings with pretty orderly people near the Quay,
where I met with some who could speak English: I enquired for a passage to England,
but none seemed immediately to offer, and as it was now growing late in the fall season,
when a passage through the Bay of Biscay is reckoned dangerous,
I was under the necessity of taking one as soon as it offered,
or else to travel through the country six or seven hundred miles, to Calais or Dunkirk,
and this without an interpreter,
the young man aforementioned having left me and returned home.
Such was again my trying situation; alone,
far separated from all my dear friends and connections,
and in a great straight to know rightly what to do for the best:
Lord look down upon me in mercy; preserve and support me under these dispensations,
and be pleased to show me the way that I should go, for thou knowest me altogether,
and my desire to trust in thy eternal Providence!
O, withdraw not thy soul-animating presence, altogether from me,
but preserve me in these proving seasons, and keep me, O my God,
in every hour of temptation and trial,
that so I may not wound and become a reproach to thy holy cause, where my lot is cast,
nor make sorrow and repentance for my own soul; but that through thy holy aid, my God,
I may yet be enabled to sing thy praises on the banks of deliverance,
for unto Thee only is praise due, now and forevermore!

Sixth-day, thirtieth, I wrote letters to my dear wife and others in America.
It was nearly two weeks from this time before I
could engage a passage to answer my purpose,
but at length one offered by a Danish brig bound for the island of Gurnsey,
and I concluded to embrace this opportunity,
and cast myself entirely on that all-supporting
arm of Omnipotence which sustains the earth,
and rules the raging sea.

I may now remark,
that although much of the time I have been
waiting here has seemed almost like imprisonment,
and at times as if forsaken both of friends and the world,
yet as I have endeavoured to renew my trust and confidence in the eternal Arm,
blessed be his ever adorable name, through the renewing of his infinite,
love and mercy to my soul, my lonely room,
especially during the latter part of my stay here,
has been made to me as a pleasant museum,
wherein I have been favoured with precious openings into some
of the wonderful works both of nature and of grace,
to my own humble rejoicing in the eternal Providence,
and I was made a renewed believer therein.
O, my God, how unsearchable is thy wisdom,
how boundless and unfathomable are the riches of thy goodness and mercy;
thy ways are hid as in the great deep, and past finding out;
who shall refuse to adore thee, who art the everlasting Father and God over all!
Shall not all nations bow before thee, who hast made both the seas and the dry land,
and hast appointed unto them the bounds of their habitations,
for the Lord of Hosts remains to be thy name!

I have been made to see and believe the fall of Adam,
and how all his offspring have been and are affected by it;
and the means appointed for their redemption, and how it is to be effected,
I have seen and do most assuredly believe in.
O, well might the poor man mentioned in the gospel, cry out, "`Lord, I believe;
help thou mine unbelief.`"
O, who can disbelieve in Christ Jesus, the Saviour of the world! in his manhood,
sufferings and death therein! also in his divinity and eternal power;
the Redeemer and Saviour, in whom, as testified by the apostle,
dwells all the fulness of the Godhead bodily.
Tremble, O ye Deists, before Him, unto whom all judgment is committed,
that all men might honour him, even as the Father is honoured.
This is the Stone which was set at naught and rejected by you wise builders,
but truly it is elect of God and precious; and by Him all your buildings will be tried,
whether you will or not; although you may, in your wisdom,
carry your fabric to a prodigious height, like Nimrod,
yet in the day of his power when he shall come to inspect your work,
it shall fare no better than Nimrod`'s did.
O, tremble, lest confusion and everlasting disappointment be your portion!--But O,
my God, be thou pleased to strengthen and enable me from time to time,
to hold fast even unto the end, what thou hast now been pleased to renew in my soul,
and given me to believe most firmly.
Amen.

Sixth-day, thirteenth of eleventh month, I went on board the brig Mercurius,
Ole Nelson captain, and all the crew Danes; but such was his delay,
that although he was to have sailed a week or ten days before this time,
yet it was a full week after I got on board before they weighed anchor,
which I very much regretted, it being fine weather.

Sixth-day, twentieth.
Weighed anchor and fell down a little below the shipping,
which we did not effect without some apparent danger,
there being abundance of shipping in port and the current very rapid.
Next day we fell down a few leagues further,
and got a pilot on board in order to put to sea, when the wind turned against us,
and the weather became so rainy, that although we kept the pilot on board a full week,
we only made about twenty leagues from Bordeaux,
the wind continuing ahead until first-day, the thirteenth of twelfth month;
sometimes it blew so hard, that several ships drifted,
and others were driven from their anchors; one sloop sunk,
which we saw drifting near us with her topmast only above water,
but we could not learn whether the men were saved or lost:
this sight was very awful to me.

The wind coming fair for us, we weighed anchor and put to sea,
and had a fine run for about twenty-four hours.
There were two other passengers on board, one a Scotchman, the other an Irishman,
both lately from the English navy, and we all began to hope now for a speedy passage:
but, alas! for causes unknown to us,
how are all our pleasant prospects sometimes blasted;
for in the afternoon of the fourteenth, the wind shifted and came right against us,
and presently blew so strong that we were obliged to heave to,
with only our foresail spread,
and let her drive wheresoever the wind and waves would carry us.
This seemed to be only the beginning of our sorrows,
for from this time we had contrary winds almost constantly,
and at times such violent storms and high seas, that we were mightily tossed,
and so beaten by the heavy seas,
that we were in danger of being shattered to pieces by the violence of the waves;
at other times swallowed up in the belly of the mighty deep,
as though we were going down, never to rise again;
first driven near upon the French coast, which was very rocky and dangerous,
and then upon the English.
We several times saw the English land, but so mightily had we been driven about,
that our mariners hardly knew where we were, and our brig became so leaky,
that it was with much difficulty and hard labour,
that our poor seamen could free her of water by the pumps.

At length, our captain was determined, if possible,
to get into the first port we could make, and therefore on the twenty-eighth,
we stood in for the land, early in the morning,
and about eleven o`'clock we came so near in with the land,
that they thought they knew it to be Portland.
We were beginning to rejoice again in the prospect of soon getting into safe harbour,
when perhaps about two o`'clock in the afternoon, they concluded they were deceived,
and could not find any port before dark,
and we might be in danger of driving upon the land in the night,
therefore with fallen countenances were standing out to sea again,
when providentially a pilot espied us, and gave us a sign, which we returned,
and gladly received him on board, and that evening he brought us into Dartmouth bay,
where we were obliged to anchor for want of wind and tide: however,
they rose between three and four o`'clock in the morning, and weighed anchor again,
and after considerable exertion we got safe into the port of Dartmouth,
about twelve at noon, when I was favoured once more to set my foot on firm ground,
which I had not done before in more than forty days.

I was directly conducted to the house of Walter Prideaux, a very kind Friend,
and I think the only one under our name living in Dartmouth.
I met with a very kind reception at his house, although I was an entire stranger,
and had no credentials about me, having left my baggage on ship board.
I was truly glad and thankful in heart,
for the merciful deliverance vouchsafed to me from being entombed in the mighty deep,
though, blessed be God, in whom I was enabled to put my trust,
when the countenances of the mariners wore a dismal aspect,
and all hope of being saved was nearly gone, I never quite lost my confidence; no,
not for a moment, even in the greatest extremity of danger.

At one time in particular, when I verily thought we were going down to the bottom,
never more to rise,
being so deeply covered with the rolling surge that the
mighty roaring thereof ceased to sound in our ears,
and there was a profound silence in the ship;
even then did my mind feel so calm and quiet,
that I could not doubt of being clasped in the arms of everlasting love;
and I yielded to his blessed will, saying in secret, Lord,
if it be thy blessed will that this shall be my grave, I yield,
if I may but go down clasped in the arms of thine everlasting love,
or if thou art pleased to bring me safe to land again, I will surely sing thy praise,
I will tell of thy goodness in the congregation of thy people,
I will speak of thy wondrous works.

+++[+++Editor`'s Note: During the period of his tarriance on the continent of Europe,
the existence of a state of warfare, presented many obstacles to travelling with safety,
and exposed foreigners to much suspicion and many difficulties.
But his steady adherence to the religious principles which he professed,
his circumspect deportment,
and his uniform reliance upon the direction of heavenly wisdom,
made his way comparatively easy and procured him
the respect and esteem of all classes of people.
The voyage across the Bay of Biscay is often performed in less than a week,
but owing to a violent storm which they encountered,
and a succession of boisterous weather, they were forty-five days on the passage.

The crew of the vessel in which he embarked were principally Danes,
and during the first few days of the voyage,
seemed to vie with each other in wickedness and profanity,
neglecting the proper care of the ship,
and spending their time in drunkenness or gambling.
They treated Richard Jordan with great contumely and contempt,
scoffed at his religious life and serious demeanour, and even abused his person.
His situation was indeed a pitiable one: he was wholly at their mercy,
and from their negligence and unconcern about the vessel,
it seemed probable they would have a tedious passage.

They had not been long at sea, when the sky was overcast with clouds,
the atmosphere became dark and hazy, and a tempest arose,
during which the fury of contending elements seemed let loose upon them.
The waves were wrought up to an appalling height,
and the vessel heaved and tossed to such a degree,
as to induce them to fear she would be buried in the opening sea.

Their situation soon became apparently hopeless,
and the officers gave their wicked crew the
dreaded warning to "`prepare for a watery grave.`
Oh then, what a change was seen in their conduct.
Terrified at the prospect of the awful fate which awaited them,
smitten with remorse for their past wickedness and contempt of God,
they gave way to despair, and became almost incapable of managing the ship.
The helm was ordered to be lashed, and giving up all hope of safety,
they let her drive at the mercy of the winds and waves.
Amidst this general consternation, when all around him bespoke distress and terror,
Richard Jordan sat peacefully in the cabin, waiting in humble confidence upon the Lord.
His mind was calm and collected,
securely anchored on that Rock of Ages which no storms can move, no tempests overturn.

As shipwreck seemed, in all human probability, to be inevitable,
he took from a trunk his certificates and a few other valuable documents,
and fastened them around him, that in the event of his body being afterwards found,
it might be known and the papers forwarded to his friends.
But although he made these arrangements, he did not, during the whole scene,
entirely lose his confidence.
The captain, awakened from his sensuality and wickedness,
and tremblingly alive to the doom which seemed to be impending,
betook himself to the cabin, and seconded by his anxious crew,
besought Richard Jordon to implore for them the mercy and protection of that Being,
whose power they had so lately contemned, nay,
whose very existence they had impiously denied.
He informed them in a few words,
that the spirit of availing prayer was not at his command:
but after waiting for a considerable time in solemn silence,
he was permitted to approach the throne of grace in reverent vocal supplication.
This religious service seemed to be in some degree blessed to them;
they were humbled into contrition, and became more composed;
their conduct towards him was now reversed;
every one seemed desirous to do him some kindness,
and so sensible were they that the Divine presence was near to preserve and support him,
that all were anxious to get as close to him as possible.
Their exertions in managing the vessel were renewed,
but owing to the continuance of boisterous and foggy weather,
they had lost their reckoning, and provisions running short, they were put on allowance;
and although the violence of the storm soon after abated,
yet the probability of reaching land before their
stores were exhausted became very doubtful.
The vessel was so much injured that she began to take in water very fast,
and the pumps had to be constantly worked to keep her free.
Discouraging as the prospect before them appeared,
such was the confidence and faith with which Richard Jordan`'s mind was replenished,
that he told the captain it was his belief they should yet be brought safely into port,
without the loss of a life.

In a few days after this,
when almost the last portions of bread and water were served out, they descried land,
and soon after entered the harbour of Dartmouth.
His gratitude for this happy deliverance from imminent danger,
and his release from long confinement in a vessel,
which a variety of circumstances rendered extremely unpleasant, may readily be conceived.
He appointed a public meeting for Divine worship in the town,
to which the captain and some of the crew came,
and it proved a memorable and humbling opportunity to many present.^
footnote:[From A Biographical Memoir of Richard Jordan]]

Hearing there was to be a quarterly meeting held next day at Kingsbridge,
about twelve miles from this place, I felt very desirous of being at it,
and therefore took horse, though perhaps after sunset,
being accompanied by George Pri-deaux, a kind young man,
and nephew to the above mentioned Friend.
We got to Kingsbridge about eight o`'clock, though it was very dark and rainy,
and the country very mountainous, and being clear of wood,
I thought in the evening the hills somewhat
resembled the mighty waves in the Bay of Biscay.
The young man took me to his father`'s house,
where I was also very kindly received and agreeably accommodated.

Next day I attended the quarterly meeting, which though small, was a blessed time,
and I trust will not soon be forgotten by many of us then present,
but long had in remembrance as a fresh memorial
of the Lord`'s love and mercy to our souls.

Fifth-day, thirty-first, was their week-day meeting at this place, which I attended,
it was also a precious opportunity, blessed be the Lord,
who causeth all things to work together for good to them that love and fear him.

Sixth-day, first of first month, 1802.
Finding myself much reduced and exhausted in my nature,
I have concluded to accept the kind invitation of these dear Friends, where I lodge,
to stay with them awhile, and endeavour to recruit,
before I proceed further on my journey,
though I have attended meetings here constantly as they come in course,
both on first and week-days.

Fourth-day, thirteenth, I went to a monthly meeting at Modbury,
where I sat the meeting through in peaceful silence,
and returned again to Kingsbridge in the evening.
First-day, twenty-fourth, this morning at meeting I was awfully engaged,
and my heart enlarged in solemn prayer and supplication
for all my home Friends and their meetings in general,
that the blessing of preservation might be vouchsafed;
as also for all those engaged in like manner with
myself to leave their all for the gospel`'s sake,
and that the great and glorious work thereof might be
carried on to the praise of the great name.

Second-day, twenty-fifth, went to Dartmouth,
and next evening had a large public meeting there, made up of a mixed multitude,
who behaved well while many gospel truths were delivered to them,
with which they appeared to be well satisfied,
and the meeting concluded in a solemn manner, after it had held about three hours;
a number of the people, as I understood afterwards, were desirous of another meeting.
I also went to see the ship in which I had witnessed so marvellous a deliverance,
and found her in dock, and many workmen were employed in repairing her,
for so much was she wrecked that I was informed,
she narrowly escaped being condemned as not sea-worthy,
the captain and crew seemed much rejoiced to see me again,

Fifth-day, fourth of second month, went to Modbury again,
and stayed until second-day morning, in which time I attended three meetings,
all times of favour, returned to Kingsbridge,
and attended a monthly meeting on fourth-day, for the Friends of Plymouth, Modbury,
Kingsbridge and Dartmouth, which was also a time of favour.

Fifth-day, eleventh, in the evening had a large public meeting with the town`'s people,
which was attended with great solemnity, many gospel truths were delivered to them,
which seemed to be received with joy and gladness,
and I did believe there were many seeking minds amongst them.
I now began to look towards leaving Kingsbridge,
a place which I trust will not soon be forgotten by me,
but long be remembered with gratitude for the many
favours which I was made partaker of while there,
I had proposed setting off on the morrow,
but being a little unwell and not feeling quite clear in my mind,
I stayed until first-day,
and had another precious opportunity with Friends in the morning,
and feeling my mind again drawn towards the townspeople,
I requested Friends to inform them that the doors would be opened in the afternoon,
for all that were disposed to come, which was done,
and they came together in such abundance, that the house could not contain them,
and blessed be the Lord,
this was through the manifestation of his goodness and power a crowned opportunity,
which I humbly trust will not soon be forgotten.
Many of these dear people, who could not get seats,
I believe stood quietly near three hours,
such was the solemnity that prevailed in this large meeting:
may the Lord have all the praise, to whom alone it is due, now and forevermore.
Amen.

Second-day, fifteenth,
after an affectionate and solemn farewell with
the dear children of this agreeable family,
where I have been abundantly cared for in the time of need,
and having the company of their dear father and mother, George and Anna Prideaux,
I left Kingsbridge, and rode to Plymouth, where I put up with James Fox,
and on fourth-day attended a meeting of Friends at this place, in which I was silent.
First-day, twenty-first, I attended two meetings at the same place,
in which I was again raised up in the authority of Truth,
to preach the gospel to a pretty large audience, and felt considerably relieved.
Fourth-day, attended the week-day meeting, which was a solemn time,
wherein the testimony went forth in a close searching manner.

First-day, first of third month, in the morning enlarged in testimony;
in the afternoon silent: stayed their week-day meeting again,
and was considerably enlarged in testimony,
but still I do not feel clear to leave Plymouth;
Lord preserve me in the right way and give me to understand thy dispensations towards me,
and be pleased to grant me renewals of strength and patience, from time to time,
to abide them all.

First-day, eighth.
Again attended the fore and afternoon meetings, but was shut up throughout both,
in deep inward exercise.
Their monthly meeting was held here this week, which I also attended,
and blessed be the Lord, the alone Helper of his people,
he was pleased to give the remnant of the deeply suffering souls,
to drink of living water, to their humble rejoicing in his salvation.
Seventh-day, feeling clear of this place, and having the company of George Prideaux,
I set out for Cornwall, and took the following meetings; viz. Germains, Looe, Liskeard,
Aristoll, and Mavegessey;
in the two last I was opened in a good degree of clearness and gospel authority,
I humbly trust to the edification of many as well as the peace of my own mind.
And O, may I be enabled to keep that testimony, "`he openeth and no man shutteth,
and shutteth and no man openeth.`"
Ah! when he shutteth, who dare attempt to open; and O,
may I be preserved from being numbered among those that "`compass themselves about
with sparks of their own kindling,`" whose portion is to "`lie down in sorrow.`"

Sixth-day, reached Falmouth,
and on first-day attended both the meetings of Friends at this place;
in the afternoon had a favoured time in testimony,
this being only the third meeting out of seven since we left Plymouth,
in which I have been able to open my mouth in public.
Fourth-day, I sat the week-day meeting through in deep silent exercise;
after meeting went to see a woman Friend who was very ill,
and perhaps near her end in this world.
I had a comfortable opportunity by her bedside,
which was also a precious season to some others present: after this,
visited another family or two, and returned to my lodgings.

Fifth-day, went to Perran-wharf, and attended a small meeting of Friends there,
which was a blessed time;
in the evening returned to Falmouth-- and feeling considerably unwell,
I continued mostly at my lodgings until first-day,
when I attended the meeting here again in the morning,
and went to Perran-wharf in the afternoon, and attended theirs,
both to pretty good satisfaction.
Spent a little time with Friends here, returned to Falmouth,
and was at their monthly meeting on fourth-day, thirty-first,
and set out the same afternoon for the Land`'s End, taking the following meetings, viz:
Hilstone, a public meeting at the same place, Marazion, and so to Redruth,
and attended both their meetings on first-day.

Next day returned to Falmouth, and fourth-day, the seventh of fourth month,
attended the quarterly meeting there, which was a deeply exercising time,
both in silence and in public labour; but in the conclusion I felt considerable relief,
though I did not yet seem quite clear in leaving the place,
and therefore I endeavoured patiently to wait the Lord`'s time,
being very desirous of seeing my way out of places, as well as into them.
After this meeting I visited several Friends,
and attended their two meetings again on first-day,
which were times of deep inward exercise, though I was opened a little in the afternoon.
O Lord, when shall I be released from this almost constant weight and burden,
by which my poor soul is so much borne down and afflicted in this place.
Not feeling yet liberated, I was afraid to move under the cloud,
and therefore endeavoured to wait in the patience a little longer,
if happily I might be favoured to find a peaceful retreat.
So I stayed another meeting with them on fourth-day, fourteenth,
where I was enlarged in a particularly close searching testimony to some states,
which perhaps are not often reached by instruments,
the meeting concluded in solemn prayer and supplication;
many minds seemed to be humbled-- and blessed be the Lord,
at the conclusion of this meeting I felt quite relieved and unburdened in my spirit;
praised be his glorious name forever.

We took our solemn leave of Friends here, and went to Perran-wharf to dinner,
and there being a large iron-foundry, etc. here,
we had a meeting with the people in the evening, which was a highly favoured opportunity.
Next day went on our way back to Plymouth and reached it the day following, viz:
sixth-day, the sixteenth.

First-day, attended the fore and afternoon meetings,
which were times of deep wading and close exercise without much relief:
here also I seemed to be kept in a state of imprisonment,
(as I had been at Falmouth) until the twenty-ninth,
in which time I had one public meeting, and attended sundry meetings with Friends,
and much of the time I was so covered and borne down under inward exercise and suffering,
that I ate but little pleasant bread; but blessed be the Lord,
as I endeavoured patiently tc wait his time,
he was pleased to grant a clear and satisfactory release,
so that at the conclusion of a meeting the day before I set out,
the joyful intimation was given, "`thou hast encompassed this mountain long enough.`"
I received it with heartfelt gratitude and joy, and left the place quite relieved.
Next day got to Exeter and stayed over their two meetings on first-day,
which were on the whole solid instructive opportunities.

Third-day, fourth of fifth month, I got to Chard,
and had a precious meeting with a few Friends there the same evening;
next day reached Compton, and the day following attended a week-day meeting there,
which was made up chiefly of Thomas Thompson`'s scholars;
this was also a solid opportunity.
I got to Marnhull the same evening, where I met with dear Deborah Darby,
and we were truly gladdened in seeing each other, as also her old companion Rebecca Byrd,
who now resides here with her husband.
First-day, we attended two meetings, in both of which I was silent.
Third-day, eleventh, attended a monthly meeting at Sherburne in which I was also silent,
but dear Deborah Darby was set at liberty in an affecting manner,
much to the relief of my mind.

Fourth-day, twelfth, attended the week-day meeting at Marnhull,
where I was opened in a short testimony to the relief of my own mind; and on fifth-day,
accompanied by William Rawes, junior, and his wife, I set out for London,
distant about one hundred and twenty miles.
I had a very agreeable journey with these two valuable Friends,
who were very kind caretakers, arriving in London next afternoon,
where I was again kindly received by my old friends Josiah Messer and wife, of Holborn.

First-day, sixteenth.
Attended two meetings at Westminster; second-day,
two sittings of the yearly meeting of ministers and elders,
and another sitting of the same on third-day morning, at Grace Church street,
most of which were solid, good opportunities,
and Friends seemed glad to see me returned from so trying and
perilous a journey as that on the continent of Europe.

Fourth-day, nineteenth.
The yearly meeting for business opened, which was a solid opportunity,
as were the sittings next day.
Sixth-day, all the meeting-houses of Friends in the city were opened for worship;
I attended that at Grace Church street, which was a good time.
The yearly meeting proceeded with its business until first-day,
when the meeting houses were again opened for worship, both in the fore and afternoon.
Second and third days, the yearly meeting continued its sittings,
and on fourth-day meetings for worship were held, I attended at Southwark meeting-house,
which was an exercising time to me, but I was favoured to relieve my mind,
so that I left it peacefully; in the afternoon the yearly meeting resumed its business.
Fifth-day, soon after the meeting gathered,
I proposed a visit to our women Friends in their apartment, which was readily acceded to;
it proved a precious opportunity, and the day closed peacefully; blessed be the Lord.

Sixth-day morning, the twenty-eighth.
The yearly meeting for business concluded in a solid manner,
and in the afternoon the meeting of ministers and elders met,
which was a time of renewed favour,
such as I trust will long be had in grateful remembrance;
in this concluding opportunity I was permitted
to be as it were numbered among the princes;
blessed be the Lord,
who causeth all things to work together for good to them that
love and fear him--sanctifying their toils and exercises,
at times, to their own peace and rejoicing.

First-day, the thirtieth.
I attended Devonshire-house meeting,
wherein I was enlarged in testimony on the fall of man,
also on the subject of his redemption and restoration
to the favour of God through Jesus Christ:
this was a solemn time, the meeting was large,
and many not professing with us were present,
but one stood up in the meeting (who was in profession with us,) and
expressed something like lessening the validity and weight of this doctrine.
I had felt that spirit at work in many places,
and in some it had openly made its appearance.
I was also engaged in prayer and supplication in this meeting,
and near the conclusion was concerned to stand forth and testify,
that I had travelled in most parts of North America,
and also in most places in Europe where Friends were scattered,
and that we were uniformly as a religious body, of the same principles,
and held forth the same doctrines, as I had done in that meeting,
or words to this import.
The meeting seemed clothed with a profound solemnity, and so concluded,
and I went my way rejoicing, believing that many were made to rejoice with me,
in the Hope of Israel; blessed be the Lord who gave the victory this day.
In the afternoon I attended the meeting at Grace Church street,
where I met with my friend Joseph Cloud, from North America.

Second-day, thirty-first.
The dear family with whom I sojourn removed out of the city to Hampstead,
and took me with them, which I find a pleasant retreat from the noise of London.
Returned to the city on fifth-day, and attended the week-day meeting at Westminster.
Sixth and seventh-day, stayed mostly about Hampstead, and wrote letters to America.

First-day, sixth.
I attended the two meetings of Friends at Tottenham,
which were solid opportunities through the fresh extendings of holy help.
Fourth-day attended the monthly meeting of Grace Church street,
and next day the meeting at Westminster.
First-day, was at the meetings of Westminster again, in which I was silent,
as I had been in the week-day meeting preceding.
Second-day, fourteenth, attended the morning meeting of ministers and elders,
where I communicated to Friends my apprehension of having
pretty nearly fulfilled my prospects in coming to Europe,
and my expectation of soon being at liberty to return to my own country;
this was a blessed opportunity,
and several Friends were appointed to prepare a certificate for me.

Third-day, fifteenth, was at a monthly meeting at Southwark,
and next day attended the meeting at Grace Church street,
in which I was raised up and enlarged in Gospel authority,
and matter flowed freely like precious oil,
to the humbling and contriting of many souls before the Lord;
it was a blessed watering time,
and concluded in solemn supplication by our dear friend Sarah Lynes.
Fifth-day, I was at Westminster monthly meeting, which was a time of favour.
First-day attended both the meetings at Westminster again,
in which I had considerable communication,
but did not feel so comfortable after these meetings as
I had done in some of the aforementioned ones,
but perhaps it is better for me.
Lord, preserve me both in heights and in depths,
so that nothing may be able to separate me from thy love,
nor shake my confidence in thee.

Fourth-day, twenty-third.
Attended an adjournment of the monthly meeting at Grace Church street;
fifth-day went to Radcliff, and on sixth-day was at a school meeting at Islington,
in all of which I was silent except the last, which was a pretty open time,
and I believe was to general satisfaction.

First-day, twenty-seventh.
Went to the meetings at Peel, which were both solid, good opportunities.
Second-day, I attended the quarterly meeting of ministers and elders,
and on third and fourth days, a large quarterly meeting for business,
in the first sitting of which, while men and women were together,
I was enlarged in testimony, with clearness and good authority,
to my own humble admiration;
the opportunity concluded with solemn prayer and
thanksgiving to the blessed Father of mercies,
who had been pleased to cover us this day as with the canopy of his love,
under a renewed sense whereof many souls with my own,
were given to rejoice in his salvation,
and I humbly trust that this day will long be gratefully remembered by many of us.

Fifth-day, first of seventh month.
I attended Westminster meeting, where was a marriage,
which drew a number of people not professing with us,
among whom were several French noblemen,
one of them a member of the National Assembly at Paris;
this I think was one of the most solid opportunities
that I ever experienced on such an occasion:
this great man from France was introduced to me after meeting,
and seemed sensibly affected with the favours of the day,
the service of which fell chiefly on Mary Dudley and myself.

First-day, fourth.
I attended a large meeting at Devonshire house in the forenoon, where was a burial;
I had considerable communication, which I hope was of some use,
but the solemnity of the meeting was much interrupted
by an unseasonable and unsanctified appearance,
yet it ended better than I expected:
in the afternoon I attended Grace Church street meeting, which was silent.
Third-day, sixth, attended a monthly meeting at Devonshire house, which,
through the renewed extending of holy help, was a memorable time.
Fifth-day, was at a week-day meeting at Radcliff, which was also a time of favour.

First-day, in the morning, attended Westminster meeting;
in the evening a large public meeting appointed by Mary Dudley at Devonshire house,
and on second-day was at the morning meeting of ministers and elders,
where I obtained a certificate addressed to my friends at home,
purporting unity with me in my travels in Europe.
I spent the remaining part of this week among Friends in social visits,
except attending a monthly meeting at Westminster;
and on first-day morning I attended the meeting at Grace Church street,
where I had a solemn farewell opportunity.
In the afternoon I attended Westminster meeting,
where I suppose the expectations of many were raised,
seeing this was to be my last opportunity with them,
and it being the meeting within the limits of
which I had resided during my stay in London,
but they were disappointed, for I was silent, except near the conclusion I told them,
that in looking over the many exercises and baptizing
seasons which I had passed through among them,
I felt quite clear and relieved;
and with very little addition took my solemn leave of them, and bid them a long farewell;
this seemed to occasion considerable solemnity, and opened a door for dear Mary Dudley,
who had a favoured opportunity.

I returned to Hampstead that evening,
and next day attended a school meeting at Islington, to satisfaction.
Third and fourth days rather unwell, and stayed mostly at my lodgings.
On fifth-day, having the company of two young Friends of London,
I took leave of my Friends at Hampstead, and got to Colebrookdale on seventh-day;
stayed over first-day, and attended their two meetings,
which were highly favoured opportunities, wherein truth was eminently exalted over all,
and many souls with mine, were comforted and refreshed and praised the Lord.
We were also favoured with a precious opportunity in the evening,
at the house of Richard Reynolds, with his family,
and a number of young Friends who came in, and the evening closed peacefully.

On third-day reached Warrington in time to attend their meeting the same morning,
which was a blessed watering opportunity, especially with some of the younger class;
we also had a good opportunity with some young people
who came to see us at the house where we dined,
and the same evening we got peacefully into Liverpool,
where we were again kindly received at the house of our dear friend Robert Benson.

Fifth-day I attended their week-day meeting, and after a time of close exercise,
Truth broke forth to our comfort and rejoicing; blessed be the Lord.
Here I also received agreeable accounts from my dear wife,
which was cause of thankfulness and gratitude.

First-day, first of eighth month, I attended two meetings here,
which were baptising seasons, and the day closed peacefully.
I have been very much tried in my mind for two or three days past,
having been on board of several fine ships in order to see for a passage to America,
but all has seemed to close up respecting it at present,
so that I could not see my way to engage a passage in any of them.
Lord, look down upon me in mercy, and preserve me in patience,
until thou art pleased to open the way for me according to thy own blessed counsel.
Fourth-day, Josiah Messer, his wife and two daughters, from London,
called here and spent two or three days very agreeably with me,
they being on a journey to the north, to visit their relations.
Fifth-day, attended the week-day meeting, where I could see no way for me,
but to abide in my tent, in inward exercise.
I stayed in and about Liverpool until first-day, and attended their two meetings again,
when, blessed be the Lord, I was enabled, in a good degree to cast off my burden,
with which I have been so much borne down, and pressed in spirit for several days,
in this place, and my mind now felt more calm and quiet.

Third-day, tenth.
The half year`'s meeting in Wales, which is to be held this month,
having engaged my attention for several days,
after some very close thinking on the subject,
I have believed it safer for me to resign myself to the prospect of attending it;
and accordingly I set out this afternoon; crossed the river Mersey from Liverpool,
and took our journey by the way of Chester, where we arrived the same evening.
Their meeting being next day we attended it, and it was a time of favour,
tending to the encouragement of the little few who reside here,
as well as to the comfort of our own minds.

We lodged another night in Chester, and on fifth-day got to Shrewsbury,
being upwards of forty miles.
Sixth-day, had an appointed meeting with Friends of this place,
which was a blessed watering time,
and that evening had a very agreeable ride to Colebrookdale.
First-day, fifteenth,
we attended a meeting at a place called the New Dale in the morning, four miles distant;
returned to their meeting here in the afternoon, which was large,
owing to the coming in of many not professing with us.
I expected during a great part of this meeting
that I should have sat it through in silence,
as I had done that in the morning, but at length,
when I began to be apprehensive that it was nearly time for the meeting to conclude,
I stood up with a few words, and, as I expressed them, life seemed to increase, until,
blessed be the Lord, it was exalted to our humble admiration,
and many of us were renewedly enabled to bow, and worship, and praise Him,
who lives forever and ever, and we went on our way rejoicing;
thus the day again closed peacefully.

Third-day, attended a week-day meeting at the old Dale,
and in the evening a meeting of ministers and elders at the same place,
and next day a monthly meeting at the New Dale, all of which were, I humbly trust,
profitable and instructive opportunities to me and many more.

Fifth-day, nineteenth, we left Colebrookdale and reached Leominster,
where we put up with William Young, a very ancient and valuable Friend,
who received us very kindly; we stayed in and about this town until first-day,
and attended their meetings to good satisfaction.
Second-day, we rode to the Hay in South Wales,
where the half yearly meeting is to be held; here we met with dear Deborah Darby again,
who had not been home since the yearly meeting in London.

Third-day, the twenty-fourth; at eight o`'clock in the morning,
the select meeting was held; at eleven, a public meeting, and at four in the afternoon,
the meeting for discipline opened, which continued by adjournments until next afternoon,
and in the evening a large public meeting was held.
Sundry Friends from London,
and many from other parts of England attended this half year`'s meeting,
and on the whole, the several opportunities in the course thereof, were times of favour,
and we left the place with thankful hearts.

Fifth-day, twenty-sixth,
Deborah Darby having appointed a public meeting to be
held this morning about fourteen miles from this place,
on our way to Leominster, and another in the evening at Leominster, I attended them both,
and they proved to be seasons of favour; the day closed peacefully.
Sixth-day, Deborah Darby and we parted, she went towards Worcester,
and we back towards Shrewsbury.
We lodged at an inn at Church Stratton, and next morning got to Shrewsbury,
having the company of several Friends;
we stayed over first-day and attended their meeting in the forenoon,
and in the afternoon had a pretty large public meeting, both of which were solid,
good opportunities, and tended much to the relief of my mind.
Second-day morning we took an affectionate leave of these Friends,
and set out for Chester, where we arrived in the evening;
next day had a public meeting there, which was a solid good time;
and in the evening had a precious opportunity at
our lodgings with some newly convinced persons.

Next day being the first of ninth month, we got well to Liverpool,
where I met with my dear friend William Jackson from America,
who had just before arrived, with Mary Jefferis,
after a passage of thirty-eight days from New York; our meeting was truly rejoicing.

Fifth-day, the second, we all attended the week-day meeting here,
which was to us a day of high favour;
blessed be the Lord our God who comforteth those that are cast down,
he was pleased to comfort our souls in this meeting.
Sixth and seventh days, William Jackson and I spent most of these two days together,
and attended the two meetings of Friends next day, which were large,
especially that in the afternoon, many not professing with us coming in;
both these meetings tended much to the relief of my mind.
In the last I had something like a solemn farewell to
many whose faces I was to see no more,
and next day I felt freedom to engage my passage in a ship called the India,
Captain Hathaway, bound for Philadelphia; this day dear William Jackson and I parted,
he going on his journey towards Cheshire,
I stayed in town and went about preparing for my voyage.

Fourth-day, accompanied by Isaac Hadwin and wife,
took passage in a canal boat to Writtington, about twenty-one miles from Liverpool,
to see dear Robert Benson and his family, and arrived there that evening;
next day attended their week-day meeting, which was a blessed relieving opportunity;
spent the remainder of the day with this valuable family,
and in the evening before we retired to bed, divine good being renewed,
we were favoured with another blessed opportunity to
the comfort and consolation of our souls,
and the great name was magnified and praised, who alone is worthy forever.

Next morning early we took our solemn leave of these dear Friends,
and returned to Liverpool, and first-day, twelfth, I attended both the meetings here:
in the afternoon I was raised up,
and enabled to bear a testimony on the subject of the first and second commandments,
in an affecting manner, and the meeting concluded with solemn prayer.
I left it under a fresh sense of divine favour, and went to my lodgings,
and this evening a number of Friends coming in,
we had another heart-tendering opportunity.

Second-day, thirteenth, I went to the customhouse and gave in my name, nativity,
occupation, what country I was last from, where bound,
the ship`'s name in which I was to sail, and the persons to whom I was known here.
I then obtained a permit to leave the country and go home.--Well,
if my blessed and heavenly Master doth but go along with me,
and carry me safely and peacefully there, I believe all the difficulties,
dangers and hardships which have attended me in this journey,
will weigh lighter than vanity in comparison with his superintending care,
love and mercy to my soul; eternally blessed be his name.

Third-day, attended the burial of a Friend,
on which occasion a large meeting was held at the meeting-house, which was a solid time,
and I believe one of renewed visitation and warning to many.
Fifth-day being meeting-day in course,
and I not having had any warning to go on ship board, I ventured to attend the meeting,
which proved to be a blessed opportunity,
the day closed peacefully and I seem only waiting the ship`'s time.
Seventh-day, eighteenth, the eight passengers who are to go in the cabin,
and sundry others in the steerage were ordered on board,
and now I took my last leave of the dear Friends where I lodged,
and a number of others who came to see me on the occasion,
and got onboard between ten and eleven in the morning: the ship was very soon under way,
and having a fine breeze, we presently got out of the mouth of the river Mersey;
the breeze gradually increasing, and our ship being a fast sailer,
we soon left all behind that came out with us, though there were many fine ships,
some of which came out before us,
but the wind dying away in the evening we were almost becalmed,
and continued so most of the night;
all the passengers continue pretty free from sea-sickness.

Next day in the afternoon a fine breeze sprang up,
and our sailing increased to seven knots and a half per hour,
and we seem now to be fast bidding adieu to Europe.
I leave it with a peaceful mind,
and many of its inhabitants will be long remembered in gospel affection by me,
if I am continued in this state of being.
I feel that I have much to be thankful for to the great Author of my being,
who by his all-supporting arm of Omnipotence,
hath carried me through many heights and depths,
and covered my head in the day of battle,
and hath often enabled me to set up my Ebenezer, and say,
"`hitherto the Lord hath helped me.`"
He hath been with me in perils by land, perils by sea, and perils among false brethren,
and hath delivered me from the power of them all; yea,
when the proud waves roared tremendously and essayed to swallow me up,
then was his voice experienced to be mightier than the noise of many waters, yea,
than the mighty waves of the sea.
I was favoured with a good passage, good accommodations, a kind captain,
and all the crew civil and respectful towards me.
