[#testimony, short="Testimony of Haddonfield Monthly Meeting"]
== Testimony of Haddonfield Monthly Meeting, concerning our beloved friend Richard Jordan, deceased.

It appears from memorandums which he has left, that his parents,
Joseph and Patience Jordan, were members of our religious Society.
His father being much from home on business,
and his mother dying whilst he was quite young, his education was so far neglected,
that he was but a few times at a religious meeting of Friends,
until he was twelve years old.
But the watchful care and unspeakable mercy of the Lord,
was manifested in the tendering visitations of his holy Spirit,
exciting awful impressions on his mind respecting a future state,
and raising at times fervent desires after an inheritance
among the spirits of the sanctified in heaven,
when time to him should be no longer.
But not keeping close to this religious exercise,
the tendering sense of divine goodness became much effaced,
his mind alienated from the source of all true comfort,
and his feet with avidity were tracing the paths of temptation and lying vanities.
In this condition it pleased the Shepherd of Israel renewedly to
bring him under a deep sense of judgment and condemnation for sin;
and as he patiently and humbly abode under this refining baptism,
though at times tempted to give up all hope of ever
attaining to a state of acceptance and peace,
he was, through great mercy,
enabled to surrender himself into the hands of his all-sufficient Redeemer,
and brought into a living and heartfelt experience of reconciliation to God,
through Jesus Christ our Lord.

Being married and settled in North Carolina,
and having passed through many deep and various baptisms,
with an awful impression that he was called to the ministry,
and at times a sensible feeling of the divine hand putting him forth therein,
which he strove to avoid; he was, in the twenty-fifth year of his age,
enabled to resign himself to the disposal of the blessed Head of the church,
and strengthened to express a few words in a small meeting of Friends,
which yielded indescribable peace to his hitherto oppressed and afflicted soul.
His appearances in the ministry were for a long time small, and not frequent,
his mind being covered with a fear and dread lest he should shoot out into branches,
and not truly know an establishment in the root of immortal life.
He kept much at home, except attending his own yearly meeting,
and some neighbouring meetings in Virginia,
and also travelling on foot in religious visits to some places in North Carolina.

Being faithful in, the little, his qualification for further services became enlarged;
and feeling a religious concern to visit the meetings
of Friends in the northern and eastern states,
he opened the same to his Friends, and in the third month, 1797,
obtained certificates of their unity,
from the monthly and quarterly meetings of which he was a member.
His visit to those parts was attended with the savour of divine life,
and as a messenger of Christ,
his fervent labours in the ministry were made effectual to the quickening of many minds,
and to the real edification of the church.
Some time after his return from this journey,
his mind being often greatly reduced and humbled,
a prospect of extensive religious service in
foreign parts was weightily spread before him,
which, through holy help, he was enabled to give up to; and in the second month, 1800,
after receiving the requisite certificates,
he left his residence with a humbling sense of the Lord`'s hand upon him;
and soon after embarked at New York, in a vessel bound for England.
Being strengthened to complete his visit with
much acceptance and in the unity of his Friends,
to most of the meetings in Great Britain and Ireland,
and also to several parts of the continent of Europe,
where he experienced many remarkable preservations,
and signal interpositions of Divine Providence,
he returned to America in the tenth month, 1802.
After the lapse of several months,
believing himself called upon to reside some time in Connecticut,
he removed with his family to Hartford, in that state, in the year 1804.

Whilst an inhabitant there, he paid several religious visits to distant meetings;
and in 1809, being satisfied that it would be right for him to leave those parts,
and again change his residence, he spread the same before his friends,
who after due deliberation, signified their unity with his prospect,
and he accordingly came and settled within the limits of this monthly meeting.
His time for several years was much occupied in
attending to the services of our religious Society,
and in performing some religious visits.
In the management of his temporal affairs,
he was remarkably cautious of entering into engagements or contracting debts,
lest through any unforeseen occurrence,
an honourable and punctual discharge of them might be improperly delayed or prevented,
and a blemish be thereby brought upon the cause of Truth,
which to him was more precious than any earthly possession:
this guarded circumspection was so strictly maintained, that, making his wants few,
he rarely had any unsettled accounts on hand.

Being devoted to the service of his heavenly Master,
he was made an able minister of the gospel;
and though at times in the beginning of his communications,
he might seem to the superficial observer, to move on in weakness,
yet to the truly gathered spirits he was felt to be exercised
in watchful care not to proceed faster or further,
than as the great Shepherd of the sheep was pleased to lead along,
in the openings of the divine gift.
His reverent humble waiting, and deep exercise of spirit,
in his silent sitting in our meetings,
were instructive and at times had a reaching effect upon the minds of those around him;
and when put forth to speak to the people,
it was not with enticing words of man`'s wisdom,
but in demonstration of the Spirit and of power; baptizing the audience,
and clearly opening to individuals their states and conditions,
showing with indubitable certainty,
that the pathway of peace and salvation was through the
effectual operation of the Cross of our Lord Jesus Christ.

In the third month, 1825, he met with a close trial in the death of his beloved wife,
which he bore with exemplary resignation.

In the eighth month, 1826, returning from a visit to Salem quarterly meeting,
held at Woodbury,
and conversing with a Friend in allusion to a visit he
had lately made to Friends in Philadelphia,
he expressed the great peace and satisfaction he felt in recurring to it,
and emphatically said that it would be his last visit;
and appeared settled in the conviction that the happy period
of his release from the trials of time was near at hand.
In a few days after this, he was taken unwell; and in this his last illness,
which continued about two months,
he had much conversation with several of his dear and intimate Friends,
upon the present state of our religious Society, earnestly declaring as his belief,
that all those who were led by the Spirit of truth,
would feel themselves constrained to acknowledge
all that is recorded in the holy Scriptures,
concerning the coming, the sufferings, and offices of our Lord and Saviour Jesus Christ,
as he appeared in the flesh at Jerusalem.
He several times declared as his firm conviction at that awful period,
that however painful the present state of things
was to the sincere followers of the Lamb,
yet he fully believed it would be made the means
of purifying the Society of much of its dross,
and that such as stood faithful in their allegiance to Christ,
would be deepened by it in the life of religion.
He had seen (he said) that the Lord would take the cause into his own hand,
and none should be able to hinder him: that those of this Society,
who had been highly favoured, but who had turned their backs and forsaken Him,
would be cast out, and others brought in,
who would stand for the honour of his great name, and for his cause in the earth.

On the 16th of the ninth month, a Friend calling to see him,
he intimated that he thought his recovery very doubtful, considering his age,
and the great prostration of his strength; but he several times remarked,
that he had no will but the Lord`'s will.
He expressed with much feeling and deep sorrow, his concern for those, who,
by giving way to their creaturely wisdom, and carnal reasoning,
have departed from the Christian faith.
With much emphasis he said, "`Oh, what will those men do,
that deny the divinity of our Lord and Saviour Jesus Christ!
what refuge will they have at such a time as this;
on a sick bed--O, what will become of them!`"--Once he said,
"`I would not be in their state for any thing in the world.`"
He intimated that during this sickness, he had had much opportunity for reflection,
both by day and by night,
and he had thought much upon the awful state of those people that deny the Lord,
and the only hope of salvation, which, added he, is by the mercy of God,
through the merits and the grace of our Lord Jesus Christ.
Then he said with much emphasis, "`My hope, my only hope for salvation,
is in the mercy of God, through the merits of Jesus Christ:`" these,
or words nearly similar, he repeated several times during the course of the conversation.

He enlarged very instructively on the ground of this his hope,
and the great stay and comfort it was to his mind:--`" Oh,`" said he,
"`I would not give this hope in the mercy of God, through Jesus Christ,
for the whole world.`"
He then proceeded to relate, how, during that illness, many scripture passages,
both out of the old and new Testament,
had been unfolded to his mind with great clearness and comfort,
respecting the plan devised by divine love for the restoration of poor fallen man,
and the salvation of sinners.--After setting forth the fall of man,
through the temptation and subtlety of Satan,
and his aspiring above the station appointed him by divine wisdom,
he proceeded to open some of those passages,
beginning with the promise of the seed of the woman,
that should bruise the head of the serpent; and enlarged upon many scripture testimonies,
showing that this Seed is Christ; even He who died for our sins on the cross,
and who is a propitiatory sacrifice for the sins of the whole world,
an Advocate with the Father, and Mediator between God and man.
He enlarged upon what faith in God, and in our Lord and Saviour Jesus Christ,
had done in every generation; then emphatically said, "`This is also my faith,
and I shall die in it, as I have lived, hoping in God`'s mercy,
through our Lord and Saviour Jesus Christ.`"

On the 18th of the month, being alone with a Friend,
he entered into conversation on the present state of Society, and remarked,
that there were many under our name, who had made a mere profession,
but had never been convinced of, nor yielded obedience to,
the principles and doctrines of Friends,
and it was no marvel if such were carried off with unsound notions.
He said, he believed it had been permitted, in order to manifest such as these,
but he was firm in the faith, that the ancient doctrines and principles of the Society,
as set forth in the scriptures, would prevail:
and all those who were building on Jesus Christ, would be preserved,
amid all the storms and commotions that now agitated the Society;
and it would yet arise and shine in more of its ancient
beauty than many now living have ever seen it;
adding, "`I may not live to see it,
but there are some of you that will.`"--He remarked to a Friend who called to see him;
"`It is a satisfaction to reflect that my outward
concerns are all settled.`"--After a solemn pause,
he added, "`I know that I am a poor creature,
and have nothing to depend on but the mercy of a gracious God,
through Christ Jesus my Lord.
Oh, these poor things that are trying to do away all
belief in the authenticity of the scriptures,
and in a Saviour, what will become of them!
No other foundation can any man lay than that which is
laid.`"--His bodily sufferings were at times great,
but he was preserved in patience and resignation to the divine will,
and several times he ejaculated with much earnestness, "`Oh,
blessed Saviour I--Oh Lord Jesus help me,`"--evincing that his
dependence was placed upon the Physician of value.

A few days before his decease, he remarked to a Friend,
that the crisis had not been shown to him, when he should be taken;
but from the way he felt, he thought it could not be much longer.
The Friend intimating that she supposed he thought he should not recover, he answered,
"`I leave it all to him who knows how to order all things for the best.
I have no desire but that his blessed will may be done.`"

On sixth-day, the 13th of tenth month, he became much worse,
and about three o`'clock on seventh-day morning,
the approaching change was apparent.--He was in much suffering until about ten o`'clock,
when the conflict seemed to be nearly over; and breathing shorter and shorter,
he quietly and calmly departed, about a quarter after eleven o`'clock, that forenoon,
in the seventieth year of his age, being a minister about forty-five years.

Read and approved at an adjourned Monthly meeting of men and women Friends,
held at Haddonfield, New Jersey, the thirteenth-day of the third month, 1827,
and directed to be signed by the clerks of the respective meetings,
and forwarded to the Quarterly meeting.

[.signed-section-signature]
John M. Kaign, Sarah Clement, Clerks.

Read and approved in Haddonfield Quarterly meeting, held third month fifteenth, 1827,
and directed to be signed and forwarded to the Meeting for Sufferings.

[.signed-section-signature]
David Roberts, Clerk.
